### ISSUE TITLE
can't reopen popup

### ISSUE THREAD

**Issue by GDreyV** [Adobe-CEP/CEP-Resources#10]
I faced a problem hope you can help me. I have extension with popup.
Here is description for popup:

``` xml
<UI>
    <Type>Modeless</Type>
    <Lifecycle>
        <AutoVisible>false</AutoVisible>
    </Lifecycle>
    ...
</UI>
```

popup is opened in pretty simple way:

``` javascript
var cs = new CSInterface();
cs.requestOpenExtension("my.extension.popup");
```

When I close popup and try to reopen it everything works fine. But if I close main panel while popup is opened popup is closed automatically and I it can't be reopened after panel is started again. Do you have any ideas what I'm doing wrong?

Thanks

**Comment by arthurwei1975** [comment]
In the popup extension's manifest, you set <AutoVisible>false</AutoVisible>. Do you do anything to make it visible in the extension's code? Maybe you should set AutoVisible to true. Thanks

**Comment by GDreyV** [comment]
As I understand AutoViible makes sense only for Panel items to make them opened or closed by default.
Anyway I checked true and false for AutoVisible with different values for StartOn Event and behavior was the same.
To make popup visible I just call requestOpenExtension in main panel.

**Comment by lesavage** [comment]
Are your panel and modeless dialog contained in a bundle e.g. defined in the same manifest file similar to our Test Extension (https://github.com/Adobe-CEP/Samples/blob/master/CEP_HTML_Test_Extension/CSXS/manifest.xml) or delivered separately?

If you download our Test Extension and attempt to launch your modeless dialog (CS APIs > Open/Close Extension > Get All Extensions) and then complete the above workflows, do you see the same behaviour?

**Comment by GDreyV** [comment]
Thanks for example. Yes, I managed to reproduce it:
Run CEP HTML Panel 1;
choose CSXS APIs;
then Open/Close Extension;
click Get All Extensions and run CEP HTML Test Modeless Dialog;
close CEP HTML Test Panel 1 (just opened CEP HTML Modeless Dialog will be closed automatically);
try to do the same once again. I didn't manage to reopen CEP HTML Test Modeless Dialog.

**Comment by lesavage** [comment]
Can you confirm your environment setup so we can investigate it further:
Mac/Windows? OS version?
Adobe Application and version?
Thanks.

**Comment by GDreyV** [comment]
Here is what I've got from System Info. Hope it helps
Adobe Photoshop Version: 2014.2.2 20141204.r.310 2014/12/04:23:59:59 CL 994532  x64
Operating System: Windows 8.1 64-bit
Version: 6.3

**Comment by lesavage** [comment]
Hi. I can confirm that I see this behaviour so thank you for reporting it. I will look to get this fixed in a future release.

**Comment by arthurwei1975** [comment]
If the popup dialog is simple, you can try to use a pure JavaScript dialog, rather than a separate modeless CEP extension.

**Comment by GDreyV** [comment]
Yeah, the point of the modeless popup was ability to work with both panels and reflect changes. As temporary workaround I'm using modal dialog. It's not really user friendly and what I was looking for but it's still better than nothing :)

**Comment by arthurwei1975** [comment]
This bug will be fixed in next version of CEP. Thanks

**Comment by arthurwei1975** [comment]
This bug should have been fixed in Photoshop CC 2015 November release.
