### ISSUE TITLE
Photoshop CC extension close after few minutes

### ISSUE THREAD

**Issue by mds-charu** [Adobe-CEP/CEP-Resources#100]
As soon as I start remote debugging photoshop extension closes automatically. Not able to debug.

**Comment by stompychump** [comment]
There are reportedly some issues with using recent versions of Chrome for debugging extensions. Try using Chromium v41.0.2272.0 instead, which is the version that runs inside Photoshop CC 2015.1:

http://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/310963/
http://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/310963/

If you have trouble with conflicting user profiles, set up a separate profile folder and call Chromium with the "--user-data-dir" argument. For example in Windows:

`chrome.exe --user-data-dir="C:\Users\<user>\AppData\Local\Chromium\User Data 41.0.2272.0"`
