### ISSUE TITLE
ExManCmd license

### ISSUE THREAD

**Issue by thebinaryartist** [Adobe-CEP/CEP-Resources#107]
Hi,
i plan to develope an open source standalone installer for Adobe CC Extensions. I want to use and redistribute ExManCmd in the installer, but I can't find any license information for ExManCmd. Is it possible to distribute it within my installer?

Thanks

**Comment by totorototo** [comment]
Hi,
I do not know if you can distribute those in your application, but some projects already do that:
Just take a look at: https://github.com/CreativeDo/ZXPInstaller
Just ask them if they did something special to redistribute ExManCmd.

Thomas.

**Comment by bbb999** [comment]
ExManCmd has been approved for redistribution.
