### ISSUE TITLE
error message that doesnt make sense AND //@include in photoshop script/CEP

### ISSUE THREAD

**Issue by chrisrplay** [Adobe-CEP/CEP-Resources#11]
2015-05-19 16:47:14 : INFO  Remove of include search path for JS scripts is not supported by this host application

Besides the fact that message doesnt make sense in English,
does this mean we can't //@include when the function is called from CEP (it works if I open it as a script in photoshop)?

If so, how to get JSON.parse working in a photoshop script? I dont seem to be able to include jamJSON.
The only thing I can think of writing files out if I cant parse jSON in photoshop, like the old days of photoshop scripting...

**Comment by chrisrplay** [comment]
Ok, I can at least cut-n-paste jamJSON into my script file, but that's a hacky duct-tape solution.

**Comment by lesavage** [comment]
Does this help? https://forums.adobe.com/thread/1392408
