### ISSUE TITLE
node.js implementation inquiry

### ISSUE THREAD

**Issue by codearoni** [Adobe-CEP/CEP-Resources#113]
Currently, extensions utilize io.js v1.2.0

This is quite out-of-date, and I was curious if there is any plan to update to a more modern version of node this year. Additionally, would it be reasonable to expect the node.js version to be updated simultaneously with all Adobe products, or would it happen on a product-by-product basis?

Very curious, cheers!

**Comment by venpa** [comment]
Yes, we do have the plan for upgrading the nodejs version to 7.5 or higher in the upcoming CEP 8.0 release. CEP is a component for Adobe host applications, so it's the host application's decision to integrate CEP in to their product release. This way, each host application might release CEP 8.0 with different timelines. You can expect Adobe products with above mentioned nodejs version in post June releases.
We also have the plan for upgrading nodejs, Chromium and CEF in shorter timeline going forward.
