### ISSUE TITLE
URGENT - ZXPSignCmd is not working anymore (timestamp fail)

### ISSUE THREAD

**Issue by Jolg42** [Adobe-CEP/CEP-Resources#115]
Hi,

It looks like GeoTrust just took down the timestamp service "https://timestamp.geotrust.com/tsa" because it was deprecated, resulting in the impossibility to sign any extension. **I currently can't sign our extension to send it to our users.**

This issue is happening with the latest ZXPSignCMD (4.0.7)
https://github.com/Adobe-CEP/CEP-Resources/tree/master/ZXPSignCMD/4.0.7/osx10

Here is what I just found on Reddit: https://www.reddit.com/r/java/comments/66b0pf/maven_jarsigner_plugin_alternatives_fallback_to/
> By April 2017, we will decommission the "Legacy" timestamping service (see below).
(Legacy) RFC 3161 Service SHA128: https://timestamp.geotrust.com/tsa
To support business continuity for our customers, we have provided the following replacement services. All Code Signing customers must migrate to the "new" service URLs by March 31, 2017 in order to avoid service disruption (see below).
(New) RFC 3161 Service SHA256: http://sha256timestamp.ws.symantec.com/sha256/timestamp
Important: Customers must leverage SHA256 Timestamping service going forward, and should not use a SHA1 service unless there is a legacy platform constraint which doesn't allow use of SHA2 service (in this case you can use this new URL: RFC 3161 Service SHA128: http://sha1timestamp.ws.symantec.com/sha1/timestamp).

It looks like I can do anything about it, I tried the new urls without success, I think that the only way to fix it is to change the old timestamp url to the new one and rebuild ZXPSignCMD to make it work work again.
 
Ping @yugguo @arthurwei1975 @bbb999

**Comment by Jolg42** [comment]
Apparently GeoTrust sent an email about that last 22nd of February (from GeoTrust support) and here is the link to the announce https://knowledge.symantec.com/support/code-signing-support/index?page=content&id=ALERT2248

**Comment by Jolg42** [comment]
Here is the error returned by ZXPSignCmd 4.0.7 with the new urls `http://sha1timestamp.ws.symantec.com/sha1/timestamp`
`http://sha256timestamp.ws.symantec.com/sha256/timestamp`

`Error - the timestamp returned from the chosen TSA could not be verified, so the ZXP created is likely to be rejected by other tools. Please recreate your ZXP with a different trusted TSA.`

**Comment by Max-Playstudios** [comment]
Does the "-tsa" option still work? I can't verify, just remember from documentations...

http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/creativesuite/pdfs/SigningTechNote_CC.pdf

"To create a signed package:
ZXPSignCmd -sign <inputDir> <outputZxp> <p12> <p12Password> [options]
inputDir The path to the folder containing the source files to package.
outputZxp The path and file name for the ZXP package.
p12 The signing certificate; see “How signing works” on page 5.
p12Password The password for the certificate.
**options -tsa <timestampURL> The timestamp server.** For example:
https://timestamp.geotrust.com/tsa"

**Comment by Jolg42** [comment]
@Max-Playstudios Yes, I'm actually using it but as the timestamp server "https://timestamp.geotrust.com/tsa" was turned off by GeoTrust it's not working anymore :(

**Comment by meyer** [comment]
@Jolg42 have you tried specifying a _different_ timestamp server with the `-tsa` option that @Max-Playstudios mentioned?

**Comment by Jolg42** [comment]
@meyer Yes I tried and I had the `Error - the timestamp returned from the chosen TSA could not be verified, so the ZXP created is likely to be rejected by other tools. Please recreate your ZXP with a different trusted TSA.` for 
'http://sha1timestamp.ws.symantec.com/sha1/timestamp'
'http://sha256timestamp.ws.symantec.com/sha256/timestamp'

Is it working for you right now?

**Comment by bbb999** [comment]
Neither of those work, here.

**Comment by akshitSinghal1989** [comment]
Meanwhile can you please try TSA as [](http://timestamp.digicert.com/)
Hope it works.

**Comment by akshitSinghal1989** [comment]
Meanwhile can you please try:  http://timestamp.digicert.com/
Hope it works with ZXPSignCmd.

**Comment by QStack** [comment]
@akshitSinghal1989 This works for me. Thanks for the link

**Comment by Jolg42** [comment]
I did a new build with `http://timestamp.digicert.com/` and `PlayerDebugMode false` and it looks like it's working (only tested AI CC 2017 on Mac for now).

Thank you @akshitSinghal1989 ;)

**Comment by murphysm2342** [comment]
@Jolg42 How do you build with `PlayerDebugMode false` ?  I've been trying to create a new ZXP with the new tsa url but ZXPSignCmd just displays its usage info.

**Comment by bbb999** [comment]
PlayerDebugMode is unrelated to signing extensions; it governs whether host applications load unsigned extensions.

**Comment by murphysm2342** [comment]
That is what I was thinking but confused why it was included with being successful.  Any thoughts on why I might only be getting ZXP usage commands output?  I literally only changed the tsa URL in the command I've been using for at least a year or two.

**Comment by bbb999** [comment]
Sorry, no ideas. Thankfully, with the new timestamp server, ZXPSignCmd is once again working for me. 

What's the entire command line you're passing to ZXPSignCmd?

**Comment by murphysm2342** [comment]
making the working directory as cd (contains ZXPSignCmd and panel extension folder).

command line (password *** out): 
`./ZXPSignCmd -sign SBProductRetouch SBProductRetouch.zxp SeanMurphy2017Cert.p12 *** –tsa http://timestamp.digicert.com/`

same results creating the new certificate:
`./ZXPSignCmd -selfSignedCert US WI “Shopbop” “Sean Murphy” *** SeanMurphy2017Cert.p12`

Have tried several tsa URLs recommended on a few posts:
http://tsa.starfieldtech.com
http://sha256timestamp.ws.symantec.com/sha256/timestamp
http://timestamp.comodoca.com
http://timestamp.verisign.com/scripts/timstamp.dll
http://timestamp.digicert.com

**Comment by Jolg42** [comment]
@murphysm2342 this is working for me:
```
./ZXPSignCmd -sign "ABSOLUTE_PATH_TO_FOLDER" OUTPUT.zxp cert.p12 "CERT_PASSWORD" -tsa http://timestamp.digicert.com
```

**Comment by Jolg42** [comment]
Make sure you have the latest `4.0.7` binary, available here: https://github.com/Adobe-CEP/CEP-Resources/tree/master/ZXPSignCMD

**Comment by bbb999** [comment]
> ./ZXPSignCmd -sign SBProductRetouch SBProductRetouch.zxp SeanMurphy2017Cert.p12 *** –tsa http://timestamp.digicert.com/

I'd try a trailing slash, on SBProductRetouch: 

./ZXPSignCmd -sign SBProductRetouch/ SBProductRetouch.zxp SeanMurphy2017Cert.p12 *** –tsa http://timestamp.digicert.com/

**Comment by murphysm2342** [comment]
Looks like it is an issue with Terminal on my computer.  Switched to a different computer and everything works fine with the above commands.  Thanks for the help.

**Comment by michalfapso** [comment]
> Make sure you have the latest `4.0.7` binary, available here: https://github.com/Adobe-CEP/CEP-Resources/tree/master/ZXPSignCMD

Thanks, @Jolg42, I can confirm that `4.0.7` works with `-tsa http://timestamp.digicert.com/`, while the older version I've used before always gave the error.
