### ISSUE TITLE
How to get current selected image path in custom CC Bridge Extension Panel

### ISSUE THREAD

**Issue by pawan-mittal** [Adobe-CEP/CEP-Resources#125]
Hi Team,

I have created a custom HTML5 Extensional Panel for CC Bridge. I just want to know how can I get the image path for an image selected in CC Bridge. 

Can I get it ? 

One more thing - Can I edit keywords field in Metadata panel from my custom panel? I want to do it to sort/categorise image based on these keywords.

**Comment by pawan-mittal** [comment]
@bbb999 can you please guide me through right steps ?

**Comment by bbb999** [comment]
Sorry, I have zero experience with Bridge's APIs.

**Comment by pawan-mittal** [comment]
It's not specific to Bridge APIs'. Do you have any doc for Bridge APIs. I was thinking it should be a general way of doing it. Like CSInterface.js.

**Comment by bbb999** [comment]
I have zero docs for Bridge APIs.

**Comment by bbb999** [comment]
[I'm responsible for Adobe's video and audio applications.]

**Comment by pawan-mittal** [comment]
Thanks. Same thing if we want to in PhotoShop then are there any specific APIs.

**Comment by pawan-mittal** [comment]
I am now able to access CC Bridge APIs (.JSX scripts) and completed the task.

**Comment by fcarrilLB** [comment]
@pawan-mittal sorry for bother you, how did you solve the issue? I wasn't able to run any JSX in Bridge, could you share me your manifest.xml?
