### ISSUE TITLE
Update internal chrome version

### ISSUE THREAD

**Issue by Webysther** [Adobe-CEP/CEP-Resources#126]
Any schedule for update internal chrome version from 41 to new one? Only [Polymer](https://www.polymer-project.org/) 1.x works.

**Comment by Jolg42** [comment]
They should update it in the next version that will be released at Adobe's Max conference in October

**Comment by Jolg42** [comment]
You could sign up on Adobe's Pre-release Forum here https://www.adobeprerelease.com/ for the "Creative Cloud Developer Prerelease"

**Comment by Webysther** [comment]
I have access and see now the latest, great! :+1:
