### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by sdaitzman** [Adobe-CEP/CEP-Resources#127]
Is there an introductory guide anywhere on this repository? Or perhaps elsewhere?

**Comment by bbb999** [comment]
Any guide generic enough to include all CEP hosts, would be nearly meaningless. :)

For which applications would you like to develop extensions?

**Comment by sdaitzman** [comment]
@bbb999 thank you for your prompt response. I am writing a script for Illustrator CC 2017. Perhaps I misunderstood what CEP does exactly? Basically, I want to write a script that I can execute in Illustrator and that uses some modules from npm. I was told that CEP would allow me to do so. Is this the case? Thanks again!

**Comment by bbb999** [comment]
CEP = Common Extensibility Platform, or "how Adobe apps host web pages in their UI, and gives them scripting super powers".

Here's our flagship "CEP HTML Test Panel", which shows off all the fun stuff you can do from within a panel: 

https://github.com/Adobe-CEP/Samples/tree/master/CEP_HTML_Test_Extension

I don't know which among our sample panels most closely resembles what your script is trying to do; if possible, I'd start from a very, very simple example (Trello and Twitter are good), clone that, then 'graft' your Illustrator script execution onto it. 

Potentially helpful: I made a screen video showing how to debug panels at both the JavaScript and ExtendScript levels:

https://www.dropbox.com/s/lwo8jg0klxkq91s/walkthru.mp4

[If you were integrating with our video apps, I could be of more direct assistance...]

**Comment by sdaitzman** [comment]
@bbb999 I think I misunderstood what CEP does. I was led to understand it as a successor to the ExtendScript system for making extensions. If all I want to do is create a script, in JS, that manipulates the selection in Illustrator when run, is this the right tool?

**Comment by Silly-V** [comment]
The development educational course written by Davide Barranca is an invaluable resource:
https://www.davidebarranca.com/2016/03/adobe-photoshop-html-panels-development-course-released/

What kind of node npm module things are you planning on using? Could some of it be just possible in regular .jsx extendscript? It would be infinitely easier..

**Comment by sdaitzman** [comment]
@Silly-V I am going to try just using extendscript. I will come back and look through that educational course if I can't get around it. Thank you for all of your help!

**Comment by bbb999** [comment]
CEP isn't a replacement; it's an improvement / enablement. 

CEP hosts web pages, backed by JavaScript, in our apps. 

CEP panels are the best place from which to execute ExtendScript, which is what our apps' scripting engines use.

**Comment by Silly-V** [comment]
You can join the group of AI junkies at the Illustrator scripting forum, to see a lot of what's possible/impossible. Regarding AI, the scripting commands are more limited compared to Photoshop and most of all, Indesign. To make up for lack of general documentation, the forums have served as a knowledge repository for years and years! We'd be glad to assist.
