### ISSUE TITLE
Error - Failed to zip directory into output file. ZXP not created. Does the ZXP already exist?

### ISSUE THREAD

**Issue by joydeep1982** [Adobe-CEP/CEP-Resources#128]
I am trying to use the ZXPSignCmd for linux
But getting the below error when I am trying to execute the command
[dayadmin@uw2010250118187 zxp_utility]$ /apps/zxp_utility/zxpsigncmd_linux -sign /apps/zxp_utility/Encrypted_CodenbergIoillustratorplugin_1_1_0 /apps/zxp_utility/Encrypted_CodenbergIoillustratorplugin_1_1_0.zxp /apps/zxp_utility/an_adobe_exchange_user.p12 AgoraZXPsRuleOKSETEH114DF -tsa http://sha256timestamp.ws.symantec.com/sha256/timestamp
DebugErr: ZXP could not be created.
DebugErr: ZXP could not be created.
Error - Failed to zip directory into output file. ZXP not created. Does the ZXP already exist?

**Comment by bbb999** [comment]
I've never heard of anyone successfully creating a .zxp file, on Linux. Any chance you could try on Mac or Win?

**Comment by rafiya** [comment]
This issue was resolved when we noticed that the VM we were trying on didn't have gzip.
Anyway, Now i am facing the same issue for files which have a size greater than 500MB. can anyone help?

**Comment by hennadiy-kudashev** [comment]
@joydeep1982, Could you please share your zxpsigncmd_linux script.

**Comment by rafiya** [comment]
@hennadiy-kudashev , this issue was resolved when we figured that the machine we were trying out on didn't have the zipping tool. Are you facing similar issues ?

**Comment by hennadiy-kudashev** [comment]
Thanks for response. 
Not the same issue. I have tried to run mac os binary(ZXPSignCmd) on linux without success. 
I see that you have used **zxpsigncmd_linux**. Has you somehow converted **mac os binary** to **linux binary**? If so, could you please share it. Thanks in advance.

**Comment by joydeep1982** [comment]
thanks all for your response

**Comment by greyfairer** [comment]
@joydeep1982 where did you get the zxpsigncmd_linux command from? Compiled your own?

**Comment by greyfairer** [comment]
I tried to run zxpsigncmd on wine, but that doesn't work yet. https://github.com/greyfairer/zxpsigncmd-docker

**Comment by jdelibas** [comment]
@joydeep1982 I'm also wondering where you got the `zxpsigncmd_linux` command from, any chance you could share or point us in the right direction?

**Comment by joydeep1982** [comment]
@greyfairer and @jdelibas I was provided the same from my org, unfortunately I can't share the same with you, will definitely check and let you know from where you can download the same.

**Comment by pmichel-J2S** [comment]
@joydeep1982 That would be highly appreciated, indeed. Thanks in advance ;)
