### ISSUE TITLE
YouTube videos with webm vp9 codecs not playing in CEP 8

### ISSUE THREAD

**Issue by zhangusc** [Adobe-CEP/CEP-Resources#134]
YouTube videos that are encoded in webm vp9 codecs do not play in the new version of CEP 8, Chromium 57.0.2987.74. Host information is missing. It could be a bug in Chromium. Videos with mp4 codecs are okay. To reproduce the issue, use the link below
https://www.youtube.com/watch?v=BdbCUMCJ_0M&index=1&list=PLGZUzt4E4O2K7MQjlQkM8D6z3E6DKkiOx. 
![image](https://user-images.githubusercontent.com/7468979/31508374-ac0068d4-af32-11e7-806d-a35552d30c20.png)

**Comment by venpa** [comment]
Thanks @zhangusc for reporting this issue. This is expected as webm is not approved Adobe's legal team to use within CEP.

**Comment by zhangusc** [comment]
@venpa Thank you for the quick response. So this is something new? webm vp9 is supported in CEP 7 though. If it is no longer supported in CEP 8 due to some legal issue, is there a workaround to play those videos in other codecs like avc? YouTube has ten of videos in vp9 and they are broken in CEP 8.

**Comment by bbb999** [comment]
@venpa With whom shall I follow up, in Adobe Legal?

**Comment by bbb999** [comment]
It turns out that WebM VP9 codecs have some legal encumbrances, and are not included in open source'd chrome browser code. More info as it becomes available.
