### ISSUE TITLE
"ReferenceError: require is not defined" when reloading in CEP 8

### ISSUE THREAD

**Issue by noamraby-ssky** [Adobe-CEP/CEP-Resources#139]
Hi all,

Our team has been experimenting with CEP8 in After Effects 2018 in the past week. We noticed that reloading by CTRL+R in devtools or by window.location.reload() results in an error - "ReferenceError: require is not defined"

Has anyone else encountered this? Is there an elegant workaround?

**Comment by undavide** [comment]
Try adding in the `manifest.xml` 
```
<CEFCommandLine>
  <Parameter>--enable-nodejs</Parameter>
  <Parameter>--mixed-context</Parameter>
</CEFCommandLine>
```
It's a known bug AFAIK.

**Comment by noamraby-ssky** [comment]
Thanks, David!
I was just reading your [blog post about CEP8](http://www.davidebarranca.com/2017/10/html-panel-tips-25-cc-2018-survival-guide/) and it works beautifully.

**Comment by fcarrilLB** [comment]
@undavide I have the same issue, I added the `--enable-nodejs` and `--mixed-context` parameters, it works fine in Premiere Pro 2018, but, in Illustrator CC 2018 it doesn't work fine

In Illustrator, if I refresh the page the `window.cep_node.require` still exists and I can use simple node.js modules like `fs` and create files and directories, but for example, `window.require` doesn't exist anymore (and I am not sure what else) and when I use a complex library with a lot of files like `aws-sdk` it stop working

In few words, in Premiere it works fine in all the cases, in Illustrator if I refresh I can't use any complex library

Do you have any idea how I could fix this?
