### ISSUE TITLE
PhotoshopJSONCallback example missing

### ISSUE THREAD

**Issue by undavide** [Adobe-CEP/CEP-Resources#14]
Hi, 
in the CEP JavaScript programming (subsection Specific Events in Products, Photoshop -> about the com.adobe.PhotoshopCallback replacement) it's written: 
"A sample of using this event:"
But then no sample is provided, and "Invoke point product's scripts from html extension" section starts.
Thanks

Davide

**Comment by lesavage** [comment]
Fixed now. I forgot to go back to that placeholder yesterday and add the link to the sample once it was uploaded. :)

**Comment by undavide** [comment]
Thank you for the super-quick response Lea :-)
