### ISSUE TITLE
TSA could not be verified on Win 7

### ISSUE THREAD

**Issue by ADukal** [Adobe-CEP/CEP-Resources#15]
Since the update, using this newest ZXPSignCmd it's impossible to create / timestamp new ZXP files, on Windows 7 this is the error received (using https://timestamp.geotrust.com/tsa):
> Error – the timestamp returned from the chosen TSA could not be verified, 
> so the ZXP created is likely to be rejected by other tools. Please recreate your 
> ZXP with a different trusted TSA.

**Comment by arthurwei1975** [comment]
Please try https://github.com/Adobe-CEP/CEP-Resources/tree/master/ZXPSignCMD/3.0.19

Thanks
