### ISSUE TITLE
Impossible to debug CEP 7

### ISSUE THREAD

**Issue by AAverin** [Adobe-CEP/CEP-Resources#151]
I am testing my HTML panel in Adobe Photoshop 2017, and debugging is absolutely broken.
When I visit localhost:8009 (which is my photoshop debug port) I see a broken chrome developer tools UI which is unresponsive

<img width="1367" alt="screen shot 2017-12-14 at 18 03 35" src="https://user-images.githubusercontent.com/1481332/34004795-26f05a34-e0f9-11e7-8a7b-51e12b0cc90e.png">

**Comment by Jolg42** [comment]
You should try again with the "CEF_client" from https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_7.x for CEP 7 or https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_8.x for CEP 8

**Comment by AAverin** [comment]
@Jolg42 it worked, thanks
Have another problem now, I'll make a new ticket for it
