### ISSUE TITLE
Extensions don't show up in Photoshop.

### ISSUE THREAD

**Issue by cropher** [Adobe-CEP/CEP-Resources#155]
Hey everyone,

I'm new to CC Extension development and I'm hitting a brick wall. I can't bring any extensions to show up in PS. I am now trying out Adobe's [HelloWorld extension provided in this short guide](http://www.adobe.com/devnet/creativesuite/articles/a-short-guide-to-HTML5-extensions.html) to try to determine what the problem is.

What I changed in the index.html:

I included PHXS version 19.0 (the current PS version, which is also the one I'm using):

`<Host Name="PHXS" Version="[14.0,14.9,19.0]"/>
`

I updated the CSXS version:

`<RequiredRuntime Name="CSXS" Version="8.0"/>
`

I placed the files in **AppData\Roaming\Adobe\CEP\extensions\HelloWorld**

My folder structure is correct (**HelloWorld > index.html** and **HelloWorld >CSXS>manifest.xml**)

PlayerDebugMode is added (here: **\HKEY_CURRENT_USER\Software\Adobe\CSXS.8**) and set to 1 .

But it doesn't appear in the PS extensions menu. I would be very thankful if someone could point out what's going wrong here.

(This repo seemed like the best place to ask this, but feel free to point me in a different direction.)

**Comment by bbb999** [comment]
I'm not sure what CEP/CSXS version Photoshop 19.0 ships with, so I can't say whether CSXS.8 is the right place to set PlayerDebugMode...

To confirm that versioning _isn't_ the problem, you might try saying your extension works in every version since 10.0, or something...

<Host Name="PHXS" Version="10.0" />

**Comment by cropher** [comment]
Thanks for the suggestion. I'm not sure I understand the second part of your post, but here's what I did to exclude versioning as the root of the problem:

I added PlayerDebugMode to CSXS.3 through 8. I then changed the CSXS version in the manifest.xml from 8 to 7 and so on, launching Photoshop CC2018 each time. Nothing changed.

I then changed the manifest to also support PHXS Version 17.0 and did the whole thing again with PS CC 2015.5, but the extension didn't show up there, either.

What you're saying is that I should try PHXS Version 10.0 next and see if it works in Photoshop CS3? (Sorry if I'm getting this wrong).

**Comment by Klustre** [comment]
Change 

`<Host Name="PHXS" Version="[14.0,14.9,19.0]"/>`

to 

`<Host Name="PHXS" Version="14.0"/>`

This makes the extension support version 14 and up. When using brackets it means support version x _up to, and including_ y. It's not an array of supported versions.

Read more on version notation [here](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/Documentation/CEP%208.0%20HTML%20Extension%20Cookbook.md#important-manifest-change-for-cep-50-extensions).

**Comment by mds-charu** [comment]
Please change following lines in the manifest file
**<RequiredRuntime Name="CSXS" Version="8.0"/>**
to 
**<RequiredRuntime Name="CSXS" Version="7.0"/>**
and
**<Host Name="PHXS" Version="[14.0,14.9,19.0]"/>**
to
**<Host Name="PHXS" Version="14.0"/>**

even if you are using Photoshop 2018 version.

And also, add **PlayerDebugMode** property **\HKEY_CURRENT_USER\Software\Adobe\CSXS.7**

**Comment by cropher** [comment]
Ah, now it works! I had no idea that the brackets meant "up to and including". Now I also get what you meant, @bbb999 .

Thank you all for taking the time to help a rookie out! :)

**Comment by noamraby-ssky** [comment]
Version as a list is a range and from my experience should contain two numbers - 
`"[min_version, max_version]"`
So in your case 
`Version="[14.0,19.0]"`
