### ISSUE TITLE
[Windows] ZXPSignCmd immediately crashes when creating self-signed cert

### ISSUE THREAD

**Issue by sonictk** [Adobe-CEP/CEP-Resources#16]
Hi all:

I'm starting to get into development of Photoshop CC extensions on Windows, and I'm running into issues with the ZXPSignCmd command line utility.

When trying to create any certificate, it crashes immediately with the following error:

http://i.imgur.com/V5C65Sl.png

I can't find any crash log or anything like that, so I'm wondering what on earth is going on. This is happening with any Windows machine that I've tested it on, whether Windows 7/8. Tested on both physical machines and a clean Win 8.1 VM with only the MSVC redistributables installed.

The command I'm running is:

`ZXPSignCmd -selfSignedCert 1 MI FrostburnStudios sonictk testPassword cert.p12`

I have tried both the binary in this repo along with both the x86/x64 versions available at: http://labs.adobe.com/downloads/extensionbuilder3.html

In both cases, they both crash with either the BEX or BEX64 error.

I should mention that running `ZXPSignCmd -verify <package.zxp>` and `-sign` commands seems to work fine, so the binary is not completely broken; only generating self-signed certificates seems to be crashing.

Anyone who has a solution for this, I'd very much appreciate it!

**Comment by sonictk** [comment]
My colleague just found the issue: changing the country code from 1 to `US` allows it to build.

**Comment by fgregor** [comment]
Hi sonictk - yes, the "1" is the problem as it expects an ISO country code such as "US". It certainly shouldn't crash, though - we'll get this fixed as soon as we can.

Thanks for bringing it to our attention!
