### ISSUE TITLE
Blank Panel on Windows Ai CC 2018

### ISSUE THREAD

**Issue by raven001** [Adobe-CEP/CEP-Resources#162]
Adding PlayerDebugMode in the registry works but if I close and open the panel then navigate to a diiferent page the panel became blank.

**Comment by bbb999** [comment]
If it opens correctly at least once, then PlayerDebugMode is not the problem.

**Comment by raven001** [comment]
It is working fine in mac and only encountered in windows

**Comment by bbb999** [comment]
That's a good lead; I'd pepper any platform-dependent code in your panel with breakpoints, and see what's happening.

**Comment by raven001** [comment]
but sometimes it will load with a blank panel. It's pretty much inconsistent, but I encountered it consistently when closing and then opening the panel and navigate to different page

**Comment by bbb999** [comment]
The fact that it sometimes loads at all,  preclude the possibility that it is a PlayerDebugMode issue.

 The fact that it works intermittently, suggest a problem in your panels response to being loaded. 

 I’d put breakpoints in your OnLoaded()  response, put a refresh button in your panels UI, and debug into your panel’s loading sequence.

**Comment by raven001** [comment]
[](url)
![image](https://user-images.githubusercontent.com/25901779/35293046-77eb208a-00ad-11e8-9f08-79f22e772b15.png)

**Comment by raven001** [comment]
the panel went totally blank. I didn't encounter any bug.

**Comment by bbb999** [comment]
Not sure what to tell you. Perhaps debug it on the platform where you _have_ seen it work?

**Comment by raven001** [comment]
It doesn't crashed when I update the Type to modeless instead of Panel.

**Comment by ErinFinnegan** [comment]
I had this problem, too. I've been making an Ai sample panel but it was blank when I opened it in Windows. Ultimately I had to download the [CSInterface.js](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/CSInterface.js) file again, and I copied a `manifest.xml` file from a working panel. I was never sure what the error was.

**Comment by raven001** [comment]
@ErinFinnegan  Hi, would you mind giving me the manifest.xml. I've already downloaded the CSInterface.js and it still doesn't work.

**Comment by ErinFinnegan** [comment]
Sure... I also messed around with the version numbers in the manifest. I think you can see here where I commented out how I wrote the version numbers in that had worked on Mac OS but failed on Windows: 

```      <Host Name="ILST" Version="21.0"/>
<!-- <Host Name="ILST" Version="[22.0,1000.0]"/> -->```

https://gist.github.com/ErinFinnegan/ef8ea95d4de4ea69565d076eabbda8f0

**Comment by ErinFinnegan** [comment]
Can you email me? finnegan (at) adobe.com 

Meanwhile, another thing to try is to look on the Adobe Exchange for a free Illustrator plug-in and see if you can get it to work. I had some trouble with this also! Maybe there's a weird Windows issue.

**Comment by raven001** [comment]
Hi,
Thanks for the help, really appreciate it. I email you my manifest.js

**Comment by acswift** [comment]
For future people who come here… I have found that comments in manifest.xml cause the panel to fail:
```
<!-- <Host Name="ILST" Version="[22.0,1000.0]"/> -->
```

**Comment by tsmusty** [comment]
So what should be done?

**Comment by tsmusty** [comment]
I don't have any comment on mine, I was working all fine but now blank screen. I have done all possible
