### ISSUE TITLE
Adobe Photoshop 2018 Panel Problems

### ISSUE THREAD

**Issue by timc3** [Adobe-CEP/CEP-Resources#174]
I have found a couple of problems with my Panel that is specific to Photoshop:

1. Panel can't be resized (I think this is a known bug)
2. Focusing away from a panel unloads it. So if a panel is docked into a group of tabs and I tab between them my panel is reloaded once it's back in focus.

I am 99% sure this didn't happen in 2017

**Comment by tomzag** [comment]
1) Define also the MaxSize in the manifest file
2) Making a panel persistent in Photoshop: 

`var Persistent = function(inOn){
  if(inOn){
    var event = new CSEvent("com.adobe.PhotoshopPersistent", "APPLICATION"); 
  } else {
    var event = new CSEvent("com.adobe.PhotoshopUnPersistent", "APPLICATION"); //Photoshop
  }
  event.extensionId = <extension id as per manifest definition>;
  csInterface.dispatchEvent(event);
 }
 
Persistent(true); //persistent to prevent extension from unloading`

**Comment by timc3** [comment]
Thanks @tomzag - that worked nicely.
