### ISSUE TITLE
Version 3.0.19 Win 64 Error

### ISSUE THREAD

**Issue by ADukal** [Adobe-CEP/CEP-Resources#18]
I'm sorry but the new ZXPSignCmd Version 3.0.19 Win 64 just doesn't work.
I did a quick try on my Windows 7 64bits and the message in spanish says:

"Esta versión de ZXPSignCmd.exe no es compatible con la versión de Windows que está ejecutando. Compruebe la información de sistema del equipo para consultar si necesita una versión x86 (32 bits) o x64 (64 bits) del programa, y después póngase en contacto con el editor del software."

In english is something like "This version of ZXPSignCmd.exe is not compatible with the Win version you are using. Blah blah blah..."

I'm 100% sure I've downloaded (twice) the 64bits version. I tried also with the 32bits exe but obviously the error message is the same.

**Comment by fgregor** [comment]
Hi ADukal,

I've just tried this on Windows 7 x64 and I do not see any error (both the 32 and 64 bit builds of ZXPSignCmd work successfully). Which browser did you use to download the files?

Do you have the Creative Cloud desktop application installed on your computer? Sometimes the Microsoft VC Runtimes are not installed by default with Windows (this might be the cause of your error message), and one way to make sure they are installed is by installing Adobe software.

Regards,
Fraser

**Comment by ADukal** [comment]
Sorry about the delay.
Downloaded with Chrome, Creative Cloud is up to date and Microsoft VC Runtimes are fine.
Not sure what happened but actually it is working as expected.

Thanks.

**Comment by fgregor** [comment]
Great, thanks for confirming.

**Comment by ADukal** [comment]
Well, the same trouble is back!
ZXPSignCmd worked fine for a couple of days but today I'm having exactly the same error message.
I'm using the same machine with Win 7 64bits, the ZXPSignCmd.exe was downloaded with Chrome (I also tryied with Firefox but nothing changed), I'm the only user / admin, executing the file as admin, but can't make it work.
The only thing that changed here is that I updated Windows a couple of days ago and -just in case- I installed the latest Microsoft VC Runtime today after the error appeared.
I've also Rebooted Win a couple of times but the problem remains.
So... the only solution I found is to use ZXPSignCmd launching OSX in a virtualbox.

**Comment by fgregor** [comment]
I'm not sure what would be causing this. Can you follow these steps and let me know if either option was checked?

 1.  Right-click on ZXPSignCmd.exe, click Properties
 2.  Click on the Compatibility tab and uncheck the following options if they are checked:
‘Run this program in compatibility mode’ 
‘Run this program as an administrator’

I wonder if the response from Microsoft on this thread might help? http://answers.microsoft.com/en-us/windows/forum/windows_7-performance/the-version-of-this-file-is-not-compatible-with/b619fa31-bbbb-465c-9663-b76153e30496

**Comment by ADukal** [comment]
That was the first thing I've tried and did not help.
Activating and deactivating ‘Run this program in compatibility mode’ and ‘Run this program as an administrator’, rebooting, downloading ZXPSignCmd.exe many times with Chrome and Firefox, etc.
Updated to Windows 10 this weekend and the problem persists.
My machine is working really fine so I'm going to keep using the ZXPSignCmd with OSX in a VirtualMachine.
Later this week I'll try to use the ZXPSignCmd.exe in my notebook to see if it works as expected. Also, I'll pay a view to that Microsoft forum.

Thanks.

**Comment by ADukal** [comment]
Infortunately, I tried in my Notebook (Win 7 64 bits) this morning with the very same result:

> "The version of this file is not compatible with the version of Windows you're running. 
> Check you computer system infromation to see whether you need an x86 (32-bit) 
> or x64 (64-bit) version of the program, and then contact the software publisher."

My CreativeCloud is up to date, the same with Windows 10, same with my browsers, just in case I redownloaded the file deactivating my antivirus, but there's no luck, and I don't know if there's another thing to take care of...

**Comment by ADukal** [comment]
ISSUE SOLVED
After my last post I downloaded the full CEP-Resources folder as a ZIP and... surprise! 
The ZXPSignCmd.exe worked fine!

**Comment by fgregor** [comment]
How strange! I was just in the process of setting up a virtual machine to test this, but good to know what solved the problem for you. We will review the way that this file is published to hopefully avoid this issue in future. Thanks for your perseverance!
