### ISSUE TITLE
CEP 8 and extension manifest - Illustrator CC2018

### ISSUE THREAD

**Issue by totorototo** [Adobe-CEP/CEP-Resources#180]
Hi,
I'm trying to migrate an Illustrator extension from CEP 7 to CEP 8.
CSInterace file, included in my project, has been modified (the same way I did for each migration).
ExtensionManifest file has been updater as well. (revision and runtime properties have been set to 8).

Unfortunately, when I try to launch my extension, a empty extension is shown.
After digging in some log files, here is what I have foundin CEP8-ILST.log: 
ExtensionManifest is not valid (CSXS runtime or ExtensionManifest version invalid).

Should I still set those properties to 7 even if I'm running CEP8?

After checking this file: 
> https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/ExtensionManifest_v_7_0.xsd

it seems to be the case. 

Any help would be appreciated! 
Thanks,
Thomas.

**Comment by akibnavidkhan** [comment]
Hi,
We have fixed this problem and fix should be available in next Illustrator update. For now, you can use revision property 7.

**Comment by totorototo** [comment]
Many thanks for your prompt reply. 
I will do what you told me while waiting for that fix. 

Until that fix, it won't be possible to use / get all new features / fixes provided by CEP 8 ? (just to be sure).

Have you a tiny idea about Illustrator update release date? few weeks, several months? 

Thanks,
Thomas.

**Comment by akibnavidkhan** [comment]
You can still use all the new features/ fixes provided by CEP 8 with revision property 7. Unfortunately, I don't have any idea about Illustrator update release date.

**Comment by akibnavidkhan** [comment]
I am closing the issue, please reopen if you are facing any problem with revision property 7.
