### ISSUE TITLE
Archive of ZXPs

### ISSUE THREAD

**Issue by alexwidener** [Adobe-CEP/CEP-Resources#19]
If there are going to be old versions of the CEP in the repository (4,5,6), there should also be archived versions of the ZXP that are compliant with CC, CC2014, CC2015. 

The ZXP that is currently in the archive doesn't confirm whether it's backwards compatible, nor how far back in OSX it works.

**Comment by fgregor** [comment]
Hi alexwidener,

The current version of ZXPSignCmd is backward compatible and can be used with applications as far back as CC. The ZXP format has not changed - new builds of ZXPSignCmd are generally for fixing bugs and making usability improvements, so you should be fine to stick with the latest one.

Best,
Fraser
