### ISSUE TITLE
ZXPSignCmd.exe window immediately closes

### ISSUE THREAD

**Issue by Inventsable** [Adobe-CEP/CEP-Resources#197]
I'm on Windows: 8.1 64bit, and sorry if this is a dumb question but I don't see any documentation on ZXPSignCmd so I'm not sure what to expect. I'm trying to follow the new [Package / Distribute Guide](https://github.com/Adobe-CEP/Getting-Started-guides/tree/master/Package%20Distribute%20Install) and downloaded the executable but the result of trying to run it is to close immediately:

![closing immediately](https://thumbs.gfycat.com/DeliciousWindyHammerheadshark-size_restricted.gif)

My first thought was that maybe this isn't supposed to be it's own window or CLI and I'm now supposed to run `ZXPSignCmd` and trailing options from the terminal, but in trying I get a `ZXPSignCmd: command not found`. I've tried all three 64x versions in the repo, running them as Admin, using OS diagnostic tools, and making sure it wasn't an Anti-Virus issue on my end. Am I using this incorrectly?

**Comment by Inventsable** [comment]
Thanks! Just for posterity, I get the same results when running it with the typical `start` command from GitBash. I'm not sure if this is because of using GitBash or because I simply don't know what I'm doing over here, but results on my end are:

!(Demo)[https://thumbs.gfycat.com/SimplisticSeparateBeardedcollie-size_restricted.gif]

- `start ZXPSignCmd.exe` gives the same result as trying to open from Windows Explorer
- `ZXPSignCmd.exe` isn't recognized
- `./ZXPSignCmd.exe` **_does_** work

I think this is pretty confusing because the Installation and Distribution guide completely glosses over installation of ZXPSignCmd and there isn't any kind of simple readme in the repo as a barebones example of what to expect. Is this supposed to be it's own window and CLI, or is this a CLI command? Where am I supposed to use this? and etc. Thanks for the answer though! I don't know if I'm supposed to close this now or it's courtesy to let the contributors of the repo do that.

**Comment by schroef** [comment]
How do i run this on windows 11. I get this poup from powershell and command prompt tells me its  is not recognized as an internal or external command
