### ISSUE TITLE
remote debugging: local server won't start

### ISSUE THREAD

**Issue by Jean-Zombie** [Adobe-CEP/CEP-Resources#200]
I am desperately trying to get the remote debugging working (CEP 8). I did everything described in the cookbook:
- create a `.debug` file in the root of my extension
- make sure the extension ID matches the one in `manifest.xml`
- try a lot of ports, i.e. "8080" or "2222" or "9090"
- make change to my plist file `defaults write com.adobe.CSXS.8 PlayerDebugMode 1` and restart the computer

now, when I open `localhost:8080`on chrome, safari or firefox I get a connection error. My localhost is fine though. When I fire up a jupyter server, for example, all is good.

I even tried the `cefclient` from this repo to access localhost. No luck either.

Is there another way to start the debugging server or even to "debug" the process of starting it?

**Edit**
I am on Mac OS (High Sierra).

**Comment by Jean-Zombie** [comment]
Extension ID. I don't even have a panel ID. Like this:

manifest.xml:
```
<?xml version='1.0' encoding='UTF-8'?>
<ExtensionManifest ExtensionBundleId="com.my.extension" ExtensionBundleVersion="1.0.0" Version="7.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ExtensionList>
    <Extension Id="com.my.extension.panel"/>
  </ExtensionList>
  <ExecutionEnvironment>
    <HostList>
      <Host Name="IDSN" Version="13" />
    </HostList>
<!-- Code goes on -->
```

.debug
```
<?xml version="1.0" encoding="UTF-8"?>
<ExtensionList>
    <Extension Id="com.my.extension.panel"/>
        <HostList>
            <Host Name="IDSN" Port="8080"/>
        </HostList>
    </Extension>
</ExtensionList>
```

**Comment by noehuerta** [comment]
Did you change your .plist file to accept logging?

**Comment by Jean-Zombie** [comment]
@jardicc 
tried 'em all. nearly all between "between 1024 and 65535 (not include 65535)" ;-)

@noehuerta 
right, yes using this cmd `defaults write com.adobe.CSXS.8 PlayerDebugMode 1`, didn't mention  it in my initial comment. (will edit it)

it's so weird. Don't know what else it could be :-(

**Comment by noehuerta** [comment]
When you change the plist you have to either restart the process with terminal command or restart your computer to see it work

**Comment by Jean-Zombie** [comment]
@noehuerta 
I did. No luck. 

I even just tried another thing. I changed the plist file for CSXS 7 too, since my manifest declares version 7 – I read about this on Davide Barrancas blog. But the additional plist doesn't do the trick either.

**Comment by noehuerta** [comment]
Which software is this for? I was able to get it up and running for AI & PS in the past. I think AE did need 'debug' file but I'm not 100.

**Comment by bbb999** [comment]
Any CEP host requires the presence of a .debug file.

Jean-Zombie, can you debug ANY panels, other than your own?

**Comment by Jean-Zombie** [comment]
InDesign CC 2018. I referenced it like this `<Host Name="IDSN" Version="13" />` in the manifest.

**Comment by Jean-Zombie** [comment]
@bbb999 
I just gave it a try and added a .debug file for one of the sample panels from this repo, i.e. "CEP HTML TEST Panel1". 

I also tried using Photoshop as a host this time, since the sample panels are suited for it. Nada.

Is the `.debug` file indeed the only way to fire up the debugging server? No command line tool or such?

**Comment by jardicc** [comment]
There is command line parameter but I think it is different use case: https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/Documentation/CEP%208.0%20HTML%20Extension%20Cookbook.md#customize-cef-command-line-parameters

**Comment by Jean-Zombie** [comment]
Guys. Much appreciated! I am on the run right now. Gonna check another machine later on. And also the command line option...

**Comment by schroef** [comment]
There seem to be this issue with Chrome, but also in Safari. Something about PolyFill or so, i hardly know anything about CEP panels. But I'm working on some panel and trying to improve it. I wanted to test it, but get this error.

Found a thread here on [Adobe Community](https://community.adobe.com/t5/get-started/adobe-extension-debuger-problem/m-p/11003012)

```
Uncaught TypeError: document.registerElement is not a function
    at Object.UI.registerCustomElement (inspector.js:2914)
    at inspector.js:2918
    at inspector.js:2921
```

**Comment by doriansmiley** [comment]
I'm seeing this error all of a sudden as well. Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by Inventsable** [comment]
Hello, this is due to changes in Chrome 80. We need to use the CEF Client program provided at this repo, see here:

https://github.com/Adobe-CEP/CEP-Resources/issues/272#issuecomment-584207829

**Comment by lvtute** [comment]
> is matching extension ID or panel ID?

thank you, you save my work, thank you sir

**Comment by mbpkk** [comment]
This may be too simple to mention, but having struggling to connect using https://localhost:<port#> for the last hour, I just tried using https://127.0.0.1:<port#> instead and finally go into the CEF debug console.

**Comment by schroef** [comment]
Kinda weird, im bumping into this .debug file issue again. I got the other running just fine. Ive a second panel, its setup is exact same. However when i try to debug that panel it refuses to make connection. I tried same number as the other panel, doesnt matter because if its closed you can use any number.  Even copied over that working index from the other panel still nothing. all names match 100%

**Comment by schroef** [comment]
> https://127.0.0.1:

I had exact same issue, took me many hours. Eventually got back home and tried Windows, bam, exact same issue. Different CEF versions and different OS's. Weirderst thing is other panel works just fine. went ovr all names and id's all 100% the same. Then suddenly it started working?!?

On osx i never seem to be able to user the browser for this on Windows this does seem to work.

**Comment by GammelSami** [comment]
Same issue. Then I used the xml of [this guide ](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#remote-debugging)instead of [the old guide ](https://github.com/Adobe-CEP/Getting-Started-guides/tree/master/Client-side%20Debugging)who is referenced everywhere.

This fixed it for me. (But only works in Google Chrome.)
