### ISSUE TITLE
IMSInterface.js is missing

### ISSUE THREAD

**Issue by nighantom** [Adobe-CEP/CEP-Resources#204]
Hi,

According to https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/Documentation/CEP%208.0%20HTML%20Extension%20Cookbook.md#cep-javascript-libraries, the IMSInterface.js file should be available at https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_8.x. But actually it's not there.

My question is where I can find IMSInterface.js?

Thanks

**Comment by sujaisivanandan** [comment]
This is no longer supported. Will update the documentation
