### ISSUE TITLE
Sample CEP 9 panel not working in Indesign 2019

### ISSUE THREAD

**Issue by snalld** [Adobe-CEP/CEP-Resources#214]
I'm trying to open the sample extension in Indesign 2019 on macOS High Sierra and the panel opens but displays no content.

I've also tried to open a panel I'm working on, that was working in Indesign 2018, and the same thing happens…

Thoughts?

![screen shot 2018-10-18 at 9 24 12 am](https://user-images.githubusercontent.com/11532073/47119697-9d050480-d2b7-11e8-82a8-dadda2bfd63a.png)

**Comment by undavide** [comment]
New CEP versions require a new activation of the debug flag for development panels – might that be? Just guessing.

**Comment by snalld** [comment]
Oh yep that was it. Didn't realise you had to enable debugging for unsigned extensions per CEP version. 

Thanks @undavide!
