### ISSUE TITLE
Adobe illstrator export problem

### ISSUE THREAD

**Issue by DS0818** [Adobe-CEP/CEP-Resources#228]
hello,
Adobe illstrator does not export API from multiple sketchpads. When can this API be added?
This API is of great use to us.
thanks!

**Comment by DS0818** [comment]
Export  multiple artboard to JPEG
I used it on indesign, but I couldn't find it on illstrator.

**Comment by ErinFinnegan** [comment]
Hi @DS0818 ! By "sketchpad" do you mean "artboard"?

**Comment by Inventsable** [comment]
Hello @DS0818, this is done in the [Export options](https://y-designs.com/tutorials/export-multiple-artboards-using-illustrator/).

**Comment by ErinFinnegan** [comment]
Thanks @Inventsable ... but isn't @DS0818 asking how to do this via the API? Or perhaps the Ai SDK?

**Comment by Inventsable** [comment]
If so I don't see how that's a CEP issue. The scripting API allows you to
define the active art board and easily export it -- exporting all is just a
matter of doing that while looping through
app.activeDocument.artboards.length.
