### ISSUE TITLE
CEP panel min width 136px

### ISSUE THREAD

**Issue by WagnerJakob** [Adobe-CEP/CEP-Resources#234]
Hi

I'm making a CEP panel for After Effects. I'm using responsive html to organize the few buttons the interface have.

Problem is, it seems a CEP panel can never become less than 136 px wide. The panel can be narrower, but the html inside will be stuck on 136 px. Is there a way to override that? I have tried the MinSize in the manifest, but that didn't do anything.

Thanks,
Jakob

**Comment by Inventsable** [comment]
I've confirmed this as well from trying to port a panel as a slim, vertical toolbar in both Illustrator and AE. Never found a solution myself, but realistically After Effects panels aren't meant to be so thin while docked so I changed my design to accomodate.

**Comment by bbb999** [comment]
Not today (or in our forthcoming release). 

What's the use case, for very thin panels?

**Comment by WagnerJakob** [comment]
Inventsable > OK. Thanks for replying. Then I wont use more time trying. :)

bbb999 > My panel is seven small buttons. Default is a horizontal line of buttons, but if you scale the window they will be a vertical line instead. Like photoshop left toolbar. Just nice to have for the user.

I found a workaround that works for me. But thanks both of you!

**Comment by prernavij** [comment]
Can we close this issue?

**Comment by WagnerJakob** [comment]
> Can we close this issue?

Yes. :)
