### ISSUE TITLE
Debug Bug with the CEP function saveAs() from Premiere Pro

### ISSUE THREAD

**Issue by SufyanKerboua** [Adobe-CEP/CEP-Resources#236]
When I use this function to save a new copy of my project, the new copy is well saved to the directory of destination. And the new project is well open meanwhile the previous project is closed.

However, when I use the autosave functionality with the new instance of my project.

I got an error

Here is a sample of code how bug with the Autosave functionality.

[Bug saveAS function - code.zip](https://github.com/Adobe-CEP/CEP-Resources/files/3098576/Bug.saveAS.function.-.code.zip)

**Comment by bbb999** [comment]
That's correct behavior. Autosave != SaveAs.

If you'd like, you can save the original project's path, and re-open it after your SaveAs.

**Comment by SufyanKerboua** [comment]
Thanks to the quick answer.

My goal is to write a script for Adobe Premiere Pro, who allows users to save their works thanks to that script, and let's them use the Autosave functionnality. 
However when I use both of these functionality I got this error : 

![Capture d’écran (4)](https://user-images.githubusercontent.com/44617517/56569722-d47fa100-65b9-11e9-9f77-fff268760ca5.png)

**Comment by bbb999** [comment]
Code snippet, please? [send direct if you like; bbb@adobe.com)

**Comment by SufyanKerboua** [comment]
Ok thanks, I just send you a mail with a snippet of code, to use with Adobe ExtendScript Tool Kit

**Comment by bbb999** [comment]
I'm pretty sure the problem is separators. 

This can't work: var outputPath = "C:/Users/profile/Desktop/test/tmp/";

This works: var outputPath = "C:\\Users\\profile\\Desktop\\test\\tmp\\";

PProPanel uses a getSep() function, to obtain a platform-specific path delimiter. 

https://github.com/Adobe-CEP/Samples/blob/27edf5546e1b50602e063f0186d7669b60d91e27/PProPanel/jsx/PPRO/Premiere.jsx#L715

**Comment by SufyanKerboua** [comment]
I just try right now and it was that, thanks a lot

**Comment by bbb999** [comment]
Great, thanks for letting us know!
