### ISSUE TITLE
ZXP signing success, but installing failed with "no valid cert"

### ISSUE THREAD

**Issue by zhiqiang-li** [Adobe-CEP/CEP-Resources#239]
Hey guys, 
I was trying to sign a finished After  Effects extension. 
Following the [document recommended by this repo](http://wwwimages.adobe.com/www.adobe.com/content/dam/acom/en/devnet/creativesuite/pdfs/SigningTechNote_CC.pdf),
I was able to create a signed zxp package successfully, but when try to install the package using [ZXPInstaller](https://zxpinstaller.com/), I always get the same error "no valid signed certificate", and the installation fail. 
If I do a validation on my zxp package using ZXPSignCmd, it outputs following messages:
```
CN:'SeeShionTech'
OU:
DN: /C=CN/ST=HangZhou/O='SeeShionTech'/CN='SeeShionTech'
OS Trused=false
Timestamp:None
Sigining Certificate:Valid (form 2019-06-14 unti 2030-08-31)
``` 
I'm using Windows 10, has you guys encountered such problem?

**Comment by NTProductions** [comment]
Are you using your own generated certificate? Also what is your code for packaging the ZXP?

**Comment by zhiqiang-li** [comment]
Hi @NTProductions 
I was uing my own generated certificate, here's the cmd I use to generate the certificate"
`ZXPSignCmd.exe -selfSignedCert CN HangZhou SeeShionTech SeeShionTech ****** cert.p12`

and here's the cmd I use to sign the package:
`ZXPSignCmd.exe -sign ExtFolder ExtResult.zxp cert.p12 ******`

I also tried to add `-tsa` option when signing the package, no luck either.
Also, maybe I should mention that I have some exe binary files in my extension package, not sure whether it matter.

**Comment by tomzag** [comment]
You must use timestamping. You can use the server http://timestamp.digicert.com/

`ZXPSignCmd.exe -sign ExtFolder ExtResult.zxp cert.p12 ****** -tsa http://timestamp.digicert.com/`

**Comment by zhiqiang-li** [comment]
Hi @tomzag 
I tried to add timestamp option, and the verification outputs following:
```
*********** Certificate Information ***********
CN: 'SeeShionTech'
OU:
DN: /C=CN/ST=HangZhou/O='SeeShionTech'/CN='SeeShionTech'
OS Trusted: false
Revoked: false
Timestamp: Valid and within certificate validity dates at time of signing
Signing Certificate: Valid (from 2019-06-14 until 2030-08-31)
***********************************************
Signature verified successfully
```
But sadly, the installation still fail with the same error

**Comment by tomzag** [comment]
Hm, I got the same error also a few times. For me, it worked if I repeated the signing process again (probably something on the previous signing process went wrong).
As an alternative to ZXPInstaller you can also use http://install.anastasiy.com/

**Comment by zhiqiang-li** [comment]
Thanks @tomzag I'll try the new installer and let you know the result

**Comment by zhiqiang-li** [comment]
@NTProductions @tomzag hi, here to resport my testing result. I found out that the reason I keep getting "invalid certificate" error is I have ffmpeg binary files in my extension package. If I remove them, I can install my signed package successfully. So, I think the new question is, how do I sign a package with some executable binary files inside.

**Comment by NTProductions** [comment]
I know that when you sign files, you should not change or move them in anyway, otherwise it will cause the extension to fail. 

Not sure if it applies in your case with your binary files, but if possible, you could try having them deployed in a public directory (like ~/Documents). If they are moved here on you should be able to modify them and still have everything work.

**Comment by zhiqiang-li** [comment]
@NTProductions Yes, that's exactly what I'm doing right now, Thanks for your suggestion
