### ISSUE TITLE
Check in .zxp files for example extension.

### ISSUE THREAD

**Issue by jenstroeger** [Adobe-CEP/CEP-Resources#242]
To just try out an example extension, I have to clone the entire repo and build one of the [Sample](https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_9.x/Samples) extension myself. I think it would make much sense to build and check in the `.zxp` files just so people can quickly try them without cloning everything?

**Comment by ErinFinnegan** [comment]
This is a good point! I'll pass it along to @prernavij !

**Comment by sujaisivanandan** [comment]
The idea of this repo is to help with development and therefore the samples provided here are non-obfursated and non-compressed. other ZXP content is available online - https://helpx.adobe.com/in/creative-cloud/kb/installingextensionsandaddons.html
