### ISSUE TITLE
Read Stream doesn't emit "end" event

### ISSUE THREAD

**Issue by wahab054** [Adobe-CEP/CEP-Resources#243]
**Method reference:**

>  fs.createReadStream()

**Issue faced**: Same code running in NodeJS emits "end" event when stream finishes, but does not emit this event when running within CEP.

**Code Reference:**
```
let toSendData = [];
let fileStream = fs.createReadStream(path);
function sendData() {
  console.log("Time to Send File");
}
fileStream.on("end", sendData);
fileStream.on("data", data => {
    console.log("Append Data");
    toSendData += data;
});
```

**Comment by ErinFinnegan** [comment]
Hi @wahab054 ,

Sorry about the delay, I was hoping someone else might answer your question. Are you still facing this issue?

Which [version of CEP](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_9.x/Documentation/CEP%209.0%20HTML%20Extension%20Cookbook.md#applications-integrated-with-cep) are you trying this in? And which products are you testing with?

ExtendScript is based on an old version of JavaScript, so it won't behave the same was as it would in NodeJS.  CEP is tied to [specific instances of CEF](https://forums.adobe.com/message/11225088#11225088) (that chart also shows Node compatibility), and sometimes newer versions of CEF can cause issues.

**Comment by wahab054** [comment]
Thank you for responding. No, i'm not facing his issue anymore, figured out a work-around.
