### ISSUE TITLE
.debug file can't have a filename

### ISSUE THREAD

**Issue by undavide** [Adobe-CEP/CEP-Resources#25]
Hi,
in the cookbook is written that the file enabling remote debugging can have whatever name, with a mandatory ".debug" extension, like Test_Extension.debug.
In fact (at least on OSX) it seems that only ".debug" (a hidden file) works, while using any other name fails and results in Chrome not being able to find the page.
Thanks,

-Davide

**Comment by arthurwei1975** [comment]
The file name must be ".debug".

The wiki text was actually "... such as Test_Extension\.debug". GitHub wiki treated "\." as an escape character and showed it as "... such as Test_Extension.debug". This was misleading.

I just changed the text to "... such as Test_Extension\\.debug". Not it shows as "... such as Test_Extension\.debug".

Thanks

**Comment by undavide** [comment]
Thanks!
