### ISSUE TITLE
ExManCmd.exe /enable_logging log location

### ISSUE THREAD

**Issue by keir-lavelle** [Adobe-CEP/CEP-Resources#255]
More of a question than an issue really - I am setting logging to all using 

`ExManCmd.exe /enable_logging all`

and then attempting to install an extension that I know will fail with a status code of -403

`ExManCmd.exe /install 403_extension.zxp`

But can anyone tell me where the logs are written? When I try to install I can see a `tmp1234aaaaa` (that format but the 1234aaaaa change each time) file is created in the %temp% directory, but this just appears to have some XML configuration in there. There's nothing in PDApp.log that appears to be from the ExManCmd.exe call either

Thanks for your help

**Comment by ErinFinnegan** [comment]
Hi @keir-lavelle,

Windows: `C:\Users\<username>\AppData\Roaming\Adobe\Extension Manager CC\Log\`

Mac: `/Users/<username>/Library/Application Support/Adobe/Extension Manager CC/Log/`

People do ask that a lot, perhaps we need to put the answer more prominently into the documentation.

Let us know how that 403 error works out.

**Comment by keir-lavelle** [comment]
Found it, that's great thank you :)
