### ISSUE TITLE
cep.fs.showOpenDialog crashes panel on Photoshop CC2020 / macOS

### ISSUE THREAD

**Issue by anastasiuspernat** [Adobe-CEP/CEP-Resources#256]
Hi! I experience the problem with cep.fs.showOpenDialog on macOS 10.12. I haven't tried it on other versions of OSs but a couple of my users reported the same problem on different versions of macOS and Photoshop CC 2020.

cep.fs.showOpenDialog crashes and reloads current CEP panel after choosing any file. Are you aware of this problem? I can supply an example. Thank you!

**Comment by ErinFinnegan** [comment]
Hi Anastasiy!

Even as of Photoshop 2019 (v.21) macOS 10.12 wasn't supported: https://helpx.adobe.com/photoshop/system-requirements.html (I know that's not the 2020 page...)

I can ask the CEP team anyway, but I suspect it's unlikely to get traction.

**Comment by ErinFinnegan** [comment]
The CEP team wrote back very quickly! Apparently this is being fixed, and is tracked in the following bugs (for internal reference):

CEP-1773
CEP-1775
CEP-1727

**Comment by anastasiuspernat** [comment]
Thank you very much! Great! 

P.S. And yeah sorry, my bad. I meant macOS Mojave 10.14.
(Photoshop 2020 doesn't even start on 10.12).

**Comment by ErinFinnegan** [comment]
Apparently it's happening across OS versions anyway... 😅

**Comment by Trevor-** [comment]
Just for the record and to follow this thread on Windows it seems to still work

**Comment by jardicc** [comment]
I can confirm same bug. Mojave + PS 2020 (21.0.1)
I use it for a folder opening.

**Comment by jamesey2001** [comment]
I am experiencing the same issue with InDesign 15.0.1, on Mojave 10.14.6, is this issue across the board in CEP for 2020?

**Comment by ErinFinnegan** [comment]
So the good news is these bugs have been fixed in CEP 9.4.0.122, the less good news is that I'm not sure when that build of CEP will be included in each product yet. Hopefully @prernavij can let use know...

**Comment by jamesey2001** [comment]
Just use `showOpenDialogEx()` with the same parameters and you should be good to go.

**Comment by ErinFinnegan** [comment]
Just to give a quick update, the CEP hotfix for this issue is expected to be picked up in Photoshop, Illustrator, Premiere Pro, and (possibly?) After Effects by the end of the month, or in early February.

**Comment by Trevor-** [comment]
And not InDesign?

**Comment by ErinFinnegan** [comment]
@Trevor- The engineering team didn't specifically mention InDesign, and this is not a "required" hotfix to be picked up by product teams. When I hear something more I'll let you know.

**Comment by sujaisivanandan** [comment]
this is now available in all apps
