### ISSUE TITLE
Setting sequence marker end time does nothing (premiere pro)

### ISSUE THREAD

**Issue by maca134** [Adobe-CEP/CEP-Resources#262]
As title says, when trying to set a sequence marker end time simple does nothing.

Im using sample code here https://github.com/Adobe-CEP/Samples/blob/master/PProPanel/jsx/PPRO/Premiere.jsx#L294-L297

Adobe Premiere Pro 2019 (CEP 9)

Not sure what else i can provide.

**Comment by bbb999** [comment]
Fixed! It should have been setting marker.end to [new value], not marker.end.seconds.
