### ISSUE TITLE
[Photoshop] Functions in secondary, correctly parsed JSX fail to execute

### ISSUE THREAD

**Issue by undavide** [Adobe-CEP/CEP-Resources#27]
Hi,
the following applies to Photoshop only (any version from CC onwards), OSX.
Please find the demo extension here: https://dl.dropboxusercontent.com/u/23243188/Adobe/com.example.evalJSX.zip

Alongside my _main_ jsx file (let's call it JSX1) I have a secondary jsx (let's call it JSX2): it contains an alert to warn you when it's evaluated, plus a function:

```
// in the JSX2
alert("anotherFile.jsx has been evaluating");
var secondJSXFunction = function() {
     alert("Hello world from anotherFile.jsx");
}
```

JSX1 in turn contains the code to evaluate on the fly JSX2, using the absolute path the panel passes it:

```
// in the JSX1
function evalFile(path) {
    try {
        $.evalFile(path);
    } catch (e) {
        alert("Exception:" + e);
    }
}
```

The Panel, apparently, correctly parses the JSX2, since the alert `"anotherFile.jsx has been evaluating"` pops up. Yet, the `secondJSXFunction` is not available, and fails to execute when called from the main JS via `evalScript()`. 

As a result, it's currently impossible to modularize the JSX in multiple files, since any function there fails to execute.
Thank you,

Davide Barranca

**Comment by undavide** [comment]
Hi,
I've been able to considerably narrow the issue.
The function in the secondary JSX fails if you write it this way:

    var secondJSXFunction = function() {
        alert("Hello world from anotherFile.jsx");
    }

And fails if you write it this way too:

    function secondJSXFunction() {
        alert("Hello world from anotherFile.jsx");
    }

But works if you omit the "var"

    secondJSXFunction = function() {
        alert("Hello world from anotherFile.jsx");
    }

Is this as designed? Thank you!
-Davide

**Comment by MaxJohnson** [comment]
Additionally, using the #include in the main .jsx of a panel causes a script error every time, but ou can have the #include in a secondary .jsx file called from the main via evalFile() and it will work. I don't know if the same rules apply as are described by @undavide

**Comment by undavide** [comment]
Gee, what an entangled topic...

**Comment by indiscripts** [comment]
Hi Davide,

Did you test, in JSX2, whether **this===$.global** is true?

**Comment by derrickb** [comment]
Old topic, but I thought it might be helpful for @undavide and others to see how I structure my JSX so everything is accessible.

My JSX consists of about 4 files, each responsible for different functionality of my extension.  I execute them all on startup using a looped function like the one Davide shows on his blog.

In my main JSX, I have my primary host functionality, the functions that my HTML panel call to.  It may call a "util" object like this:
```
$._ext = {  
    someFunc: function () { util.helper(); }  
}
```

I have another JSX file which contains my "utility namespace".  It uses **$.global** to make itself usable in the global scope to all JSX files.  For example:
```
$.global.util = {  
    helper: function () { alert("I'm helping!"); }
}
```

As others have states, I found #include to be too unwieldy when used in the Photoshop environment (not sure about other host apps) so I don't use it.

**Comment by undavide** [comment]
Keeping up with this old topic, since the behaviour is still bugged...
@indiscripts: yes, `this === $.global`.
@derrickb: in fact if you keep the secondary JSX namespaced, it works

For some reason, only global variables are correctly parsed, like:

```
secondJSXFunction = function() {
    alert("Hello world from anotherFile.jsx");
}
```

where `secondJSXFunction` is a global var. Functions... they don't stick. I still wonder where the trick is...

**Comment by undavide** [comment]
I comment after so long to keep this issue open.
FYI, I can confirm that @MaxJohnson suggestion works (`#include` in a secondary file), yet if you don't namespace each and every function in any extra file that is loaded at runtime, they **won't work**.

To sum up, in a secondary `jsx` file:

```
var fun = function () { /* will NOT work */ };
function fun() {        /* will NOT work */ };
fun = function () {     /* works */ };
var fun = {
    fun: function() {   /* works */ }
};
```

**Comment by derrickb** [comment]
What it seems like to me is that JSX files are not actually in the global scope, but are wrapped in a closure that we don't know about and can't see.

This would be consistent with your findings that defining a function as `var fun = function()` doesn't work, but `fun = function()` does.

In regular browser environments, even in a nested scope (say, a function in a function in an object that is in another object, etc...) if you omit the "var" then it is defined globally.  The same is happening here.  See "Automatically Global" section here: https://www.w3schools.com/js/js_scope.asp

Now, why `var fun = { ... }` works I have no idea as I would expect the "fun" object to not be defined globally as well.

**Comment by ofx360** [comment]
Seems like "#include" works in JSX

So something like: 
#include "~/AppData/Roaming/Adobe/CEP/extensions/CEP_HTML_Test_Extension-8.0/jsx/util.jsx"

Seems to support all the function types you listed as well

**Comment by speedgeil** [comment]
`#include "~/AppData/Roaming/Adobe/CEP/extensions/CEP_HTML_Test_Extension-8.0/jsx/util.jsx"`

Works for me as well. But what if another User is on MacOS? Could we pass the system root as a variable from js to jsx to make it work on both Os?
Something like #include "pathToExtension" ?
