### ISSUE TITLE
ETSK wont start on OSX 10.11.6

### ISSUE THREAD

**Issue by schroef** [Adobe-CEP/CEP-Resources#270]
I got this the AdobeExtendScriptToolkit_4_LS22 installed on 2 machines running 10.11.6. On machine A it works just fine, on machine B, it shows app tile in the file menu for a split second and seems to crash. I dont get any crash window though.

EDIT
i had visual studio open and also acrobat. Closing both now does show the ESTK.
After it showed, it seems to run just fine even when those 2 apps are open again. Tried finding logs for any help. But couldnt find any, but dont know exactly where to look. I tried the console but could not find ESTK related log

**Comment by undavide** [comment]
VSCode with the official ExtendScript plugin won't allow ESTK to run, see the [Notes section here](https://marketplace.visualstudio.com/items?itemName=Adobe.extendscript-debug). I assume that if you start ESTK first, VSCode plugin won't run either...

**Comment by sujaisivanandan** [comment]
Known issue : we can either run estk or vscode extendscript debug plugin at a time.
