### ISSUE TITLE
[Question] Format and codec of exported sequence. Adobe Premiere Pro v14

### ISSUE THREAD

**Issue by artem-kazaryan-es** [Adobe-CEP/CEP-Resources#277]
I want export sequence via my plugin and give for the user an ability to choose format and codec.
As I can see there is an ability to accomplish it via `exportAsMediaDirect` but it requires predefined .epr preset path. BTW I don't see in the signature of this function an ability to specify a format.
Is there a way to get all available formats and codecs from SDK and then export sequence based on them? Or at least generate .epr file on a fly depending on chosen format and codec (as I see all SDK depends on .epr preset file)

**Comment by bbb999** [comment]
An output preset (.epr file) already specifies a format. 

If you don't want to constrain the user's choices to (for example) a list of available .epr files, why perform the export through your extension, at all? The user could just use PPro's Export functionality, right?

**Comment by sujaisivanandan** [comment]
closing this since there is not further response on this thread. Assuming this is resolved.
