### ISSUE TITLE
Panel is empty on AI 2020

### ISSUE THREAD

**Issue by net5566** [Adobe-CEP/CEP-Resources#286]
I'm trying to run CEP 9 extension on AI 2020. (Mac OS 10.14.6)

I download the sample (CEP_HTML_Test_Extension-9.0) and move the folders to `/Library/Application\ Support/Adobe/CEP/extensions/`

Then there are 4 items shown on the extension list 
CEP HTML Test Modal Dialog
CEP HTML Test Modeless Dialog
CEP HTML Test Panel 1
CEP HTML Test Panel 2

After I click on `CEP HTML Test Modal Dialog` or `CEP HTML Test Modeless Dialog`, there is nothing happened.
I can launch panels when I click on` CEP HTML Test Panel 1` or `CEP HTML Test Panel 2`, but the panels are all empty

**Comment by bbb999** [comment]
It sounds like you haven't enabled the loading of unsigned panels...?

**Comment by alialneyadi** [comment]
### good job

**Comment by net5566** [comment]
> It sounds like you haven't enabled the loading of unsigned panels...?

Yes, you are right

I enter `defaults write com.adobe.CSXS.8 PlayerDebugMode 1` yesterday
But I'm running CEP 9
It should be
````bash
defaults write com.adobe.CSXS.9 PlayerDebugMode 1
````
