### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by eseraygun** [Adobe-CEP/CEP-Resources#29]
The copyright notice in .js files mentions an "Adobe license agreement" accompanying the files, but there is no such file in the repo.

Would you be able to include a LICENSE file so that people can use these libraries in their products safely?

**Comment by arthurwei1975** [comment]
License files had been uploaded to https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_6.x

Thanks
