### ISSUE TITLE
Input type="range" doesn't work properly

### ISSUE THREAD

**Issue by dmitryrazinkov** [Adobe-CEP/CEP-Resources#291]
It's impossible to use "\<input type="range">". I can just guess that some .preventDefault is called internally.
Screen record link: https://youtu.be/OwrKXEEoYRw
How it works in Chromium 61: https://youtu.be/pQQ5UKrxnkY

**Comment by sujaisivanandan** [comment]
Fixed in CEP v9.2.1.39
