### ISSUE TITLE
System exception: cannot lock named mutex (abadoned): ExmanProcessMutex

### ISSUE THREAD

**Issue by StefanRiedmann** [Adobe-CEP/CEP-Resources#298]
This is happening to me when running any exmancmd. I already uninstalled all Adobe applications, including Creative Cloud Desktop, and re-installed it. Still the same issue. 

Windows 10 Enterprise, version 10.0.17763

**Comment by ErinFinnegan** [comment]
Which version of ExManCmd are you running? And when does this happen? When using ExManCmd to sign or to install...?

**Comment by StefanRiedmann** [comment]
Hi Erin! 
I'm using the latest version from here
https://partners.adobe.com/exchangeprogram/creativecloud/support/exman-com-line-tool.html

And it already happens doing a simple /list all

**Comment by StefanRiedmann** [comment]
> Which version of ExManCmd are you running? And when does this happen? When using ExManCmd to sign or to install...?

@ErinFinnegan any updates on this? or any idea where to reach out..? I already posted in the community, without success so far... 
https://community.adobe.com/t5/exchange/exmancmd-not-working-anymore-mutex-error/m-p/11256135?page=1#M560

**Comment by ErinFinnegan** [comment]
I'm still asking around about this... 

Did this happen to you using previous versions of ExManCmd, or is this a new problem with 7.10? (If you're a new user of ExManCmd, it's understandable.)

Also, how might we reproduce this error internally?

**Comment by StefanRiedmann** [comment]
I think it's a very specific error that happened on my machine (windows on a mac, using Bootcamp). I'm using ExManCmd since years, and never happened to me before. Unfortunately, we couldn't reproduce it on any other machine.

**Comment by ErinFinnegan** [comment]
Hi!

If you're still having this issue, can you share your log files? Here's how to get them:

> To enable trace level EMCL logs , add below mentioned files- 
> 
> ExManCoreLibLog.YES (create empty file) at
> /Users/<username>/Library/Application Support/Adobe/Extension Manager CC/Log/ OR C:\Users\<username>\AppData\Roaming\Adobe\Extension Manager CC\Log\
> 
> asu.trace (create empty   file) at
> /Users/**/Library/Logs OR C:\Users**\AppData\Local\Temp
> 
> Try installing a plugin…
> 
> Share EMCL.log file at 
> /Users/<username>/Library/Application Support/Adobe/Extension Manager CC/Log/ OR C:\Users***\AppData\Local\Temp\CreativeCloud\ACC\ACC.log
> 
> Share ACC.log file at 
> /Users/**/Library/Logs/CreativeCloud/ACC/ACC.log  OR C:\Users**\AppData\Local\Temp\CreativeCloud\ACC\ACC.log
> 
> Share ExMan.db from
>  /Library/Application Support/Adobe/Extension Manager CC/Configuration/DB/ OR C:\ProgramData\Adobe\Extension Manager CC\Configuration\DB\

If you don't want to share them here, you can email them to me at finnegan (at) adobe.com.

I think one of my coworkers said he faced something like this, but it went away after he re-imaged the machine... but I recognize that is a very undesirable solution!

**Comment by StefanRiedmann** [comment]
Hi Erin! 
Thanks for this. Yes, to setup Windows from scratch would be a big effort. So perhaps you can find something with the files you asked for. The ACC.log is too big, and I can't add it here. Also, the ExtensionManagerCC application doesn't even start (the UI appears and crashes), so I gues that's why there is no .db file available. 
I'll send you the acc.log and emcl.log per mail. 

If nothing helps, I'll re-install Windows when I can. 

Best regards,
Stefan

**Comment by ErinFinnegan** [comment]
Thanks, Stefan!

A new ExManCmd release will come out in October at the very least, and might be [in prerelease](https://adobe.ly/ccdevpre) sooner.

ExtensionManagerCC has been deprecated for some time now. I know it's still possible to install and open it, but I'm not surprised if it doesn't open...

**Comment by StefanRiedmann** [comment]
Thanks for the update. 
Yes, I thought that ExtensionManagerCC is deprecated, but since you asked me for 
C:\ProgramData\Adobe\Extension Manager CC\Configuration\DB\ExMan.db
...I thought I should install it.

**Comment by ErinFinnegan** [comment]
Hi @StefanRiedmann,

ExManCmd was once part of the Extension Manager, and that just happens to be the path where the database file lives...

**Comment by StefanRiedmann** [comment]
After lots of mails and help from @ErinFinnegan and the team, we found the solution. Simply delete the folder

C:\ProgramData\Adobe\Extension Manager CC\
/Library/Application Support/Adobe/Extension Manager CC

I just tried it on Windows - because that's where I had the problem. Be aware that the 'ProgramData' folder is invisible by default. So you should make it visible in the explorer... 

![image](https://user-images.githubusercontent.com/20997981/90637647-a7212280-e202-11ea-8cb3-d2ecc2163975.png)

Thanks again for the help!
Stefan
