### ISSUE TITLE
JSON object as CSEvent payload

### ISSUE THREAD

**Issue by undavide** [Adobe-CEP/CEP-Resources#30]
Hi,
I've not properly understood the following paragraph, quoted from the CEP6 cookbook:

> Besides, like flash world, event.data could even be an object, i.e. you could use an object as event.data. **If you use a JSON object as event data**, there is a known issue that the data order will be messed up sometimes. A work around for this issue is using JSON.stringify() to convert this JSON object to a string first, and then add any prefix to this string like “Your JSON string”.

When it's said **If you use a JSON object as event data**, does that mean a regular Object, correct? I can't get why a JSON.stringify() isn't enough, and we're suggested to prefix it with some extra string. Is that the same as PhotoshopJSONCallback, which event.data received as a parameter in the callback is a JSON with a prepended "ver1," string?

Thank you,

-Davide

**Comment by arthurwei1975** [comment]
This had been fixed in the upcoming release of CEP and CC 2015.
