### ISSUE TITLE
Import files API does not work as expected

### ISSUE THREAD

**Issue by danpora** [Adobe-CEP/CEP-Resources#301]
I'm using CEP 9.0, working on PPro. 
When calling `app.project.importFiles(['my_video.mp4'], 1, <ProjectItem>, 0)` while _my_video.mp4_ 
is intentionally not located on my host, I have two issues:

1. I get a warning dialog (image below), while I passed true as a second argument (suppressed UI warnings).
2. importFiles returns true, means the import was successful although the file does not exists.

![image](https://user-images.githubusercontent.com/15452419/90010981-75abd280-dca9-11ea-9945-fa7fe7954b20.png)

**Comment by bbb999** [comment]
> my_video.mp4 is intentionally not located on my host...

Where is it? 

Adobe's video applications required that source media be available at one of the following: 

- Local path
- Mapped network drive (Win)
- Mounted network volume (Mac)
- UNC path

Media from IP addresses won't work.

**Comment by danpora** [comment]
@bbb999 Well, in my application users are fetching a list of paths (could be host or network paths) to videos. In most cases videos truly exists behind those paths, but there could be cases where no video is located behind a certain path, and I want to catch that case and prompt the user.

So I just tested _importFiles_ with a path that does not exist, to test how can I catch that scenario.

**Comment by bbb999** [comment]
>...there could be cases where no video is located behind a certain path, and I want to catch that case and prompt the user

I'd be tempted to use the ExtendScript File object to check those paths, before attempting import; specifically, the handy File.exists() method.

**Comment by AlohaFX** [comment]
hi @bbb999 , I also have an import problem.
I have code working correctly on all AE versions prior to 17.5.1.

This is the code
`var myTemplateToImport = "the local path from file"
newFootageItem = app.project.importFile (new ImportOptions (new File (myTemplateToImport)));`


Before the release of 17.5.1, this import happens instantly.
However, from 17.5.1 and 17.6 - The process takes almost 2 minutes.
Does anything new need to be included in the import method for versions that are not working properly?

Kindly

Rubens Nobre
