### ISSUE TITLE
fileTypes array in showOpenDialog is not considered.

### ISSUE THREAD

**Issue by meetgurudev** [Adobe-CEP/CEP-Resources#302]
Displays the platform-specific File Open dialog, allowing the user to select files or folders. Which has many parameters that can be used for launching file selection dialog.

There is also a param called : 
**fileTypes**  : Array of String The file extensions (without the dot) for the types of files that can be selected. 
For example: var fileTypes = ["ai","jpg","psd"];

However, this param is ignored when file selection dialog appears and list downs every file type.
also tried using showOpenDialogEx() // issue is still the same. fileTypes param is not filtering.

**Comment by bbb999** [comment]
Do you see the same behavior on Mac and Windows?

**Comment by meetgurudev** [comment]
Yes, this is an issue occuring both on Mac and Win

**Comment by sujaisivanandan** [comment]
You will need the dot “.” for specifying file types.
var fileTypes = [".zip",".pdf"];

**Comment by meetgurudev** [comment]
The documentation specifically says to remove the "." before the file type. Anyways will check and update you on this.

Thank you!

**Comment by meetgurudev** [comment]
fileTypes array param works for _showOpenDialogEx_ and not for _showOpenDialog_ (strange). Need not to specify dot in front of extension in the array. Example: let fileTypes = ["ai","psd"];
