### ISSUE TITLE
CEP Extensions not showing in menu if installed to system Library

### ISSUE THREAD

**Issue by notbyhalf** [Adobe-CEP/CEP-Resources#303]
macOS Mojave 10.14.6
After Effects 17.1.2

It's been like this for a little while and across versions of After Effects. I don't know what setting I have changed along the way, but After Effects only displays Extensions installed to **~/Library/Application Support/Adobe/CEP/extensions/** but not **/Library/Application Support/Adobe/CEP/extensions/**

Works as expected on another computer of mine. Any thoughts?

EDIT: I trashed the CEP folder in **/Library/Application Support/Adobe/** and re-installed an extension with ZXP Installer. All good now (and I've put up with this for ages).

**Comment by sujaisivanandan** [comment]
ok Closing this.
