### ISSUE TITLE
PPro - Create an empty ProjectItem

### ISSUE THREAD

**Issue by danpora** [Adobe-CEP/CEP-Resources#304]
Hey,

Is it possible to create an empty _ProjectItem_?

I'm using PPro scripting API and my use case is this:
I have a source video file which is not yet available on my host, but I still wish to treat it like it does exists but not yet linked.
Then I'd like to create an empty subclip from that not-linked project item and place it on my sequence.

In certain time in the future, I will have that video source file available and I expect to see the related project item get linked.

Is it possible?

**Comment by bbb999** [comment]
It's not possible to convince PPro to import completely non-existent media. However, you could import some placeholder media (of appropriate duration), then replace it later using `changeMediaPath()`.
