### ISSUE TITLE
Drag & Drop from Premiere to CEP Panel

### ISSUE THREAD

**Issue by micodeyt** [Adobe-CEP/CEP-Resources#306]
Hello !

Is there any way to drag an item from Project panel or Timeline panel into a CEP Panel ?
I'd like to access the properties of an item that would be dropped in my panel.
I know that the opposite way is possible using a `'com.adobe.cep.dnd.file.0'` property in `event.dataTransfer` but I found nothing for this case.

It seems `event.dataTransfer` is empty on 'drop' event in the CEP Panel.

**Comment by micodeyt** [comment]
Is that a feature that might be implemented ?

Else is there en equivalent of `onSourceClipSelectedInProjectPanel` for Timeline items ?

**Comment by micodeyt** [comment]
Or maybe a way to know which of Premiere panel is focused ? (with the blue outline)

**Comment by micodeyt** [comment]
> Is that a feature that might be implemented ?
> 
> Else is there en equivalent of `onSourceClipSelectedInProjectPanel` for Timeline items ?

And what about these ? :'(

**Comment by bbb999** [comment]
It's unlikely that we'll provide CEP API to query which PPro panel (which are not all CEP-based) is currently selected. 

If we did, would you do with that knowledge? 

> is there en equivalent of onSourceClipSelectedInProjectPanel for Timeline items ?

PProPanel shows how to register for onActiveSequenceSelectionChanged messages: https://github.com/Adobe-CEP/Samples/blob/f86975c3689e29df03e7d815c3bb874045b7f991/PProPanel/jsx/PPRO/Premiere.jsx#L2012

**Comment by micodeyt** [comment]
> If we did, would you do with that knowledge?
I was talking about a DnD from Premiere to a CEP Panel feature. As for the "focusedPanel" feature it would have allowed me to emulate a DnD : because focus doesn't change after a DnD between panels, I could just look which items are selected in the focused panel.

> PProPanel shows how to register for onActiveSequenceSelectionChanged messages: https://github.com/Adobe-CEP/Samples/blob/f86975c3689e29df03e7d815c3bb874045b7f991/PProPanel/jsx/PPRO/Premiere.jsx#L2012
Great ! Thanks a lot I missed it.
My third idea is to watch which of `onSourceClipSelectedInProjectPanel` and `onActiveSequenceSelectionChanged` happened last before the `drop` event.
If it's to hacky I'll stick to a more standard approach.

**Comment by micodeyt** [comment]
Closing, I ended up not using drag/drop but only a combination of `onSourceClipSelectedInProjectPanel` and `onActiveSequenceSelectionChanged`as mentioned above.
