### ISSUE TITLE
Extension not showing up in Photoshop for Window 10 for ExManCmd

### ISSUE THREAD

**Issue by AndrewMore1** [Adobe-CEP/CEP-Resources#307]
Currently running Photoshop v21.2.2 and 20.0.10 on Windows 10 with the latest version of the ExManCmd.  When running the extension in Photoshop it shows up correctly in the application window, and runs without error.  However, it's not shown in the list displayed by ExManCmd

When running the "exmancmd /list all" command I see this:

c:\git\AE_Patch\adobeextension>exmancmd /list all
1 extension installed for Illustrator 2019 (ver 23.1.0)
 Status                        Extension Name                         Version
=========  =======================================================  ==========
 Enabled    com.siemens.Teamcenter5                                        5.0

1 extension installed for Illustrator 2020 (ver 24.3.0)
 Status                        Extension Name                         Version
=========  =======================================================  ==========
 Enabled    com.siemens.Teamcenter5                                        5.0

0 extension installed for Photoshop 2020 64 (ver 21.2.2)
 Status                        Extension Name                         Version
=========  =======================================================  ==========

0 extension installed for Photoshop CC 64 (ver 20.0.10)
 Status                        Extension Name                         Version
=========  =======================================================  ==========

0 extension installed for Others
 Status                        Extension Name                         Version
=========  =======================================================  ==========

This is what my manifest looks like:

![image](https://user-images.githubusercontent.com/14878996/92507939-c42f8c80-f1d5-11ea-85d6-b8f04ab43fe7.png)

**Comment by ErinFinnegan** [comment]
Hi @AndrewMore1 !

Try re-installing the Creative Cloud Desktop app and then running ExManCmd again, let us know if that helps.

You can also try deleting the ExMan.db file... again, tell us the results.

**Comment by AndrewMore1** [comment]
> Hi @AndrewMore1 !
> 
> Try re-installing the Creative Cloud Desktop app and then running ExManCmd again, let us know if that helps.
> 
> You can also try deleting the ExMan.db file... again, tell us the results.

I tried both deleting the ExMan.db from the C:\ProgramData folder, AND uninstalling everything.  Neither had any effect.

**Comment by rahul-dutt-sharma** [comment]
the reason why ur extension works is cause it has ILST and IDSN as well, thus exman installs it
try adding this to ur manifest for photosop instead of wht u have now
<Host Name="PHXS" Version="[18.0,99.9]" />
            <Host Name="PHSP" Version="[18.0,99.9]" />

**Comment by AndrewMore1** [comment]
Ah, that fixed it!  Seems like this should be mentioned somewhere in the documentation, which just lists both PHXS/PHSP as if they have the same meaning.  Looking at the example manifest, only PHXS is used.

**Comment by rahul-dutt-sharma** [comment]
Yes, the documentation of CEP, Adobe Plugins SDK etc is a challenge to go through with so many of these going around. 

Glad I could help.

**Comment by sujaisivanandan** [comment]
PHSP/PHXS is mentioned https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_9.x/Documentation/CEP%209.0%20HTML%20Extension%20Cookbook.md#applications-integrated-with-cep.
