### ISSUE TITLE
ExManCmd - Extension with the same name already exists (Mac)

### ISSUE THREAD

**Issue by StefanRiedmann** [Adobe-CEP/CEP-Resources#309]
Hello
We have a serious issue on several client machines (Mac). They can't update our extension with ExManCmd (see error in title). We have a hybrid extension containing an .aip plugin and a HTML part. We managed to delete the HTML part manually here: 

Application Support>Adobe>CEP>Extensions.

...but the error persists. My guess is that the .aip is stuck somewhere, but we can't find it. 
The question is, how can we thoroughly remove any remnants of old extension installations? 

Another detail:
Trying to solve the issue on their own, two of them installed the ExtensionManagerCC or CS6. I know it's deprecated, but does this make the problem worse?

**Comment by ErinFinnegan** [comment]
Hi Stefan!

Did you try reinstalling the Creative Cloud Desktop app? Have you tried deleting the invisible ExMan.db file?

Anastasiy recently released a new version of his [Extension Manager](https://install.anastasiy.com/) that fixes some errors, I'd try that, too.

Otherwise, you'll have to do the [troubleshooting steps that we did before for this issue](https://github.com/Adobe-CEP/CEP-Resources/issues/298).

**Comment by StefanRiedmann** [comment]
Sorry @ErinFinnegan I forgot to mention that we did the steps from the issue #298 
Now I'll forward your message and let you know when there's news.

**Comment by StefanRiedmann** [comment]
Hello @ErinFinnegan 
Now we know the exact error code (-411). According to the [Documentation](https://helpx.adobe.com/exchange/kb/error-codes.html) it's because of incompatible versions. 
They have 2017 and 2018 installed. Our extension is only compatible >=2018. Can this be the issue? That there's one incompatible version on the system, and one compatible version?

**Comment by ErinFinnegan** [comment]
🤔  Well, here's another work around with another database file to delete:

1. Sign out of Creative cloud and quit the Creative Cloud Desktop app 
2. Delete opm.db at  users/*****/Library/Application\ Support/Adobe/OOBE
3. Launch the Creative Cloud Desktop app and sign in again
4. Install a zxp.

The troubleshooting after that means sending me the log files and ExMan.db and the steps to reproduce to my email... 

(I'm waiting on a build of ExManCmd 7.11 to prerelease at the moment, too.)

**Comment by StefanRiedmann** [comment]
Hi Erin. There's a small update on this, and it's kind of obvious. When people use older versions of Illustrator, we have to use older versions of ExManCmd, although we're installing new zxp's. So there's some backward compatibility missing I guess. 
Of course, people should always have the latest versions, but what can I say to our clients? :-)

**Comment by StefanRiedmann** [comment]
So that was it. Thanks for the help! Closing the issue...
