### ISSUE TITLE
ZXPSignCMD 3.0.19 fails when signing with tsa flag on ElCap 10.11.0

### ISSUE THREAD

**Issue by johnlouis-swaine-axomic** [Adobe-CEP/CEP-Resources#31]
`Error - the timestamp returned from the chosen TSA could not be verified, so the ZXP created is likely to be rejected by other tools. Please recreate your ZXP with a different trusted TSA.`

Fails with both `https://timestamp.geotrust.com/tsa` and `http://tsa.safecreative.org`

Worked fine under Yosemite

**Comment by nvkzNemo** [comment]
+1
> The [extension name] could not be loaded because it was not properly signed

**Comment by arthurwei1975** [comment]
We are investigating this issue.

**Comment by shawnflanagan** [comment]
+1 as well. Cannot find a trusted TSA, so I'm assuming it's something with the ZXPSignCMD running on OS X 10.11

**Comment by undavide** [comment]
+1 here too :-/

**Comment by johnlouis-swaine-axomic** [comment]
Yep, I ended up signing it on an older box. Thanks for looking into it @arthurwei1975!

**Comment by Jolg42** [comment]
+1 Anything new concerning this bug ? ping @arthurwei1975

**Comment by fgregor** [comment]
Thanks for your patience with this. The reason this issue has arisen on El Capitan is that Apple has removed trust for the root CA certificate of the certificate used by the Geotrust timestamp server. Unfortunately we've not been able to find another timestamp server that has its certificate in the format ZXPSignCmd needs - so changes are being made to ZXPSignCmd to enable support for alternative formats, as well as cope with the Geotrust issue itself. In the meantime, I'm afraid the recommendation is to use an older version of OS X, Windows, or sign without timestamps (and re-sign later once the timestamp issue is fixed).

**Comment by Jolg42** [comment]
@fgregor Thanks for the explanation. So if changes are being made do you think it will be available by the end of the month or in january maybe ?

In fact your solution signing whithout the timestamp is not working for Adobe Exchange, there is an error message like `the expiration date of your certificate need to be in 8 years from now minimum or having a timestamp` if not the upload is cancelled :/ (and code signing certificate are only valid 1 year)

For now I'm stuck to use a Virtual Machine for that and that's painful :cry: 

So please tell us when the update is ready :smiley: 

BTW, it will be nice to update the documentation if it's not fixed soon for developers discovering this problem.

**Comment by Kitniak** [comment]
@fgregor  I'm getting exactly the same error on windows 7 and windows 10. Is there a way around this to sign and timestamp extension? What is actually happening, I thought it will work on windows. 

I have also tried on mac yosemite 10.10.3 META-INF and mimetype is generated but it goes to root folder instead of HTML. When I move it manually and install plugin Photoshop gives a message that extension wasn't signed properly.

**Comment by undavide** [comment]
@fgregor, do you think that in the meantime we can use `ucf.jar` (for some reason, it seems to accept both `http://timestamp.entrust.net/TSS/JavaHttpTS` and `https://timestamp.geotrust.com/tsa`, i.e. is there any drawback?
Thank you,

Davide

**Comment by fgregor** [comment]
Hi @undavide - UCF.jar should be an option as long as your ZXP does not contain symbolic links (e.g. InDesign plugins).

@Kitniak, @Jolg42 - I would hope to have a new release of ZXPSignCmd within around 2 weeks. I'll update you as soon as I know more.

Thanks all for your patience - I realise this is not ideal.

**Comment by fgregor** [comment]
Hi @undavide, @Kitniak, @Jolg42 - Please see ZXPSignCmd 3.0.30. This build should fix issues seen when adding timestamps using the Geotrust timestamping authority and also enable creating timestamps using other timestamping authorities (e.g. http://timestamp.digicert.com). It's worth noting that the bug that existed in previous builds of ZXPSignCmd also therefore exist in older versions of CEP - so if you use these newly supported timestamp authorities (e.g. digicert), those timestamps won't be accepted by older versions of CEP (or Adobe Add-ons/Exchange).

**Comment by Jolg42** [comment]
@fgregor Nice! Thanks for the update, I will check that asap!

**Comment by Jolg42** [comment]
@fgregor I was using it today on El Capitan with Geotrust, everything was fine! Thank you for the fix! :+1:

**Comment by fgregor** [comment]
Perfect - thank you for confirming, @Jolg42!

**Comment by aescripts** [comment]
Is there any difference between `ZXPSignCmd` and `ZXPSignCmd-minimal` besides file size?

**Comment by xiaoyi-tong** [comment]
Involved Fraser.

**Comment by aescripts** [comment]
>Involved Fraser.

Sorry would you mind clarifying this?

**Comment by xiaoyi-tong** [comment]
Sorry, I just forwarded the issue to the prime of ZXPSignCmd.

**Comment by aescripts** [comment]
What is the "prime of ZXPSignCmd"?

**Comment by fgregor** [comment]
ZXPSignCmd-minimal isn't recommended for general use - this is a stripped down tool that only does validation of ZXPs. For signing, you should use ZXPSignCmd.

**Comment by aescripts** [comment]
Thanks for the clarification @fgregor
