### ISSUE TITLE
Super weird bug with track.insertClip (in Premiere)

### ISSUE THREAD

**Issue by micodeyt** [Adobe-CEP/CEP-Resources#314]
Hello !

I found a super weird bug today, when I run 
`
var outPoint = new Time()`
`outPoint.seconds = 66.96`
`myProjectItem.setOutPoint(outPoint, 4)
`
The out point of the ProjectItem becomes _00:01:06:23_.
The sequence is at 25fps so it should be _00:01:06:24_ instead. (0.96*25 = 24)
If you add `0.000000000000005` or more (yes, I found the value by hand :smile:) to `outPoint.seconds` it becomes __00:01:06:24__, the expected value.

I could reproduce this for : 64.96, 65.96, 66.96, 67.96, 68.96
Nothing else, this is so weird !

**Comment by bbb999** [comment]
Snippet to repro, please?

**Comment by bbb999** [comment]
I don't think it's weird; if the Time value is somewhere between the frame at 00:01:06:23 and the frame at 00:01:06:24, then the frame corresponding to that Time should still be the one at 00:01:06:23.

**Comment by bbb999** [comment]
If it's helpful, there are 254016000000 ticks per second.

**Comment by micodeyt** [comment]
> If it's helpful, there are 254016000000 ticks per second.
It is ! I ended up using ticks rather than seconds as I suspect the bugs I mentioned are due to js floating numbers implementation. Working as expected now.

Thanks :+1:

**Comment by bbb999** [comment]
More, from PPro Engineering:

> I'm pretty sure this is a floating point error issue.  The time probably became something like 23.99999 frames at some point in the callstack and we always truncate any fractional parts of a frame rather than round. In fact I'd bet .96 became 0.959999 right at parse time; Happens a lot when parsing float numbers.

Also, I was a little off, above: 

> I'm not sure you're posted answer is quite correct.  0.96s in a 25fps timeline is exactly 24, so he should expect to see 00:01:06:24.
