### ISSUE TITLE
Communicate between CEP Extension and C++ Plugins within Adobe Host.

### ISSUE THREAD

**Issue by meetgurudev** [Adobe-CEP/CEP-Resources#318]
Hi,

In Illustrator,  I'm looking for a some csxs call to communicate between HTML Panel (CEP Extension) and plugins built using C++ (_.aip_ plugins built on Qt Framework, if that helps).

Is there a possibility currently? I have looked over internet, couldn't find any supporting document on this.
If there is so, please help me to find the relevant resources for establishing to and fro communication in the above mentioned scenario.  

Thanks in advance!

**Comment by bbb999** [comment]
As long as the extension and the plug-in are listening for / sending the same CSXS message, It Should Work™. I'm told the Illustrator C++ SDK contains some example usage.

**Comment by meetgurudev** [comment]
Thanks @bbb999

I have gone through the Adobe AI C++ SDK document. There is a section explaining the communication between plugins and html panels. However, the description and examples there seemed insufficient to clearly cover the context. I was expecting more document resource specific to this particular case. 

Thanks for replying!
