### ISSUE TITLE
Depcrecated tutorials

### ISSUE THREAD

**Issue by Chris2011** [Adobe-CEP/CEP-Resources#32]
Hey, I have the Adobe CC 2015, hopefully last update and I wanted to create a plugin for PS and I found a plugin for Brackets: http://davidderaedt.github.io/CC-Extension-Builder-for-Brackets/

It does not more than creating a template for you. So when I wanted to make a package I have to use the ZxpSignCmd. When I created a certificate for that I can create the .zxp package. So far so good, but than when I want to add it to the extension manager I got the error that it couldn't be installed and I have to check the manifest.xml.

When I use the ExManCmd, because I read thet the ExtManager will not developed further anymore, I got the message: failed to install, status = -411. I googled a while but I didn't find a solution. So I found a couple of tutorials but each where, I think outdated (as you can see it here: http://www.adobe.com/devnet/creativesuite/articles/a-short-guide-to-HTML5-extensions.html, the folder is not available what he mentioned: %APPDATA%\Adobe\CEPServiceManager4\extensions). So what is the error -411 stands for? What did I wrong maybe? Can you help here out the confusion please?

Cheers

Chris

**Comment by undavide** [comment]
Chris, the folder for CC2015 is (on Win) `CEP\extensions\` and not `CEPServiceManager4\extensions` which used to work for CC - if this is what you're asking.
Error code -411 is Compatible Application not found, according to [this page](http://www.adobeexchange.com/resources/19#errors). You can try to make `ExManCmd` list the available applications - in case *he doesn't know* about PS CC2015 that would be the reason he fires that error. (` - ExManCmd --list all`).

If you look for tuts and doesn't already know them, a guy who has time in his hands :-) wrote this collection of [Photoshop HTML Panel Tips](http://davidebarranca.com/category/code/html-panels/).

Hope this helps,

-Davide

**Comment by Chris2011** [comment]
So the link you pasted is a complete series to create a HTML5 application or more for Adobe CC 2015, right? As I can see it right?

ExManCmd --list all shows me nothing

In the AppData\Roaming\CEP\extension is my Test folder but it doesn't show up in Photoshop.

**Comment by nvkzNemo** [comment]
@Chris2011 check your manifest.xml
```
<!-- Photoshop CC or higher -->
<Host Name="PHXS" Version="14.0" />
<Host Name="PHSP" Version="14.0" />
```

**Comment by Chris2011** [comment]
Really thx, that helped, the problem was that I had this:

```HTML
<HostList>
    <Host Name="PHXS" Version="[14.0]"/>
 </HostList>
```

And I had this from an other tutorial I think ^^.

**Comment by undavide** [comment]
Hi @Chris2011 
as for a complete set of tutorials on building HTML Panels, I'm currently writing an ebook, (temporarily) titled **Photoshop HTML Panels Development - Build and Market Adobe Creative Cloud extensions**. I haven't yet a release date - which will be somewhere in Q1/2016.
The tuts series I've pointed you to are a collection of tips solving specific problems that you are very, very likely to encounter - (I will be embedding a revised version of them in the book). Stay tuned in my blog - I haven't announced the project publicly there since I'm only at chapter 8, but probably I'll do soon.
Regards,
-Davide

**Comment by Chris2011** [comment]
Nice to here :) I will stay tuned. Thx for your helps.

**Comment by Qwertyfly** [comment]
I have just written my first Extension.
packaged it using ZXPSignCmd.exe
sent it to a friend to test.
installs fine on my PC.
but he gets Error: Please, make sure the manifest.xml of this extension is valid.
on searching I find that Extension Manager has been depreciated.
But I find no info on what is replacing it or what the new process is.

can someone please direct me to some documentation that is relevant.

**Comment by arthurwei1975** [comment]
Extension Manager application had been depreciated, but Extension Manager command line tool can be used. Please find its link on https://github.com/Adobe-CEP/CEP-Resources

**Comment by Chris2011** [comment]
I tried both, I tried the extension manager and the ExtManCmd, both are not working for me. At the Extension Manager it says that I can't install the Zxp Package, without any warning or error. With the CmdLine tool, I got the message failed to install -411. The problem with both, I can't see the list of installed adobe products. so ExtMan Cmd with list all will show nothing and the extension manager shows me nothing too, but I don't know how to fix this. Have the latest version of Adobe CC.

**Comment by Chris2011** [comment]
I found a tutorial in a form, where I have to uninstall it and reinstall it, but it didn't worked.

**Comment by fgregor** [comment]
Hi Chris,

Can you please avoid using Extension Manager CC, then install or uninstall any Adobe application via the Creative Cloud desktop app. After that, without touching Extension Manager CC, try using ExManCmd to install?

ExManCmd only updates its list of installed applications once after the Adobe installed application database changes. Therefore if you use Extension Manager CC (which does not support CC 2015), then CC 2015 applications will not get the chance to be added to the list. 

Fraser

**Comment by Chris2011** [comment]
Hey, yes I will try to avoid that, thats why I used ExManCmd. I will follow your instructions. thx. :)

**Comment by Qwertyfly** [comment]
the ExManCmd.exe command line tool is not the greatest way of asking people to install plugins.
and the adobe Exchange portal is a complete ripoff.
(I dare you to ask my why...)

and the command line tool is slow and cumbersome.
If I try to create an installer that uses it I still get UAC prompts etc... which is not what I want.
and how do I check if the plugin is installed already.
what feed back can I get from the command line tool?

**Comment by Chris2011** [comment]
Exactly, but what is the best way or best practices to install a zxp certified plugin? Is the ExManCmd the only way? Is there an other gui replacement from adobe for the Extension Manager tool?

**Comment by undavide** [comment]
Have you tried zxpinstaller.com?

**Comment by nvkzNemo** [comment]
or [install.anastasiy.com](http://install.anastasiy.com/)

**Comment by Chris2011** [comment]
I've tested both and both are working great :). Drag'n drop the zxp file and thats it.
