### ISSUE TITLE
Windows CEFClient for CEP 10 Crashes

### ISSUE THREAD

**Issue by AndrewMore1** [Adobe-CEP/CEP-Resources#323]
Steps:

1) Start cefclient.exe
2) R-click in the pane
3) Select Show DevTools

Result: Immediately crashes.

I'm also having issues with it loading an internal company app, but I can't provide easy access to that.

**Comment by ErinFinnegan** [comment]
Hi Andrew,

Are you definitely using [CEF Client 74](https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_10.x/Cefclient_v74)?

Can you give your exact version of Windows?

**Comment by AndrewMore1** [comment]
Yes, I just triple checked.  I am using the CEF Client downloaded from this part of the repository.
https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_10.x/Cefclient_v74/Cefclient_Win64.zip
It would be easier to check this if your help about displayed a useful version and date.

I am running Windows 10, Version 10.0.17763 Build 17763.

**Comment by MaxJohnson** [comment]
Same issue. Windows 10.
My CEF 79.1.38 from CEP9 runs fine.

**Comment by sujaisivanandan** [comment]
@AndrewMore1 @MaxJohnson  Are you seeing this issue for specific extensions? I'm not able to repro this on the CEP Sample Extension.

Need some info:
- Which extension are you trying to debug in CEFClient, which reproduces this issue?
- Can you debug the same extension on Chrome(latest version) and do you see the problem there?

**Comment by AndrewMore1** [comment]
No, no extension, all I'm doing is what's in the instructions.  I've upzipped the cefclient zip file in my Windows download directory.

**Comment by ErinFinnegan** [comment]
@sujaisivanandan I was able to reproduce this issue on a Windows machine:

-  I dowloaded the CEF client from the repo
- Unzipped the package contents in the "Downloads" folder
- Ran the `cefclient.exe`
- Tried to go to `https://localhost:8088` 
- When I hit Enter the cefclient crashes.

My device has Windows 10 Enterprise, version 1903, OS build 18362.1139

I tried quitting all the Creative Cloud processes in the Task Manager and _then_ running `cefclient.exe` and observed the same behavior.

**Comment by Inventsable** [comment]
Same issue, except my CEFClient window crashes immediately after opening. I don't even get a chance to right click or change the URL address, I briefly see the Google homepage then see it crash immediately.

Am I not allowed to have different versions of CEFClient installed at the same time?

Running on Windows 10 Pro v2004, OS build 19041.572

**Comment by sujaisivanandan** [comment]
@AndrewMore1 @MaxJohnson @Inventsable We have a fix in progress..

You ca try the build for this PR in the meantime:
https://github.com/rushilmahajan-adobe/CEP-Resources/tree/master/CEP_10.x/Cefclient_v74

**Comment by AndrewMore1** [comment]
@sujaisivanandan Seems to be working better than the previous client.  I no longer see it crashing when loading the dev tools, and it works with my more complex enterprise application.
