### ISSUE TITLE
Why is the Extension menu item in Photoshop 2021 labeled "Extensions (Legacy)"?

### ISSUE THREAD

**Issue by AndrewMore1** [Adobe-CEP/CEP-Resources#325]
I understand XD plugins is going to replace Adobe Extensions at some point, but it doesn't appear to be there yet.  Is this the reason for the change?  Is Photoshop the first app besides XD to support XD plugins?

**Comment by ErinFinnegan** [comment]
>  Is Photoshop the first app besides XD to support XD plugins?

We're calling the technology behind XD plugins "UXP". You can read more about it here: [https://adobe.ly/max2020uxpps](https://adobe.ly/max2020uxpps)

> ...it doesn't appear to be there yet.

I highly recommend watching this video:[ https://youtu.be/zAOUBpDjc1Q]( https://youtu.be/zAOUBpDjc1Q) which does a good job of explaining where UXP is right now and where it's going. I'd say Davide's video also covers "the reason for the change."

And so, yes, Photoshop is the second app to have UXP after XD.
