### ISSUE TITLE
Why has the version of the Chromium Embedded Framework reverted in CEP10?

### ISSUE THREAD

**Issue by AndrewMore1** [Adobe-CEP/CEP-Resources#326]
Is there a reason why the version of the CEF used in CEP 10 is CEF 74, a reversion from CEF 79 used in CEP 9?

**Comment by AndrewMore1** [comment]
To be very clear our extension of CEP ties in with a very large enterprise application that is developed by a separate team over which we have very little control.  It is important to our uses that the CEF version progress, rather than regress to avoid issues with the implementation of this enterprise application.

**Comment by sujaisivanandan** [comment]
@AndrewMore1 
CEP 9 has CEF v61 version integrated and in CEP 10 we have upgraded to CEF v74.

You can find the specific details here: https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_10.x/Documentation/CEP%2010.0%20HTML%20Extension%20Cookbook.md#chromium-embedded-framework-cef 

CEF is upgraded and has not regressed.

**Comment by AndrewMore1** [comment]
When I run the cefclient from here:  https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_9.x  And run it against this site: https://www.whatismybrowser.com/

It reports as CEF 79.  My understanding was the cefclients were supposed to be at the exact same version of CEF as the one compiled into CC.

**Comment by sujaisivanandan** [comment]
Hi @AndrewMore1 
the CEFClient for v61 was earlier shared in the CEP_9.x location. However due to certain bugs, we had asked clients to pick a new one using v79. However do note that this is only for CEFClient application. The CEF library that is integrated in CEP 9 in all the Adobe Products had CEF 61.

**Comment by AndrewMore1** [comment]
Thank you that provides some clarification for the situation.
