### ISSUE TITLE
getNetworkPreferences() use?

### ISSUE THREAD

**Issue by undavide** [Adobe-CEP/CEP-Resources#33]
Hi,
may I ask what is `getNetworkPreferences()` exactly for? 
It doesn't seem to fetch correctly the online status of the user (which instead `navigator.onLine` gets), but seems to get the Photoshop "Allow Extensions to Connect to the Internet" preference. 
So what are `isAdminOnline` and `isUserOnline`?
Thank you!

Davide

**Comment by yugguo** [comment]
Hello, you can use navigator.onLine to check the online status. JavaScript API getNetworkPreferences just follows the behavior which is defined in Flash world.
