### ISSUE TITLE
CEP-2255: CEP10 CEFClient application issues useless alert on startup

### ISSUE THREAD

**Issue by ericdrobinson** [Adobe-CEP/CEP-Resources#331]
## Problem Description
The CEP10 version of the Cefclient (available [here](https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_10.x/Cefclient_v74)) shows the following alert whenever the application is started.

![image](https://user-images.githubusercontent.com/9142587/98705755-09924680-234c-11eb-806a-69f500253859.png)

## More Information
Pressing either "Ok" or "Cancel" dismisses the alert but the main application window does **not** appear. In order to make it appear, the application icon in the Dock must be clicked a second time once the alert is dismissed.

This is exceedingly annoying.

## Environment
This is confirmed to occur on both macOS 10.14.6 and [macOS 10.15.7](https://github.com/Adobe-CEP/CEP-Resources/issues/329#issuecomment-724500764).

**Comment by Inventsable** [comment]
It does but I assume that Mac doesn't parse the title and description for some reason. On Windows, this popup does show once I hit Inspectable WebContents, but is:

![ice_screenshot_20201110-155019](https://user-images.githubusercontent.com/37279677/98743015-9fd66480-236c-11eb-8e07-bf58e613ab99.png)

**Comment by ericdrobinson** [comment]
I guess that's different, then? In macOS, the alert in the initial description appears _immediately_ when launching the cefclient application itself. You don't even get to see the application window until you click through that and then click the application icon in the dock a second time...

**Comment by sujaisivanandan** [comment]
@ericdrobinson @Inventsable can you try the build from : https://github.com/rushilmahajan-adobe/CEP-Resources/tree/master/CEP_10.x/Cefclient_v74

Will merge this once I get a confirmation from you.

**Comment by ericdrobinson** [comment]
@sujaisivanandan The build you linked seems to resolve the "useless startup alert" issue on macOS. Thanks!

**Comment by Inventsable** [comment]
@sujaisivanandan No change in behavior on Windows -- I wasn't having crashes on context menu click in the last build, both the same popups appear, etc. Unsure if I'm expected to notice something different but in any case appears perfectly stable and functional on my end 👍

**Comment by sujaisivanandan** [comment]
Thanks @ericdrobinson @Inventsable for confirming. I have merged the changes.
Closing this ticket as fixed.
