### ISSUE TITLE
CEP-2255: CEP10 CEFClient application crashes on right-click

### ISSUE THREAD

**Issue by ericdrobinson** [Adobe-CEP/CEP-Resources#332]
## Problem Description

The [CEP10 cefclient](https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_10.x/Cefclient_v74) crashes when the user right-clicks on the landing page.

At time of writing, this has only been tested on macOS 10.14.6 but it happens every single time.

## Steps to Reproduce

1. Launch the CEP10 cefclient application.
1. Click "Ok" or "Cancel" to dismiss [the useless alert](https://github.com/Adobe-CEP/CEP-Resources/issues/331).
1. Click the cefclient icon in the dock to show the application window.
1. Right-click (context click) anywhere on the resulting "Google.com" landing page.
1. Observe application crash.

## Expected Results

The application should not crash and a context menu should appear.

**Comment by Inventsable** [comment]
Does not happen on Windows 10 for me, as of the newest patch (since it crashed the moment it opened and I couldn't use it prior 🤷)

**Comment by ericdrobinson** [comment]
@Inventsable Can you verify whether or not #331 happens on the latest version on Windows 10?

**Comment by sujaisivanandan** [comment]
@ericdrobinson  we are able to repro this issue on Windows. Thanks, we will provide you a fixed build shortly.

**Comment by sujaisivanandan** [comment]
@ericdrobinson @Inventsable  can you try the build from : https://github.com/rushilmahajan-adobe/CEP-Resources/tree/master/CEP_10.x/Cefclient_v74

Will merge this once I get a confirmation from you.

**Comment by ericdrobinson** [comment]
@sujaisivanandan The build you linked seems to resolve the right-click crash issue on macOS. Thanks!

**Comment by Inventsable** [comment]
@sujaisivanandan Just to confirm, I wasn't having this issue on Windows 10 but the new build looks to be stable on my end

**Comment by sujaisivanandan** [comment]
Thanks @ericdrobinson @Inventsable for confirming. I have merged the changes.
Closing this ticket as fixed.
