### ISSUE TITLE
Since the latest CC update CEP panels in AE don't work properly

### ISSUE THREAD

**Issue by vidjuheffex** [Adobe-CEP/CEP-Resources#34]
All my panels, which use the Node API, have the following console msg: Uncaught ReferenceError: require is not defined

not sure how this is possible given that require should be in the global namespace, all were working fine until the update.

**Comment by undavide** [comment]
Hi,
have a look at [this blogpost](http://www.davidebarranca.com/2015/12/html-panel-tips-19-cc2015-1-cep6-1-node-js-fixes/) for workarounds and explanation about the reason why they now fail (TL;DR Node is handled differently on CEP6.1)
Regards

-Davide

**Comment by vidjuheffex** [comment]
Wow thanks!
