### ISSUE TITLE
CEP 10 : cep_node.global.require is not a function.

### ISSUE THREAD

**Issue by meetgurudev** [Adobe-CEP/CEP-Resources#343]
Hi,
Thanks in advance!

I am currently working on file syncing extension having client server redirects and also uses `window.cep_node.require` to access node globals like `fs`, `path` etc., mainly.

While trying provide support of extension in 2021 version hosts, I am encountering issues despite following the [Migration from CEP 9 to CEP 10 guides](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_10.x/Documentation/CEP%2010.0%20HTML%20Extension%20Cookbook.md#migration-from-cep-9-to-cep-10).

I have updated my node version to latest (v14.15.4), and did run `npm update` and `npm install`. However, I am getting an error as `process_main:1 Uncaught TypeError: cep_node.global.require is not a function` which is not used directly though.

I followed the steps in the issue #328, #335. 

But I still get the same issue -Once redirection is triggered to part of code using `window.cep_node.require`, the extension redirects to the default index.html location and throws the error as shown, 
`process_main:1 Uncaught TypeError: cep_node.global.require is not a function  at process_main:1`

please assist me in this regard, thank you!

**Comment by sujaisivanandan** [comment]
Would it be possible for you to attach a sample extension?

**Comment by meetgurudev** [comment]
Hey,

Thanks for the reply.

The extension connects to server which needs license to login.

**Comment by meetgurudev** [comment]
@Silly-V 

Thanks, It worked.
I earlier had to remove `--mixed-context` flag wasn't allowing saml auth.

Adding back the flag resolved the issue.

Thanks!
