### ISSUE TITLE
No license in CEP9_x

### ISSUE THREAD

**Issue by dmitriyyepishin** [Adobe-CEP/CEP-Resources#347]
There is no license information in CEP9_x folder. The license information is present in 3 earlier versions in their respective folders. Please add license information to CEP9_x.

**Comment by ErinFinnegan** [comment]
This is the same as https://github.com/Adobe-CEP/CEP-Resources/issues/432...

**Comment by ErinFinnegan** [comment]
I'm closing this ticket, too, with the same explanation:

> Effectively, the 8.x license still the correct license to use for the time being.
> 
> We're currently re-working developer touch points and the overall developer experience, including where and how developers use and agree to legal terms. Since it may be several months before we have a new agreement in place, you should continue using the previous terms.
> 
> If your legal department wants to follow up, I can put them in touch with the legal team. Reach out to me at finnegan (at) adobe.com (I'm not a lawyer, I work on a developer experience team...)

**Comment by dmitriyyepishin** [comment]
Perfect.
________________________________
From: Erin F. ***@***.***>
Sent: Tuesday, March 29, 2022 11:00 AM
To: Adobe-CEP/CEP-Resources ***@***.***>
Cc: Dmitriy Yepishin ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [Adobe-CEP/CEP-Resources] No license in CEP9_x (#347)


I'm closing this ticket, too, with the same explanation:

Effectively, the 8.x license still the correct license to use for the time being.

We're currently re-working developer touch points and the overall developer experience, including where and how developers use and agree to legal terms. Since it may be several months before we have a new agreement in place, you should continue using the previous terms.

If your legal department wants to follow up, I can put them in touch with the legal team. Reach out to me at finnegan (at) adobe.com (I'm not a lawyer, I work on a developer experience team...)
