### ISSUE TITLE
Chrome Debugger scrolling is broken with CC 2015.1 update

### ISSUE THREAD

**Issue by alexwidener** [Adobe-CEP/CEP-Resources#35]
Adobe extensions appear to be breaking Chrome's debugger(Chrome is up to date). When running in full-screen (and only when debugging an Adobe extension), if you fill a page up, scrolling is broken. I'm attaching a screenshot below and as you can see, I flood the window, but scrolling is disabled. Using the debugger for anything other than an Adobe extension works just fine.

This was working in 2014 and 2015.0, but no longer works in 2015.1

It occurs on both OS X 10.10.x and Windows 7 with Chrome 47.0.2526.73 m

![scroll](https://cloud.githubusercontent.com/assets/3489076/11699272/39193e1a-9e89-11e5-85d7-a272c42c3ec7.PNG)

This has been posted as a potential aide for this, but I was unable to get it to work on my machine: 
https://code.google.com/p/chromium/issues/detail?id=516760

**Comment by alexwidener** [comment]
If anyone wants to have an unintuitive and not great temporary fix, refer to the comments section on this page: 

http://www.davidebarranca.com/2015/12/html-panel-tips-19-cc2015-1-cep6-1-node-js-fixes/

Note that it is a per-session fix.

**Comment by marksutfin** [comment]
Same here, I ended up editing the CSS as Bruce said in the comments on that blog post. Any permanent solution besides waiting for the next update?

**Comment by alexwidener** [comment]
@marksutfin Unfortunately, nothing permanent now. I gave a shot at creating a Chrome extension(which is easy to do) but couldn't get it to inject on initialization(although web stuff isn't my area). That would be my best suggestion if you can get it working. I don't really have much time to mess around with it.

**Comment by marksutfin** [comment]
@alexwidener, thanks! I'll update if I came up with something.

**Comment by Jolg42** [comment]
Hi!

I have found an easier way to do that,
I'm using the css injection workaround with a chrome extension (so I only have to do it once & forget about it!)
- Install Styler - Chrome Web Store
- Go to your debug page http://localhost:8001/
- Click on Styler extension icon
- Add "html /deep/ * { min-width: 0; min-height: 0; }"

And voilà!

**Comment by alexwidener** [comment]
@Jolg42 NICE! This is great, thank you so much. 

To anyone else - this is great because it's persistent on a per-page basis, even between closing down Chrome. We have seven extensions and only have to do it once per extension and it maintains it. This is a great workaround, thanks.

**Comment by anastasiuspernat** [comment]
@Jolg42 Thanks for the workaround, it's awesome!

My question to Adobe CEP team and @arthurwei1975: are there any plans to fix this issue with scrolling on your side? When I have several extensions to debug on different computers, even with the workaround it is driving me nuts! Thank you!

**Comment by arthurwei1975** [comment]
This is a Chromium issue. It will be fixed when we upgrade to newer version of CEF/Chromium.

**Comment by akibnavidkhan** [comment]
This issue is fixed in cc 2018 update which includes CEP8(integrates Chromium V57).
