### ISSUE TITLE
Dreamweaver 2021 is giving $ is not defined error

### ISSUE THREAD

**Issue by MayaAnusiya** [Adobe-CEP/CEP-Resources#354]
Hi Team, We tried to load the JQuery scripts in the Dreamweaver 2021. We are getting "$ is not defined" error in Dreamweaver 2021 only. We are loading the same script in Dreamweaver2020, which looks good. Please find the attached screen capture of it.

https://www.screencast.com/t/nJD4ovVMA

We are using Node js in our panel extension. Please find below block of code, which we added in the manifest file, which is using CEP 9 before and we also tried CEP 10 for Dw2021. When we remove the "enable-nodejs" parameter element. We don't see "$ is not defind" error. But, Node js code is not working. Could you please suggest us how to enable Node js without any issues in the panel extension.

`<CEFCommandLine> 
   <Parameter>--enable-nodejs</Parameter> 
   <Parameter>--mixed-context</Parameter> 
</CEFCommandLine>`

Please find the link for our DemoPanel from the [link](https://www.dropbox.com/s/m980z2lblhm9cf6/DemoPanel.zip?dl=0)

**Comment by ErinFinnegan** [comment]
Are you using[ the right version of node for CEP 9?](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_10.x/Documentation/CEP%2010.0%20HTML%20Extension%20Cookbook.md#chromium-embedded-framework-cef)

**Comment by sujaisivanandan** [comment]
@MayaAnusiya I can see that jsfiddle.net is working fine in the sample extension - https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_10.x/Samples/CEP_HTML_Test_Extension-10.0

You can use the HTML1 option on the left navigation on this extension and then navigate to jsfiddle.net within this page.
I can see that this works in the sample. The manifest and CEFCommandLine options looks good. I suspect that JQuery may not be initialised when you are calling this in your extension. Do check the order within your html where you are calling 

<script type="text/javascript" src="../js/JQuery/jquery.js"></script>


DW2021 has an updated version of CEF compared to DW2020 and maybe the conditions have become more strict which maybe causing this.

**Comment by Inventsable** [comment]
@sujaisivanandan Do you have a sample extension as a public repo to see?

**Comment by sujaisivanandan** [comment]
@MayaAnusiya  Did you get a chance to check this?

**Comment by MayaAnusiya** [comment]
We tried the workaround by replacing the parameter "--mixed-context" by "--separate-context". It works for us. Thanks!!!
