### ISSUE TITLE
Google login not working in CEP 10

### ISSUE THREAD

**Issue by zhangusc** [Adobe-CEP/CEP-Resources#355]
Steps to reproduce:
1. Download the CEFClient https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_10.x/Cefclient_v74
2. Open CEfclient.exe and type in https://www.google.com
3. Click "Sign In" and type in your Google account username and password
4. Sign in fails with an error message below
![image](https://user-images.githubusercontent.com/7468979/112527938-cbc51600-8d60-11eb-8c37-df4374beec26.png)

**Comment by zhangusc** [comment]
@ErinFinnegan This is a critical issue that could impact many extensions/applications.

**Comment by Inventsable** [comment]
I don't follow. Why would you need to sign into CEFClient?

If you need Google OAuth for your panel, that has nothing to do with CEFClient. You can do that via something like the [Firebase API](https://firebase.google.com/).

**Comment by zhangusc** [comment]
@Inventsable It is not about signing into CEFClient. CEFClient is used for reproducing the issue in an easy way without installing a real extension. The fundamental problem is that Google OAuth login is no longer supporting CEP10/CEF(Chrome 74 based).

**Comment by ErinFinnegan** [comment]
@kerrishotts Do you think this is related to this measure by Google: ["Google to Block Logins from Embedded Browsers"](https://developers.googleblog.com/2020/08/guidance-for-our-effort-to-block-less-secure-browser-and-apps.html)

According to internal communications at Adobe, I thought we had a longer timeframe (until June?) to update.

**Comment by Inventsable** [comment]
> @Inventsable It is not about signing into CEFClient. CEFClient is used for reproducing the issue in an easy way without installing a real extension. The fundamental problem is that Google OAuth login is no longer supporting CEP10/CEF(Chrome 74 based).

Google OAuth is still supported through their own APIs like Firebase and OAuth 2.0 for CEP 10.

**Comment by ErinFinnegan** [comment]
Hi @zhangusc!

Engineering got back to me. The two issues might be related. Some embedded browsers are getting blocked like you've experienced, although it might not be related to the CEF version. 

We're working on getting a blog post and sample code to help developers migrate to OAuth 2.0.

Meanwhile, you can: 

- File a ticket at [https://issutracker.google.com/](https://issutracker.google.com)
- Fill out a[ Policy Enforcement Extension Request](https://docs.google.com/forms/d/e/1FAIpQLSdtYRVJSTKUtnqGcE2L9SaY6xgAgy-eHMqqcqIWOqB084Ao0A/viewform) at Google
- Let us know your issue tracker number so we can surface it with Google

**Comment by sujaisivanandan** [comment]
Closing this ticket since this is a change mandated by Google and a must fix on the CEP Plugins using Google services.
