### ISSUE TITLE
ZXPSignCmd Timestamp error (possibly SHA1 issue)

### ISSUE THREAD

**Issue by justintaylor-dev** [Adobe-CEP/CEP-Resources#358]
Starting today, when trying to sign panels with ZXPSignCmd with all of my projects like I always have, I'm suddenly running into the following error and no ZXP is generated:

`Error - the timestamp returned from the chosen TSA could not be verified, so the ZXP created is likely to be rejected by other tools. Please recreate your ZXP with a different trusted TSA.`

I've been using http://timestamp.digicert.com/ for the past several years as the TSA with no problem, but it doesn't seem to be working today. I reached out to DigiCert support and they said that they've deprecated SHA1 which I believe was used by ZXPSignCmd. 

Is there another TSA we can use instead or are you able to upgrade ZXPSignCmd to handle SHA2? Thanks!

**Comment by justintaylor-dev** [comment]
Discovered `http://time.certum.pl` works which is listed as a SHA512 TSA, other SHA512 TSAs didn't work though so not 100% if that's accurate, but this works for now.

**Comment by haruby511** [comment]
I have the same issue.
I've tried all of [this list](https://gist.github.com/Manouchehri/fd754e402d98430243455713efada710) but there is no luck.
Only `http://time.certum.pl` works.

My ZXPSignCMD is 4.1.103 win64.

**Comment by gmeeker** [comment]
I'm not sure that http://time.certum.pl is a usable workaround.  While I'm able to sign on macOS with 4.1.2, it's not working for me on Windows with 4.1.103.  Even worse, if I sign it on macOS, verification still fails on Windows (which I'm assuming means it might not be timestamped as far as the Adobe apps are concerned?)
After signing with the instruction for PProPanel, but with time.certum.pl I get this on macOS:

ZXPSignCmd -verify Samples.zxp -certInfo
*********** Certificate Information ***********
CN: Bruce Bullis
OU: 
DN: /C=US/ST=California/O=Adobe/CN=Bruce Bullis
OS Trusted: false
Revoked: false
Timestamp: Valid and within certificate validity dates at time of signing
Signing Certificate: Valid (from 2021-04-27 until 2032-07-14)
***********************************************
Signature verified successfully

But on Windows:

ZXPSignCmd.exe -verify Samples.zxp -certInfo
*********** Certificate Information ***********
CN: Bruce Bullis
OU:
DN: /C=US/ST=California/O=Adobe/CN=Bruce Bullis
OS Trusted: false
Revoked: false
Timestamp: Invalid timestamp
Signing Certificate: Valid (from 2021-04-27 until 2032-07-14)
***********************************************
Signature verified successfully

Maybe some versions of Windows don't have the root certificate for certum.pl?  This is Windows 10 Home, 20H2 19042.928

**Comment by haruby511** [comment]
@gmeeker It is weird. I've verified my ZXP, got 

    Timestamp: Valid and within certificate validity dates at time of signing
    Signing Certificate: Valid (from 2018-12-26 until 2030-03-14)

which had timestamped with `certum.pl`. My Windows is also 19042.928.

**Comment by justintaylor-dev** [comment]
I'm able to sign successfully on Windows and Mac with `http://time.certum.pl/`

@gmeeker Are you using the latest ZXPSignCmd for Mac and Windows? Side note: you'll probably want to change up your cert details from Bruce's example to your own.

**Comment by gmeeker** [comment]
@justintaylor-dev Yes I'm using the 4.1.103 win64 build from this repo.  I've tried 3 Windows machines and none of them work with http://time.cerum.pl (and they worked with digicert a few days ago).  Weird.  Maybe it's having Visual Studio installed or locale or Home vs Pro?  I suspect I won't be the only one with problems.  Hopefully Adobe can reproduce this.

The certificate above was just for illustration.  I've been using a code signing certificate from a CA but I wanted to rule out any problems with my setup.

**Comment by gmeeker** [comment]
http://timestamp.digicert.com/ started working again for me, on Mac and Windows.  Maybe they turned SHA1 back on?

**Comment by justintaylor-dev** [comment]
@gmeeker wow, it started working for me too. So strange, maybe it's not using SHA1 then...

**Comment by Pixelsplasher** [comment]
https://time.certum.pl/ could not be verified today.
http://timestamp.digicert.com/ works.
