### ISSUE TITLE
Removed Node functionality

### ISSUE THREAD

**Issue by boredstiff** [Adobe-CEP/CEP-Resources#36]
It appears that Adobe's broken(probably removed, it doesn't look like it exists anymore) the fs.watch functionality from Node, which I'm using for a constantly generating build system for the extensions. Before, if I made changes to any of the files, it would watch the files and (through some extra code)reload the application + debugger simultaneously. This is an extreme time saver for us because it takes out the process of reloading stuff while you're making changes.

This worked in 2014 and 2015.0, but not 2015.1.
This occurs on OS X 10.10.x and Windows 7.

Has this been removed or broken?

**Comment by vvasilev-** [comment]
In CEP6.1(CC 2015.1) nodejs integration is disabled by default. You need to re-enable it with CEF parameter so you will be able to require the `fs` module.

```xml
<Resources>
    <MainPath>...</MainPath>
    <ScriptPath>...</ScriptPath>
    <CEFCommandLine>
        <Parameter>--enable-nodejs</Parameter>
    </CEFCommandLine>
</Resources>
```

**Comment by p1xelHer0** [comment]
That parameter solved it for me, thanks! 

Is there any good ways to track changes like these in the future? This pretty much came a surprise when I updated InDesign to 11.2.

**Comment by vvasilev-** [comment]
This solution was found in the cookbook for CEP 6.1. So I think that is the only way to track changes between versions.

**Comment by sbaechler** [comment]
Please add @vvasilev- 's comment to the cookbook.

**Comment by Webysther** [comment]
@p1xelHer0 Close this issue, please.
