### ISSUE TITLE
CEP 11 in AE 18.4 prerelease: evalScript callbacks aren't triggered

### ISSUE THREAD

**Issue by saar62097** [Adobe-CEP/CEP-Resources#364]
Hey, I have an extenstion built with [Bombino](https://www.npmjs.com/package/bombino) which serves an app on localhost which is loaded in an iframe inside the HTML file specified in the manifest.
Up until CEP11, I could run `window.__adobe_cep__.evalScript("app", function(r){console.log(r)});` (which is just the low-level execution of CSInterface.evalScript) on **both** the top level frame **and** the nested iframed app succefully.

With CEP11 in AE 18.4, I can run it on the top-level context, but in the iframed app the callback is not executing. Note that the actual extendscript code does execute, just not the callback.

Is this a bug or is this issue related to the Content-Security-Policy changes noted [here](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#migration-from-cep-10-to-cep-11)?

thank you all in advance

**Comment by sujaisivanandan** [comment]
Hi @saar62097, the quick way to check this would be to see if your content works on the web(Chrome).
I don't have enough details to comment on this, until I know what exactly is happening in the callback.

**Comment by saar62097** [comment]
thanks @sujaisivanandan but i dont understand your suggestion.

when running in the browser, there is no "Adobe host" to run JSX files, so the `window.__adobe_cep__` object doesn't even get created.
This needs to be tested/run inside an Adobe app, in this case AE 18.4...

**Comment by sujaisivanandan** [comment]
@saar62097  this issue looks similar to https://github.com/Adobe-CEP/CEP-Resources/issues/365
@rushilmahajan-adobe  will be providing more details on this soon.

**Comment by rushilmahajan-adobe** [comment]
As mentioned by you correctly, [From CEP-11](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#migration-from-cep-10-to-cep-11) one can't access a <iframe> with a different origin (Cross-Site) using JavaScript. **For the [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) browsers block scripts trying to access a frame with a different origin.**

Origin is considered Cross-Site if at least one of the following parts of the address isn't maintained:
`protocol://hostname:port/...`
Protocol, hostname, and port must be the same as your domain if you want to access a frame.


**_Workaround :_**
Even though same-origin policy blocks scripts from accessing the content of sites with a different origin, if you own both the pages, you can work around this problem using **window.postMessage** and its relative message event to send messages between the two pages, like this:

In your Cross-Site <iframe> (contained in the main page):
`mainFrameWindow.postMessage(/*any variable or object or evalscript*/, 'http://your-main-site.com');`

The second argument to **postMessage()** can be **'*'** to indicate no preference about the origin of the destination. A target origin should always be provided when possible, to avoid disclosing the data you send to any other site.


In your main page:
```
window.addEventListener('message', event => {
    // IMPORTANT: check the origin of the data! 
    if (event.origin.startsWith('http://your-cross-site-iframe.com')) { 
        // The data was sent from your site.
        // Data sent with postMessage is stored in event.data:
        console.log(event.data); 
        // We can also invoke evalScript sent from Cross-site frame [CEP]
        var script=event.data;
        CSInterface.evalScript(script);
    } 
    else {
        // The data was NOT sent from your site! 
        // Be careful! Do not use it. This else branch is
        // here just for clarity, you usually shouldn't need it.
        return; 
    } 
}); 
```
This method can be applied in both directions, creating a listener in the cross-site child frame too, and receiving responses from the Mainframe. **The same logic can also be implemented for running CEP EvalScript from cross-site child frames- Pass your EvalScript as an event from Cross-Site child frame to Main Page and invoke EvalScript from Main Page/Frame**

**Comment by rushilmahajan-adobe** [comment]
Hi @saar62097 
If your query is resolved you can close this issue.
Thanks

**Comment by saar62097** [comment]
apologies @rushilmahajan-adobe one more question:
I noticed that unlike `evalScript`, which has a callback, actually calling a function that needs no callback, like `closeExtenstion` for example, works from within the iframe.
will this continue to be the case?

thank you
