### ISSUE TITLE
Multiple regressions in Illustrator PreRelease 25.3 (works fine on Beta 25.3 265@236190)

### ISSUE THREAD

**Issue by Jolg42** [Adobe-CEP/CEP-Resources#367]
Hi there! @rushilmahajan-adobe

I took your extension and added reproductions for more problems I noticed, these problems were also tested and confirmed by @ghenania.

## Tested with latest Prerelease 25.3, on macOS Catalina 10.15.7

I can confirm the issue mentioned in https://github.com/Adobe-CEP/CEP-Resources/issues/365
- Iframe-2: "run" button does nothing, "postmessage" button works (alert is displayed)

And here are new problems we found:

- 1) Tab key 
  - a) not working in Panel mode only (works in DialogMode), try clicking in input below and Tab key, on previous versions this goes to the next element (button or input)
- 2) Problems in hosted Iframe-2 only in both Panel and DialogMode.
    - a) Keyboard shortcuts: like Ctrl + a (select all), Ctrl + c (Copy), Ctrl + v (Paste) don't work, same for right click + copy or paste or cut <img width="224" alt="Screen Shot 2021-06-10 at 12 56 29" src="https://user-images.githubusercontent.com/1328733/121513585-4a8a3080-c9eb-11eb-940e-13cc5a5d5a31.png">
    - b) Hover: Mouse cursor doesn't change, see special div for testing below (works in Dialog Mode) 
    - c) Textarea: Mouse scroll doesn't work when text is multiline (add more text or press enter to add extra lines in textarea first, then try to scroll up or down)
	- d) Textarea, Caret: If you close the extension, restart Illustrator, open the extension then when clicking in the textarea the cursor caret doesn't appear, but if you switch to a browser window (or click outside the extension) and click again in textarea then the cursor appears consistently after.

Note: these problems are not present in Beta version 25.3 265@236190

---
Steps to use the extension:

Note: I didn't change the debug port for the extension. I changed the id and name to make it unique.

Unzip extension and place it in extensions folder, for macOS `~/Library/Application\ Support/Adobe/CEP/extensions/`

For debug, extension listens to
http://localhost:8405/

To host the iframe:
```
cd HOST_IFRAME/
npx serve -l 8887
```

Then open Illustrator Prerelease and open the extension from the menu.
[TestEvalscriptJolg42.zip](https://github.com/Adobe-CEP/CEP-Resources/files/6630672/TestEvalscriptJolg42.zip)

**Comment by Jolg42** [comment]
Note: Extension includes instructions and reproductions see 
<img width="839" alt="Screen Shot 2021-06-10 at 12 57 43" src="https://user-images.githubusercontent.com/1328733/121513800-8c1adb80-c9eb-11eb-8edf-8379d204a881.png">

Download link https://github.com/Adobe-CEP/CEP-Resources/files/6630672/TestEvalscriptJolg42.zip

**Comment by ghenania** [comment]
@rushilmahajan-adobe Any updates on this issue? It's critical for us and our users community.

**Comment by rushilmahajan-adobe** [comment]
Hi @ghenania 

About Issue-1 (Tabbing Issue in Panel):
In CEP Panel, we use custom CEP Tabbing(not provided by CEF) difference being in Panel we only focus (focusNext) on text or input area, while In Modal Dialog tabbing is control by Chromium - which focus(focusNext) on clickable iteam, 

The issue is caused when the extension's main page contains the Cross-site Iframes, with CEF'88  we cant access cross-sites Iframe objects/documents, and CEP Panel tabbing fails to initiate (cross-site Iframe throws null when our custom CEP tabbing looks for the area where it can focusNext with tab)

Workaround Solution - from our custom tabbing we ignore the cross-site Iframe and let tabbing work only on Main-Page (fix added in upcoming CEP release)

Chromium focus event on cross-site Iframe is broken for now, even in our Modal Dialog or CEF-Client where Chromium handles the tabbing - once focus(Tab) goes inside a Cross-Site iFrame then focus(tab) is not able to return at main-frame(page), We are looking for the Fix for all these Cross-Site Iframe issues.

**Comment by ghenania** [comment]
Thanks @rushilmahajan-adobe for this update.
So if I understand correctly, in our Extension, as the Cross-site Iframe fits the entire Panel, the upcoming CEP release should not fix our issue for now. Am I right?

And any updates on issue 2? Which is actually way more critical for us, to be honest. In particular 2b, 2c and 2a.

**Comment by rushilmahajan-adobe** [comment]
Hi @ghenania 

With the recent update of CEF in CEP **by default** the Full-page multi-frame layout is no longer synchronous, and the cross-site frames of a page are spread across multiple processes. Hence, we are not able to properly access the document or pass an event to Cross-Site Iframe.

You can add  `<Parameter>--disable-site-isolation-trials</Parameter>` tag in manifest, to disable the mulitple process creation for each cross site.

This will resolve the discrepancy between the versions of CEP for cross-site iframes, and all above issues seen(only in CEP-11) will also get resolved.

**Comment by ghenania** [comment]
Hey @rushilmahajan-adobe. Good news, it seems to fix all of our issues 🎉. We're going to run a full QA phase and keep you posted if we see anything else.

**Comment by ghenania** [comment]
@Jolg42 I think you can close this issue now.

**Comment by Jolg42** [comment]
👍 

Solution thanks to @rushilmahajan-adobe is to add `<Parameter>--disable-site-isolation-trials</Parameter>` to `CEFCommandLine` in the `manifest.xml`.

Example:
```diff
<CEFCommandLine>
+ <Parameter>--disable-site-isolation-trials</Parameter>
  <Parameter>--enable-nodejs</Parameter>
  <Parameter>--mixed-context</Parameter>
</CEFCommandLine>
```
