### ISSUE TITLE
wrong CSInterface.js?

### ISSUE THREAD

**Issue by mayzoon** [Adobe-CEP/CEP-Resources#368]
In https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_11.x there should be a new CSInterface.js but it still says v 10.0.0

**Comment by sujaisivanandan** [comment]
HI @mayzoon, thanks for pointing this one. Will fix the version string, however do note that there is no api change to CSInterface and this file should continue to work.

**Comment by sujaisivanandan** [comment]
The versions are updated. closing this tcket
