### ISSUE TITLE
CEP extension stopped to work due to CORS issue in AI 25.3/CEF 11

### ISSUE THREAD

**Issue by int255** [Adobe-CEP/CEP-Resources#372]
We have a CEP extension which uses iframe to display content hosted in remote website. We interact with the host view via javascript APIs, and the authentication relies on cross origin cookies.

After upgrading to AI 25.3, due to the strict CORS policy, our extension suddenly stopped to work because the API cannot be called for cross-origin, and the inner frame failed to do authentication via read/write cookie due the the cross origin limitation. 

The sudden change of the CORS policy is causing regression issue to CEP extension, many of our customer are already using it and starts to complain. Please consider to at least make CORS configurable e.g. in the CSXS manifest xml, or allow it to be configured in the Adobe Illustrator Application settings. This way at least there is a workaround for our customer.

**Comment by ghenania** [comment]
Hey @int255, Your suggestions are interesting. Meanwhile, we've had the same issue and we've used a workaround using messages posted between the iFrame and its parent. Check the issue  #365.

**Comment by sujaisivanandan** [comment]
@int255 CEF does not expose these as configurable options, therefore CEP cannot expose this as options in manifest. 
I understand that this needs work and change on the extension to fix this, but this will help the plugin ecosystem with better security and following the latest web standards.

**Comment by int255** [comment]
> 
> 
> Hey @int255, Your suggestions are interesting. Meanwhile, we've had the same issue and we've used a workaround using messages posted between the iFrame and its parent. Check the issue #365.

Thanks! indeed postMessage is a workable solution.

**Comment by sujaisivanandan** [comment]
@int255 updated the known issues - https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/Issues.md. Do close the ticket if you think this has been resolved.

**Comment by int255** [comment]
@sujaisivanandan Thanks! the flag --disable-site-isolation-trials is indeed helpful, with the flag enabled in the CSXS manifest.sml, the javascript API can be called across frames. :)

In our application we met another issue, that in the inner frame, the cookies (used for storing the session) cannot be save/loaded, due to the "SameSite" policy change of chromnium engine. But that is another issue, so this one can be closed.
