### ISSUE TITLE
When Photoshop and InDesign will get CEP 11?

### ISSUE THREAD

**Issue by malsabbagh** [Adobe-CEP/CEP-Resources#374]
It seems based on the latest changes with CEF v88 we have some extra security around iframes (based on this https://github.com/Adobe-CEP/CEP-Resources/issues/373). However, the workarounds that work in CEF v88 are not backward compatible with earlier CEF versions. The workarounds are based on this [document](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/Issues.md). So it will be important to update the rest of Adobe software to use the new CEP 11 update.

Was this not discussed when CEP 11 was released?

**Comment by malsabbagh** [comment]
I guess you have this [table here](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#applications-integrated-with-cep) to cover what is released versus not. What I am not sure about is why Adobe Illustrator was the only software to make the jump to CEP 11. I would hope that all would jump at the same time to avoid any backward compatibility  issues given CEF v88 was a major jump with breaking changes for extensions that are used in multiple Adobe software.

**Comment by malsabbagh** [comment]
Actually the backward compatibility issue might have been wrong. This seems to be working. It looks like with older CEF/CEP a custom `/etc/hosts` is not picked up.

So the priority of this question is lower now given it is working with CEP10.

**Comment by sujaisivanandan** [comment]
@malsabbagh Indesign will be releasing this month with CEP 11 and you can try out the pre-release versions that already has CEP 11.
Similarly we have Public Beta builds with CEP 11.1 for Premiere Pro, After Effects, Audition, and Media Encoder. 

Photoshop, Bridge and Dreamweaver do not have CEP 11 yet and would defnitely integrate and release with CEP 11 for the MAX releases.

**Comment by malsabbagh** [comment]
Thank you @sujaisivanandan

**Comment by ErinFinnegan** [comment]
I know this is closed, but wanted to comment that the CEP 11 rush to Illustrator was entirely to get a version of Illustrator running natively on Apple silicon.

I've made this chart of what's available now for a blog article: https://gist.github.com/ErinFinnegan/8f2e27b5e9e695dfc971441b72bf89d4#file-cep11roadmap-md
