### ISSUE TITLE
CEP11 unable to store cookie due to SameSite policy change

### ISSUE THREAD

**Issue by int255** [Adobe-CEP/CEP-Resources#376]
We have a CEP extension which renders web content inside frame. After upgrading to AI25.3/CEP 11, the authentication fails inside the inner frame. From the debug console it's caused by the default SameSite policy.

> Indicate whether a cookie is intended to be set in a cross-site context by specifying its SameSite attribute
> Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being set in a cross-site context. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.
> Resolve this issue by updating the attributes of the cookie:
> Specify SameSite=None and Secure if the cookie is intended to be set in cross-site contexts. Note that only cookies sent over HTTPS may use the Secure attribute.
> Specify SameSite=Strict or SameSite=Lax if the cookie should not be set by cross-site requests.
> 1 cookie
> Name	Domain & Path
> JSESSIONID	......

Is it possible to add additional flag to allow legacy cookie SameSite policy (default=None instead of Lax) during CEP extension start?

see "LegacySameSiteCookieBehaviorEnabled" and  "LegacySameSiteCookieBehaviorEnabledForDomainList"  policy settings of chrome.
[https://www.chromium.org/administrators/policy-list-3/cookie-legacy-samesite-policies](https://www.chromium.org/administrators/policy-list-3/cookie-legacy-samesite-policies)

**Comment by sujaisivanandan** [comment]
@int255 you can try with adding `--disable-features=SameSiteByDefaultCookies ` in the manifest. 

However please do note that this is a temporary workaround and may get disabled in CEF in a later update. This is also mentioned in the above link you have shared.

Note: The following commands in manifest recommended are interim workarounds
`--disable-features=SameSiteByDefaultCookies `
`--disable-site-isolation-trials`
You will need to work on addressing this at the earliest on the extension side since these may get removed by CEF in a future update. Then once CEP update to this new version in the future, these workarounds would cease to work.

**Comment by iAmao** [comment]
> @int255 you can try with adding `--disable-features=SameSiteByDefaultCookies ` in the manifest.
> 
> However please do note that this is a temporary workaround and may get disabled in CEF in a later update. This is also mentioned in the above link you have shared.
> 
> Note: The following commands in manifest recommended are interim workarounds
> `--disable-features=SameSiteByDefaultCookies `
> `--disable-site-isolation-trials`
> You will need to work on addressing this at the earliest on the extension side since these may get removed by CEF in a future update. Then once CEP update to this new version in the future, these workarounds would cease to work.

Is the `--disable-features` flag documented anywhere? I'm fairly new to developing extensions and I have a very hard time finding information

**Comment by sujaisivanandan** [comment]
Refer to 
https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/Issues.md . You can add command line flags similar to way mentioned in Issue-2

https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#migration-from-cep-10-to-cep-11
