### ISSUE TITLE
Reference manual?

### ISSUE THREAD

**Issue by tuomassa** [Adobe-CEP/CEP-Resources#377]
Where can I find some kind of reference manual to Bridge?

For example, there seems to be, maybe, an event called `selectionsChanged` but googling that, I find no official information, just some poorly formatted, incomplete, forum posts. Where can I actually get started?

Thanks!

**Comment by ErinFinnegan** [comment]
Hi there!

There are two answers. If you're building with CEP, here's a Bridge manual: [https://github.com/Adobe-CEP/CEP-Resources/blob/master/Documentation/Product%20specific%20Documentation/CEP_9_Extensions_Cookbook_Bridge.pdf ](https://github.com/Adobe-CEP/CEP-Resources/blob/master/Documentation/Product%20specific%20Documentation/CEP_9_Extensions_Cookbook_Bridge.pdf )

If you're building with C++ SDKs, the manual is [here](https://console.adobe.io/servicesandapis):

<img width="904" alt="Screen Shot 2021-07-23 at 11 09 38 AM" src="https://user-images.githubusercontent.com/2728504/126803000-2c824f03-ca10-4cb8-a31c-941808c2858d.png">

<img width="1502" alt="Screen Shot 2021-07-23 at 11 09 57 AM" src="https://user-images.githubusercontent.com/2728504/126803029-68fee853-f9e2-4934-95e2-1aab5dbc6160.png">

<img width="578" alt="Screen Shot 2021-07-23 at 11 11 04 AM" src="https://user-images.githubusercontent.com/2728504/126803060-3a9a1e12-2be2-4609-b843-87597ab2efbc.png">

Actually it looks like there are JavaScript references in there, too.

Bridge has no current plans to adopt UXP (at the time of this writing).
