### ISSUE TITLE
InDesign 16.3.1 panel rendering bugs (update stops completely, resizing performance)

### ISSUE THREAD

**Issue by jonasw-roxen** [Adobe-CEP/CEP-Resources#379]
We're fighting several issues when running InDesign 16.3.1 with our CEP-based panel. Some I have addressed myself with the helpful suggestions to use `--disable-site-isolation-trials` as well as the `SameSite="None"` cookie change, but others ranging from annoying to severe are still puzzling me. Here are two related to screen rendering that I'd appreciate some feedback on:

1. The most critical issue right now is that frequently the CEP panel content stops rendering any content at all. I'm attaching via the Chrome remote debugging socket and can see the process continue to run correctly, the DOM tree looks good, and sometimes even clicks in the panel generate the appropriate action, but _nothing_ is updated in the panel window. It's just blank. Closing and reopening the plugin panel brings back correct behavior for the time being (since the plugin process is reinitialized), but it might get stuck again later. One particularly peculiar version of this is that the (to the user) dead panel sometimes shows a static screenshot of what the panel looked like last time it worked, and then typically in 2x zoom! (This may be attributed to running a mix of normal and hi-dpi screens on my laptop, but the windows don't cross any screen boundaries, but it makes this bug even more weird.) Anything others have experienced, and any CEF disabling flags that could mitigate the problem? I would expect it's an internal Adobe/CEF issue where the rendering sub-process randomly disconnects from the main process.

2. Resizing of the CEP panel is visually very unpleasing until the rendering catches up. One can easily see this by opening Adobe's bundled "EPUB Interactivity Preview" panel (hit the Play button) which suffers from the same problem. Resizing either our own or Adobe's panel reveals black areas around the panel edges until the rendering is in sync again. Try e.g. a vertical resize where the window height slowly increases and you can see the _width_ of the whole embedded browser is getting narrower and then bouncing back again which looks totally unnecessary. I've got a screen capture of CC 2020 (left) and CC 2021 (right) here: https://drive.google.com/file/d/13ZJve6tQOcw94CS4tRIZmymYD8q22LB1/view?usp=sharing

I'm predominantly running macOS 11.3.1 on a MBP16 so these are not Apple Silicon-specific bugs. Thanks in advance!

**Comment by sujaisivanandan** [comment]
@jonasw-roxen can you send the extension for debugging or probably a stripped down plugin which repro's this?

**Comment by jonasw-roxen** [comment]
@sujaisivanandan Thank you for reaching out! I'd be happy to share details with you through direct contact since this is commercial software that I cannot post source code for publicly. I've arranged a test account on one of our servers and can forward login details. I couldn't find your e-mail address so please e-mail me on jonasw@roxen.com instead.

**Comment by sujaisivanandan** [comment]
Note: Fix with CEP 11.2 is now part of Illustrator 25.4 and InDesign 16.4. Will soon get integrated in other apps too.

**Comment by yuliazarkh** [comment]
Hello, we are experiencing same issues in our Premiere Pro panel that running on Windows. (Issue are reproducing in multiple Premiere versions - for example in Version 22.5.0 Build 62)

Are CEP 11.2 fixes included in Premiere Pro? I could not find any info about this fix. Thank you!
