### ISSUE TITLE
CEP6 DndCustomData url file inside InDesign

### ISSUE THREAD

**Issue by Joakk1** [Adobe-CEP/CEP-Resources#38]
The local file drag from the sample extension to InDesign is creating a text box containing the url string instead of importing the file itself.

dt.setData("url", currentPageUrl);
dt.setData("text/html", '<p>A link to a local file: <a href="../img/red.png">red.png</a></p>');
dt.setData("application/json", 'a json string');
dt.setData("custom type", 'custom data');

What is the required data type to pass to setData function ?

**Comment by yugguo** [comment]
Hello, you can set any type in setData function. However, each host application such as InDesign only accepts and handles some specific types which are defined in its own logic.
