### ISSUE TITLE
Extension Builder no longer available

### ISSUE THREAD

**Issue by hachigoro** [Adobe-CEP/CEP-Resources#381]
Hello, in multiple places in the documentation it references Extension Builder 3, with the following link: http://labs.adobe.com/technologies/extensionbuilder3/

This link has not worked for some time, and I understand that there is a different method to package and sign extensions. Could you update the documentation with the new method and removing references to Extension Builder?

Thanks!

**Comment by alexIV-0** [comment]
try to use this one
https://github.com/hyperbrew/bolt-cep

**Comment by ErinFinnegan** [comment]
Closing since I removed the references to Extension Buidler.
