### ISSUE TITLE
Any valid TSA?

### ISSUE THREAD

**Issue by willworkforhugs** [Adobe-CEP/CEP-Resources#385]
There's been a long history of TSAs going offline, causing problems for signing ZXPs. Even trying ones that worked a few months ago (per https://github.com/Adobe-CEP/CEP-Resources/issues/358), I'm getting errors from ZXPSignCmd ("
Error - cannot contact the chosen TSA. Please make sure the URL is valid and that you are connected to the internet.")

And if I try to ping **http://time.certum.pl**, I get errors. Though https://www.isitdownrightnow.com/time.certum.pl.html says the site is ok.

Working with commands along the lines of:
`ZXPSignCmd -sign ./com.myPanel.ext ./com.myPanel.ext.zxp ./selfCert.p12 XXXXXXX -tsa http://time.certum.pl`

Anyone else having luck at this point?

**Comment by sujaisivanandan** [comment]
@willworkforhugs can you comment on how you resolved this, as it would help others
