### ISSUE TITLE
ILST >= 25.4 / CEP11 cannot use the xmpSamplePanel structure for extension purpose on setup("ILST")

### ISSUE THREAD

**Issue by dfiorentin** [Adobe-CEP/CEP-Resources#393]
We've developed a plugin that uses the delegates described on https://github.com/Adobe-CEP/Samples/blob/master/XmpSamplePanel/jsx/XmpSamplePanel.jsx 

It works fine with Illustrator 2020 (24.3), but after updating to Illustrator 2021 (25.4) it doesn't work. It seems related to the CEP11 updates

In particular, when we call the CSInterface.evalScript($.XMP.setup("ILST"),<callback>) it returns a general error

`"Error 21: undefined is not an object. Line: 1 ->  $.XMP.setup("ILST")"`

It seems that $.XMP is undefined.

Does anyone have the same behavior? 

Thank you in advance.

**Comment by sujaisivanandan** [comment]
This is a product bug in Illustrator and is being tracked with [AI-4251096] and marked for the upcoming version.

**Comment by sujaisivanandan** [comment]
@dfiorentin the Illustrator 26.0 pre-release builds are available now on Creative Cloud - prerelease section. This has the fix for the issue - AI-4251096. Cann you please take a look.
