### ISSUE TITLE
CEP panel crashes in Photoshop (macOS) 22.5.1 and won't work on Windows

### ISSUE THREAD

**Issue by apiscode** [Adobe-CEP/CEP-Resources#399]
Hi

CEP panel crashes in Photoshop (macOS) 22.5.1
Below I posted log file from macOS. 

DevTools listening on ws://127.0.0.1:2330/devtools/browser/432ab61e-492a-497c-98a2-de3529ff54ab
2021-09-14 11:31:24:736 : ERROR ClientInitialized begin

**Comment by sujaisivanandan** [comment]
@apiscode can you share the crash logs from Mac Console for PhotoShop or CEPHtmlEngine if any?

**Comment by apiscode** [comment]
That's the logs from from mac. Logleve = 6

This is photoshop console:
Last login: Tue Sep 14 10:50:12 on ttys000
bkr@Barteks-iMac MacOS % ./Adobe\ Photoshop\ 2021 
2021-09-14 13:43:52.048 Adobe Photoshop 2021[6642:238838] Throttle bucket for current UUID is 4.000000
2021-09-14 13:43:52.050 Adobe Photoshop 2021[6642:238838] AdobeCrashReporterInitialize: executionTime = 0.016645 seconds
2021-09-14 13:43:52.078 AdobeCRDaemon[6643:238917] CR dialog Preference for force quit 1
Creating new log file at: /Users/bkr/Library/Logs/CreativeCloud/ACPLocalLogs/Adobe Photoshop 2021/ACPL__2021-09-14_11-43-53.555202Z_00.log
<4736118272> <DynamicLink> <5> Attempting to launch dynamiclinkmanager
<4736118272> <DynamicLink> <5> /Applications/Adobe Creative Cloud/Adobe Photoshop 2021/Adobe Photoshop 2021.app/Contents/MacOS/./DynamicLinkMediaServer/dynamiclinkmanager.app
<4736118272> <DynamicLink> <5> Increase wait time to 2
objc[6667]: Class HTTPHeader is implemented in both /Library/Application Support/Adobe/AdobeGCClient/AdobeGCClient.app/Contents/MacOS/AdobeGCClient (0x109e97e98) and /Library/Application Support/Adobe/AdobeGCClient/HDPIM.dylib (0x1147f4890). One of the two will be used. Which one is undefined.
objc[6667]: Class ProxyManager is implemented in both /Library/Application Support/Adobe/AdobeGCClient/AdobeGCClient.app/Contents/MacOS/AdobeGCClient (0x109e97ee8) and /Library/Application Support/Adobe/AdobeGCClient/HDPIM.dylib (0x1147f48e0). One of the two will be used. Which one is undefined.

**Comment by sujaisivanandan** [comment]
Since you saw a crash, can you check the mac console for any PhotoShop crashes.  MacOS console as shown below:

![Screenshot 2021-09-14 at 5 42 04 PM](https://user-images.githubusercontent.com/57343729/133255372-baa0a7e2-f863-49c0-a093-dbbf0ca5b11e.png)

**Comment by apiscode** [comment]
I removed few command line parameters and now it works. Still strange that it worked in InDesign and Illustrator but it was crashing CEP Panel inside Photoshop.
