### ISSUE TITLE
Debugging Node context on CEP 6.1

### ISSUE THREAD

**Issue by MattMcNam** [Adobe-CEP/CEP-Resources#40]
With the CEP 6.1 update, the Dev Tools only have access to the browser JS context. 
Errors from node are shown in the console, but setting breakpoints is difficult (files missing from the Scripts tab), and when they are triggered the console is actually still referencing the browser context, so I cannot interact with it.

Are there any recommendations for debugging the Node context in CEP 6.1?

Addendum: Was misreading the debugger, found Node files and can set breakpoints easily, still some strange results between highlighting variables when on a breakpoint vs what the console does.

**Comment by ReiMartins** [comment]
Hi, see this article
http://www.davidebarranca.com/2015/12/html-panel-tips-19-cc2015-1-cep6-1-node-js-fixes/

**Comment by MattMcNam** [comment]
After some re-architecting I've managed to set up a fairly good debugging environment; mainly just boiled down to code that was working around Node/CEF interaction quirks in CEP 6 that was now causing confusion for CEP 6.1.
