### ISSUE TITLE
CEP Plugin not loading in Indesign Server

### ISSUE THREAD

**Issue by rahul-dutt-sharma** [Adobe-CEP/CEP-Resources#407]
Is the Indesign server not supported?

**Comment by ErinFinnegan** [comment]
I'm not sure, but I'll ask around.

Meanwhile, which version of InDesign Server are you running, and on which OS?

Does your debug panel throw any errors when the plugin doesn't load?

**Comment by ErinFinnegan** [comment]
I got the answer: No, InDesign Server does not support CEP. There's no UI, so I'm not sure where your plugin would load (I guess it could be a plugin with no UI).

Please take a look at the InDesign Server SDK for more details on the extensibility points for IDS like scripting and plugins etc. You can download the Server SDK docs from https://developer.adobe.com/console/home - you have to search for InDesign. Also, you can't log in with an Enterprise account, you need to log in with a personal account.
