### ISSUE TITLE
Different rendering between inDesign and CEF

### ISSUE THREAD

**Issue by pekala** [Adobe-CEP/CEP-Resources#41]
According to [CEP wiki](https://github.com/Adobe-CEP/CEP-Resources/wiki/CEP-6-HTML-Extension-Cookbook-for-CC-2015#chromium-embedded-framework-cef) CEF 3, branch 1453, revision 1339 is used to run the extensions. However, when I try to run my extension in that version of CEF (from https://cefbuilds.com) it renders correctly and when I run it in inDesign I have problems with some of the simple flexbox features I used. What could be the reason? Is there any way to get the same results outside of inDesign?

**Comment by codearoni** [comment]
Throw a .debug file into your project and see what shows up in the console: http://www.davidebarranca.com/2014/01/html-panels-tips-1-debugging/

I've encountered some strange irregularities with extensions, and debugging in the localhost typically gives you good insight into what is going on.

**Comment by pekala** [comment]
It turned out to be the way I authored my CSS (I used nesting PostCSS pluging). Removing that resolved the differences. It's really strange because after the processing it was still valid CSS, essentially the same as without the plugin. I didn't investigate more though.
