### ISSUE TITLE
The CEP 11 AipHostAdapter.aip does not work with Illustrator 2022

### ISSUE THREAD

**Issue by rahul-dutt-sharma** [Adobe-CEP/CEP-Resources#416]
Hey,

Can we get a compatible aip file?

Regards

**Comment by ErinFinnegan** [comment]
Do you mean this one doesn’t work? https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_11.x/AIHostAdapter

**Comment by rahul-dutt-sharma** [comment]
Yes

**Comment by ErinFinnegan** [comment]
Hi @rahul-dutt-sharma, 

I've reached out to the Illustrator Desktop PM... just to clarify, are you talking about Illustrator 26.0.1? Have you tried it in the Illustrator Beta (26.1) or the Prerelease build (26.0.2)?

Also, I think the last release ought to be compatible with Mac M1 processors, but do let us know if it works in Rosetta mode or fails to work...

**Comment by untoldbyte** [comment]
@ErinFinnegan for 26.x.x the 11.x aip is not working. On any platform.

Do we have an updated Aip file?

**Comment by ErinFinnegan** [comment]
Hi @untoldbyte,

My colleague says the last adapter should still work. What error(s) are you seeing?

**Comment by untoldbyte** [comment]
The events are not working

**Comment by ErinFinnegan** [comment]
Can you provide a few steps to reproduce this?

**Comment by rahul-dutt-sharma** [comment]
@ErinFinnegan One more thing the CEP11 folder has aip file only for mac but not for windows like in 9.x https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_9.x/Host%20adapters/Illustrator/AIHostAdapter/Win/Release/AIHostAdapter.aip

**Comment by ErinFinnegan** [comment]
I think this is because the prior Windows build should still work. A new build was only needed for macOS M1 devices.

**Comment by untoldbyte** [comment]
we tried and it did not work

**Comment by ErinFinnegan** [comment]
Did you get an error?

Also... could someone provide a test case? I'm really not familiar with using the Hostadapter.

**Comment by rahul-dutt-sharma** [comment]
@ErinFinnegan Closing the ticket as the problem was with our code. Kindly accept our apologies.
