### ISSUE TITLE
The cep11 html iframe's mouse cursor CSS property  not work in Premiere 15.4.1 on Mac

### ISSUE THREAD

**Issue by inkn** [Adobe-CEP/CEP-Resources#417]
i use premiere15.4.1 on Mac，my plugin's html iframe's mouse cursor CSS property  not work 

html example: 
```html
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <title>eg</title>
</head>
<body onload="onLoaded()" style="background-color:rgb(35,35,35) !important">
	<iframe src="https://www.google.com" width="500" height="500"></iframe>
</body>
</html>
```
when i mouse hover a button in  iframe page, the mouse not change to pointer.

**Comment by rushilmahajan-adobe** [comment]
Hi @inkn 
you can try adding `<Parameter>--disable-site-isolation-trials</Parameter>` in you CSXS Manifest file, this will resolve you cursor hover issue inside Iframe.

For more details you can follow: https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/Issues.md#issue-2-cep-11-ui-issues-with-cross-site-iframes

**Comment by inkn** [comment]
> Hi @inkn you can try adding `<Parameter>--disable-site-isolation-trials</Parameter>` in you CSXS Manifest file, this will resolve you cursor hover issue inside Iframe.
> 
> For more details you can follow: https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/Issues.md#issue-2-cep-11-ui-issues-with-cross-site-iframes

thank u, it's ok !

**Comment by sujaisivanandan** [comment]
@inkn as mentioned in the documentation, disabling site isolation is only a workaround and can be removed in CEF in future releases. Would recommend if you can plan and handle cross site access as per the web standards so that this flag is not required to be used by the CEP extension.
