### ISSUE TITLE
Extensions don't load on startup

### ISSUE THREAD

**Issue by yaffol** [Adobe-CEP/CEP-Resources#42]
I'm porting an extension from purely Extendscript and Bridgetalk to an HTML5 panel and Vulcan.js. The extension uses InDesign to export a PDF, which is then rasterised by Photoshop (in a separate extension listening for Vulcan messages in PS). All apps are CC 2015 on Windows 7 64.

I've been struggling to get the extension to load on startup in Photoshop. It's set to load on the appActivate event:

```
        <Lifecycle>
            <AutoVisible>true</AutoVisible>
            <StartOn>
                <Event>applicationActivate</Event>
            </StartOn>
        </Lifecycle>
```

But when I start Photoshop, either manually (clicking on the menu item on the start menu) or via

`VulcanInterface.launchApp("photoshop",true);`

or via a old-school Bridgetalk message,

```
var wakeUpPhotoshop = function() {
    var bt = new BridgeTalk();
    bt.target = "photoshop";
    bt.body = "app.bringToFront();";
    bt.send();
}
```

the extension doesn't actually load until I physically click somewhere on the Photoshop window.

I also tried connecting to Photoshop with Extendscript Toolkit CC, to see if I could issue a command which would cause the application to emit it's activate event, and the act of connecting to PS with ETK also caused the extension to load.

I may have missunderstood the time that the appActivate event is fired, but I'm currently struggling to find a way to get an extension in one program to successfully launch and be able to target a message to an extension in another program. I've also tried listing to the documentAfterActivate event in PS and use Bridgetalk (which does get through) to open a document in PS - the document opens, but the extension doesn't load until I physically click on the PS window.

I tested the behaviour with the [Adobe CEP Samples Invisible HTML extension](https://github.com/Adobe-CEP/Samples/tree/master/CEP_HTML_Invisible_Extension) and got the same results - the response from the node.js http server in the Invisible HTML Extension is only available once I click somewhere on the Photoshop window.

**Comment by yugguo** [comment]
Hello, it is host application such as Photoshop that decides when to emit applicationActivate event.

**Comment by shamshoum** [comment]
What you need to do is use the "com.adobe.csxs.events.AppOnline" event and not the "applicationactivate". You can see more info about this in this [site](http://www.davidebarranca.com/2014/07/html-panels-tips-12-cep-application-events/).
