### ISSUE TITLE
MacOS Monterey

### ISSUE THREAD

**Issue by genesst** [Adobe-CEP/CEP-Resources#429]
How do I install ExtendScript Toolkit on MacOS Monterey?

It shows the following after hitting Install.app in mounted dmg:
`“Install.app” needs to be updated.`

**Comment by sir-editor** [comment]
ExtendScript Toolkit is not supported on macOS starting Mojave version (10.15)
You should install [VS Code](https://code.visualstudio.com) and add [ExtendScript Debugger v1.1.2](https://marketplace.visualstudio.com/items?itemName=Adobe.extendscript-debug) extension there.

Also, if you are a member of the prerelease group you can download v2 beta version (if I'm right it is not available anywhere else): https://community.adobe.com/t5/exchange-discussions/extendscript-debugger-2-0-news/td-p/12477923
