### ISSUE TITLE
Need to a way to have title for the extension but hiding from the window->extensions menu

### ISSUE THREAD

**Issue by zhangusc** [Adobe-CEP/CEP-Resources#43]
Currently, the manifest.xml supports extension title through Menu. But this also shows the extension in application's window->extensions menu. There is no way for a user to have a titled extension but not showing from the menu.

**Comment by Klustre** [comment]
How about setWindowTitle? Also works on panels in After Effects…

```javascript
/**
 * Set the title of the extension window. 
 * This function works with modal and modeless extensions in all Adobe products, 
 * and panel extensions in Photoshop, InDesign, InCopy, Illustrator, Flash Pro
 * and Dreamweaver.
 *
 * Since 6.1.0
 *
 * @param title The window title.
 */
CSInterface.prototype.setWindowTitle = function(title)
{
    window.__adobe_cep__.invokeSync("setWindowTitle", title);
};
```

**Comment by zhangusc** [comment]
@Klustre Thank you. It works

**Comment by rpnainwal** [comment]
Thank you :)

**Comment by zhangusc** [comment]
setWindowTitle does reset the window title but the user experience is not good. When you open an extension, you will see the extension window first takes the title from manifest.xml Menu item and then after a second update the window title to the one set by setWindowTitle. I think CEP needs to provide a window title solution at manifest level so that the title get set at the time extension starts.

**Comment by zhangusc** [comment]
@sujaisivanandan could you update the community the reason for closing the issue, fixed, not in the plan, as design, etc.?
