### ISSUE TITLE
AE markerProperty Issue

### ISSUE THREAD

**Issue by cameronjeffords** [Adobe-CEP/CEP-Resources#430]
Has anyone noticed an issue using `composition.markerProperty.setValueAtTime(...)`? This was working until one of the latest updates (22.1). 

The call is failing with `After Effects error: CSelectronASSERT fail: CSelectron: layer is null`. Wanted to see if this was just an issue on my end, or a potential bug in the latest release?

**Comment by ErinFinnegan** [comment]
You should probably [ask in this forum](https://community.adobe.com/t5/after-effects/ct-p/ct-after-effects?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions&topics=label-scripting) to see if other people are facing the same issue.

**Comment by cameronjeffords** [comment]
Will do - thanks!
