### ISSUE TITLE
CEP 9.0 does not allow cookie with sameSite=None

### ISSUE THREAD

**Issue by emmanuelpineda** [Adobe-CEP/CEP-Resources#438]
CEP 9.0 (Chormium Version: 61.0.3163.91) does not allow the creation of cookies sameSite=None and Secure. For some reason this started happening from April 25th previously it was working fine. I'm not sure if this error is due to an update to Adobe Photoshop. 

The cookies sameSite=Strict or sameSite=Lax are allowed, but I require it to be sameSite=None as I am using oidc client js to authenticate with an identity server. 

Thank you in advanced.

**Comment by sujaisivanandan** [comment]
CEP 9 does not support samesite cookies and this feature support got introduced in CEP 10 and better.

Note: as per a [temporary workaround](https://www.chromium.org/administrators/policy-list-3/cookie-legacy-samesite-policies) provided by CEF, the following option can be added in manifest --disable-features=SameSiteByDefaultCookies.
