### ISSUE TITLE
CSInterface's closeExtension() not working

### ISSUE THREAD

**Issue by carlosconnected** [Adobe-CEP/CEP-Resources#445]
I'm on CEP 11 (<RequiredRuntime Name="CSXS" Version="11.0" />) and the closeExtension() function on Mac 12.4 (Intel CPU) is not working at all. When I call it from an extension, the extension does not get close. Does the Version attribute in the Extension tag has anything to do with it?

Please shed some light as I cannot deliver my extension project without having this functionality.

**Comment by ErinFinnegan** [comment]
HI @carlos-peru; which app or apps does your extension run in? 

This repo isn't the greatest place to get answers... depending on the host app there are better forums to ask this in.

**Comment by carlos-peru** [comment]
Hi @ErinFinnegan, it's an extension (or a group of extensions rather) running on Illustrator. Below a snippet of my manifest. Is there a forum that you would suggest a forum?

`<?xml version="1.0" encoding="UTF-8"?>
<ExtensionManifest ... Version="10.0">
...
<ExecutionEnvironment>
      <HostList>
         <Host Name="ILST" Version="25.3" />
      </HostList>
      <LocaleList>
         <Locale Code="All" />
      </LocaleList>
      <RequiredRuntime Name="CSXS" Version="11.0" />
</ExecutionEnvironment>
...
</ExtensionManifest>
`

**Comment by kareemmyk** [comment]
@carlos-peru .... 
With CEP v11.5.2.130 on Illustrator and InDesign i see it working on mac 12.4 intel chipset.
Can you share your extension and manifest.xml.

Below is a sample html and manifest.xml snippet I have used to test it

**index.html**
```
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<script type="text/javascript" src="../js/CSInterface.js"></script>
<script type="text/javascript">
    function onclickCloseMe()
    {
        CSLibrary.closeExtension();
    }
</script>
</head>
<body>
 <input type="button" name="Close this extension" id="CloseMe" value="Close this extension" onclick="onclickCloseMe()" />
</body>
</html>
```
**manifest.xml**
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ExtensionManifest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ExtensionBundleId="com.adobe.CEPHTMLTEST" ExtensionBundleVersion="1.0" Version="11.0"> <!-- MAJOR-VERSION-UPDATE-MARKER -->
    <ExtensionList>
        <Extension Id="com.adobe.CEPHTMLTEST.Panel1" Version="11.0.0"/>
    </ExtensionList>
    <ExecutionEnvironment>
        <HostList>
            <Host Name="IDSN" Version="11.0"/>
            <Host Name="ILST" Version="19.0"/>
        </HostList>
        <LocaleList>
            <Locale Code="All"/>
        </LocaleList>
        <RequiredRuntimeList>
            <RequiredRuntime Name="CSXS" Version="11.0"/> <!-- MAJOR-VERSION-UPDATE-MARKER -->
        </RequiredRuntimeList>
    </ExecutionEnvironment>
    <DispatchInfoList>
        <Extension Id="com.adobe.CEPHTMLTEST.Panel1">
            <DispatchInfo>
                <Resources>
                    <MainPath>./html/index.html</MainPath>
					<ScriptPath>./jsx/core.jsx</ScriptPath>
                    <CEFCommandLine>
                        <Parameter>--enable-speech-input</Parameter>
						<Parameter>--enable-media-stream</Parameter>
                        <Parameter>--enable-nodejs</Parameter>
                        <Parameter>--mixed-context</Parameter>
                    </CEFCommandLine>
                </Resources>
                <Lifecycle>
                    <AutoVisible>true</AutoVisible>
                </Lifecycle>
                <UI>
                    <Type>Panel</Type>
                    <Menu>CEP HTML Test Panel 1</Menu>
                    <Geometry>
                        <Size>
                            <Height>580</Height>
                            <Width>1020</Width>
                        </Size>
                        <MaxSize>
                            <Height>800</Height>
                            <Width>1200</Width>
                        </MaxSize>
                        <MinSize>
                            <Height>400</Height>
                            <Width>600</Width>
                        </MinSize>
                    </Geometry>
                    <Icons>
                        <Icon Type="Normal">./TeEx_HTML_TEST_23x23_N.png</Icon>
                        <Icon Type="RollOver">./TeEx_HTML_TEST_23x23_R.png</Icon>
                        <Icon Type="DarkNormal">./TeEx_HTML_TEST_23x23_DN.png</Icon>
                        <Icon Type="DarkRollOver">./TeEx_HTML_TEST_23x23_DR.png</Icon>
                    </Icons>
                </UI>
            </DispatchInfo>
        </Extension>
        </DispatchInfoList>
</ExtensionManifest>
```

**Comment by carlos-peru** [comment]
Problem was resolved. There was a conflict between a local close function and the window.close function.

**Comment by ErinFinnegan** [comment]
> Is there a forum that you would suggest a forum?

Yes! Illustrator discussions usually take place under the SDK or Scripting tags: https://community.adobe.com/t5/illustrator/ct-p/ct-illustrator?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions&topics=label-scripting 

https://community.adobe.com/t5/illustrator/ct-p/ct-illustrator?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions&topics=label-sdk
