### ISSUE TITLE
How to use ZXPSIGNCMD to sign a ZXP file with comodo certificate

### ISSUE THREAD

**Issue by vivoilpazzo2** [Adobe-CEP/CEP-Resources#450]
Dear all,

I would like to use our custom comodo code signing certificate instead of the self-signed certificate (.p12), to sign an after-effects ZXP file.
Is there any way to do so?

Thank you very much

**Comment by ErinFinnegan** [comment]
You can absolutely use a certificate. Here's our guide: https://github.com/Adobe-CEP/Getting-Started-guides/tree/master/Package%20Distribute%20Install
