### ISSUE TITLE
PProPanel doesn't pop up in Premiere 2022

### ISSUE THREAD

**Issue by friendlygiraffe** [Adobe-CEP/CEP-Resources#451]
When selecting Window>Extentions>PProPanel nothing pops up
It works in 2020 and 2021
I'm using a mac with Premiere 22.4.0

**Comment by ErinFinnegan** [comment]
Shouldn't this issue then be in [the repo for the PProPanel sample](https://github.com/Adobe-CEP/Samples/issues)? 

Nevertheless, tagging @bbb999

**Comment by friendlygiraffe** [comment]
Another strange thing I've noticed, I experimented with other Extensions that worked in 2022, and by editing any of the files index.html, manifest.xml etc.. it stops working. However if you undo and restore the file to its original it works again. 

This is odd, because the file-encoding and everything is exactly the same. Even if you add a new line or space somewhere it stops working.

**Comment by sujaisivanandan** [comment]
@friendlygiraffe Is this happening only for the sample plugin or any other?
Also are you noticing that this issue happens only when you edit the installed plugins?

**Comment by friendlygiraffe** [comment]
@sujaisivanandan I found the solution which I previously overlooked in the docs: https://github.com/Adobe-CEP/Samples/tree/master/PProPanel#2-enable-loading-of-unsigned-panels

Just needed `defaults write /Users/<username>/Library/Preferences/com.adobe.CSXS.11.plist PlayerDebugMode 1`

And now it works, thanks
