### ISSUE TITLE
ZXPSignCMD stopped working (TSA)

### ISSUE THREAD

**Issue by speedgeil** [Adobe-CEP/CEP-Resources#456]
I can no longer sign my extensions.

`Error - the timestamp returned from the chosen TSA could not be verified, so the ZXP created is likely to be rejected by other tools. Please recreate your ZXP with a different trusted TSA.`

I tried various Adobe trusted tsa servers. Many of them throw the error above, while with others, ZXPSignCMD will silently quit without further stdout And it won't write the .zxp package then. But it will create a "Meta-Inf" folder in my plugin folder. It contains an empty signature.xml. In the root of my plugin folder i will find a mimetype file. But as said, no .zxp will be generated.

Tried on Win 10 and 11 with latest ZXPSignCMD version in cmd (not Powershell) with admin rights.
I probably signed extensions a hundred times. So the chance of user error might be quite small. I'm sure i didn't mess anything up.

Any suggestions?

**Comment by speedgeil** [comment]
Solved. TSA http://timestamp.digicert.com works (but will only work for signing on local hard drive c:)

**Comment by speedgeil** [comment]
Had to re-open the issue because the successfully signed extension won't run after installation. Triple checked everything.
So something definitely is wrong at this point.

**Comment by ErinFinnegan** [comment]
If you were able to sign but then there's an error - particularly about the signature being corrupt or something similar, it's often the fault of some node.js file causing havoc, or another invisible file making some change after signing but before installation.

**Comment by rainierraydan** [comment]
Same Error. Have anyone solve this? :(

**Comment by mindlid** [comment]
Make sure you are including both `META-INF` and `mimetype`
![image](https://user-images.githubusercontent.com/19735362/185721840-d6103f19-024b-4a8e-af26-c3c853980c51.png)
otherwise [enable the debug flag
](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#debugging-unsigned-extensions)

**Comment by ErinFinnegan** [comment]
What error are you getting and how are you trying to install?

You could try signing and installing the sample panel to see if your code is causing it or if it’s ZXPSign…

**Comment by rainierraydan** [comment]
Hi!
As @speedgeil said, It was the TSA server but I din't know how to change it.
I got it fixed.
Thanks!

**Comment by ErinFinnegan** [comment]
Oh - that seems like a different issue, in that case.

What error code do you get? And again, how are you installing it? Some ZXP installer tools are deprecated, that’s why I’m asking.

You can reach out to wwds@adobe.com and they’ll ask you to share the extension.

**Comment by speedgeil** [comment]
Hi Erin, the host application is BR. BR won't throw any error. Instead it will show the Extension in the windows menu but will just not start it when clicking on it.
Installation is in this case manually. Simply by unzipping the zxp file into place.

**Comment by ErinFinnegan** [comment]
I'd check to make sure that your manifest works with the correct version of Bridge, [see this chart](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#applications-integrated-with-cep).

Also consider asking in the [Bridge forums](https://community.adobe.com/t5/bridge/bd-p/bridge?topics=label-scripting) or the [Bridge prerelease forums](https://forums.adobeprerelease.com/bridgepr/categories/general).

I also strongly encourage you to email wwds@adobe.com

**Comment by speedgeil** [comment]
Hi Erin, thanks for your support.
Actually i only made small js changes to a properly working and signed extension. CSXS is fine and everything. I got no clue but i'll figure it out.
