### ISSUE TITLE
ZXPSignCMD usage manua url is down

### ISSUE THREAD

**Issue by mindlid** [Adobe-CEP/CEP-Resources#457]
![image](https://user-images.githubusercontent.com/19735362/185685620-147dd08c-d467-4ec0-9e24-84f35050f5a3.png)
![image](https://user-images.githubusercontent.com/19735362/185685926-ea02124e-4302-448a-ab83-a578fe2a92ee.png)

**Comment by ErinFinnegan** [comment]
Sorry which page is that on? 

You can download ZXP from here: https://github.com/Adobe-CEP/CEP-Resources/tree/master/ZXPSignCMD

**Comment by mindlid** [comment]
it's on this repo the readme, i meant the url of the pdf manual for ZXPSingCMD

**Comment by ErinFinnegan** [comment]
OK, I found it and uploaded it here: https://github.com/Adobe-CEP/CEP-Resources/blob/master/ZXPSignCMD/SigningTechNote_CC.pdf 

However, please note that much of the same content is in this guide: https://github.com/Adobe-CEP/Getting-Started-guides/tree/master/Package%20Distribute%20Install 

I'll put in a PR to change the link in the readme as well...

Please note that in that PDF, the GUI "Extension Manager" was deprecated years ago, only ZXPSignCmd remains.
