### ISSUE TITLE
How can changing Keyframe Time?

### ISSUE THREAD

**Issue by miladghiravani** [Adobe-CEP/CEP-Resources#458]
How can I change the time of one or some keyframes?

For example like this:

`thisLayer.content(1).content("Stroke 1").property("Line Cap").setTimeAtKey(keyIndex , newTime)`

**Comment by ErinFinnegan** [comment]
Hi there!

Which app are you trying to set keyframes in? Photoshop? After Effects? Animate? Premiere?

In any case this isn't the right place to ask... you should ask in the forums:

- [After Effects](https://community.adobe.com/t5/after-effects/bd-p/after-effects?topics=label-scripting)
- [Animate](https://community.adobe.com/t5/animate/bd-p/animate?topics=label-code)
- [Photoshop](https://forums.creativeclouddeveloper.com/c/photoshop/63)
- [Premiere Pro](https://community.adobe.com/t5/premiere-pro/bd-p/premiere-pro?topics=label-sdk)
