### ISSUE TITLE
Is it possible to drag/drop an image from plugin to working area in Adobe InDesign?

### ISSUE THREAD

**Issue by oshoferyuk** [Adobe-CEP/CEP-Resources#462]
Hello guys,
I found out that html links with certain configuration are possible to drag from plugin to working area as a text.
What I basically tried to remove TextFrame after dropping it and placing image instead.
It works, but it is not looking good, because while dragging it, it is showing text instead of picture.

**Does anybody know is it possible (and how) to D/D an image from plugin, like you would normally do from File Explorer to Adobe InDesign?**

![dragText2](https://user-images.githubusercontent.com/11537369/187388037-0b622822-1fee-498c-a0f7-48663ce3bdeb.png)
While dragging text..

 
![dragText](https://user-images.githubusercontent.com/11537369/187386095-80aa22a5-4eb0-44f9-931c-efa098941c78.png)
Result of dragging text is Text within TextFrame.

If somebody is interested in my work around, it is below.
`1. In plugin html, set attribute to a href:
<a [myRouterLink]>draggable text</a>

Angular MyRouterLink should set routerLink property, like this.routerLink = "draggable text"

Now the link is draggable from plugin to Adobe Indesign as a plain text and would create TextFrame.

2. Listening 'afterSelectionChanged' event, removing TextFrame and placing picture.

    app.addEventListener(
      'afterSelectionChanged',
      event => {
        const selection = event.target.selection[0];
        if (selection instanceof TextFrame ) {
          event.target.selection[0].remove();
          app.activeDocument.place(fileRef, false, null); // placing picture instead
      },
      false,
    );
`

**Comment by ErinFinnegan** [comment]
Hi @oshoferyuk!

This isn't the best place to ask InDesign-specific "is this possible?" questions. If you haven't already done so, please feel free to repost this in the InDesign forum here: https://community.adobe.com/t5/indesign/ct-p/ct-indesign?page=1&sort=latest_replies&lang=all&tabid=all&topics=label-scripting <- This forum is quite active.

Or ask in this Slack community (not run by Adobe, but with many InDesign developers): https://join.slack.com/t/adobedevs/shared_invite/zt-19h1o8jog-gUW79Ze8oW0rjtlXThFA9A
