### ISSUE TITLE
Clarification on what the difference is between the CEP versions indicated in the manifest.xml

### ISSUE THREAD

**Issue by SamuelCharpentier** [Adobe-CEP/CEP-Resources#466]
Specifically, I would like to understand better what the difference between ExtensionManifest Version and the RequiredRuntime CSXS version.

I understand that the RequiredRuntime can be indicated as a RangedVersion but how could that even work? 

If the ExtensionManifest version="11.0", how could RequiredRuntime Name="CSXS" Version="[2.0, 8.0]" make any sens? Are all CEP versions are available in the latest versions of all of Adobe's softwares? Are they loaded based on the RequiredRuntime's highest available CEP, lowest available CEP or the Manifest version? how does this affect the way the extension get to run or not run? 

Why are they both relaying the same information, the extension engine version, yet have completely different names?

It seems like an ovely complex and seem to have little to no effect nad I can't find any documentation clarifying this.

**Comment by ErinFinnegan** [comment]
I don't think you can specify a range of CSXS versions, I think you can only have a range for product versions... ?

🤔 I suspect there may have been a time where the CSXS and ExtensionManifest versions didn't match.

Otherwise, it's a question for @sujaisivanandan

**Comment by manishkrmishra** [comment]
@SamuelCharpentier @ErinFinnegan @sujaisivanandan 
The ExtensionManifest version dictate the parser version to be used for the manifest.xml validation. This, generally is updated & follows every new **major release version** of CEP. [ExtensionManifest Version = "CEP Major Release Version"]

The RequiredRuntime version dictates the the version of CEP you want to build your plugin with (should be CEP Major version number shipped with host app). It should be a single value as there would be just one version of CEP shipped with host application.

**_For simplicity you can use the same version for RequiredRuntime & ExtensionManifest tags. RequiredRuntime should be determined by what CEP Version the host app comes with_** 

Please refer - https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#important-manifest-change-for-cep-50-extensions

**Comment by ErinFinnegan** [comment]
Thanks, @manishkrmishra !
