### ISSUE TITLE
Bug : Copy Paste not working on Illustrator v19.2.0

### ISSUE THREAD

**Issue by Jolg42** [Adobe-CEP/CEP-Resources#47]
Hi,

We have some feedback from our users regarding the copy-paste in HTML5 extensions which randomly perfoms in text input / textarea, while everything was working on our dev machines (MacbookPro Yosemite / El Capitan).
We were able to reproduce this bug by ourselves in Illustrator 19.2.0 and it's not only affecting copy paste but the others shortcuts as well (Cmd-C/V/A/X).
This behaviour is erratic, it won't work at first but if you try to copy-paste many times you can be able to do so at some point…

**Comment by Jolg42** [comment]
ping @arthurwei1975 Are you aware of this issue ?

**Comment by xiaoyi-tong** [comment]
Hi Jolg42,

I could not reproduce this issue in Illustrator 19.2.0 on my mac 10.11. Could you give me the detailed steps to reproduce it?

**Comment by Jolg42** [comment]
Hi @xiaoyi-tong :)

The issue happened in an html input, our users had to paste a 35 chars license key ([A-Z,0-9,-] like D8D499C1-DD4C473B-B72A4CDF-D8D499C1).

The issue occurred randomly, we were able to reproduce it after many attempts by reloading the extension with `window.location.reload(1)`. And when we reproduced it, every keyboard shortcuts weren't working (Cmd-C/V/A/X).

And if you're reloading it a few more times the keyboards shortcuts are working again. It looks like random lost events.

**Comment by lyip1992** [comment]
Hi @Jolg42,

I followed your steps to reproduce the issue inside one of our test panels and couldn't reproduce the issue in Illustrator 19.2.1 on OS X 10.11.3. I. Do you think you could reproduce the issue in a screencast? I would like to see if this might be a extension specific issue. Thanks!
