### ISSUE TITLE
Which CEP version ships in Illustrator 2023?

### ISSUE THREAD

**Issue by mcetkovsky** [Adobe-CEP/CEP-Resources#475]
The newest CEP version in this repository is CEP 11. The [Extension Cookbook](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md) says that CEP 11 runs on node.js 15.x. As node.js 15 is [out of support since 06/2021](https://github.com/nodejs/release#end-of-life-releases), I doubt that the docs page is up to date.

We're preparing UI of our plug-in for Illustrator 2023, so we would welcome current state of the technology stack we will depend on:
* Are the versions on the docs page still up to date?
* If not...
   * Which CEP version ships with Illustrator 2023?
   * What major version of node.js is used in Illustrator 2023?
   * What version of Chromium is used in Illustrator 2023?
   * How/where can we find up-to-date information regarding versions used?

**Comment by ErinFinnegan** [comment]
Hi @mcetkovsky,

I can see where this may be the cause of some confusion. I'm asking the engineering teams to clarify at the moment, but what I can tell you is this: Illustrator 2023, v. 27.0.1 does not have CEP 12 in it yet, as CEP 12 is still in the process of being picked up by different product teams.

I think it's on CEP 11.5, but I'm waiting to hear back. All the [Chromium and Node information in this chart](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#chromium-embedded-framework-cef) should still be true. 

I checked this by looking at the version information of the following file:

`/Applications/Adobe Illustrator 2023/Adobe Illustrator.app/Contents/MacOS/CEPHtmlEngine/CEPHtmlEngine.app`

This repo is generally kept up-to-date with releases. You might also ask in the Illustrator prerelease or beta forums.

**Comment by ErinFinnegan** [comment]
Ah-hah!

There's a PR for an update: https://github.com/kareemmyk/CEP-Resources/blob/patch-2/CEP_12.x/Documentation/CEP%2012%20HTML%20Extension%20Cookbook.md 

The current release of Illustrator is 2023, v. 27.0.1, which is still on CEP 11.

Whichever version of Illustrator picks up CEP 12 will have:

> What major version of node.js?
Node.js 17.7.1

> What version of Chromium?
99

> How/where can we find up-to-date information regarding versions used?
In this repo: https://github.com/Adobe-CEP/CEP-Resources 

You can also [sign up for the Creative Cloud Developer newsletter](https://www.adobe.com/subscription/ccdevnewsletter.html), where my team will include CEP 12 announcements, or keep an eye on [the Creative Cloud tag](https://blog.developer.adobe.com/tagged/adobe-creative-cloud) of the Adobe Tech Blog.
