### ISSUE TITLE
CEP HTML Engine on Win 10: 6 Process?

### ISSUE THREAD

**Issue by ADukal** [Adobe-CEP/CEP-Resources#49]
![CEP HTML Engine 6 Process](https://4.bp.blogspot.com/-1iZIKVpptBI/Vtp7qb_HxPI/AAAAAAAAJeE/303T-_2SB08/s1600/CEP_HTML_Engine_Process.jpg)

I'm not sure if this is an Issue related to the CEP Html engine, if there's something wrong with the only HTML extension that I have opened or just normal behaviour. I'm using Win 10 and PS CC2015 (updated), in other machine with Win 7 I see the same thing.

Thx in advance!

**Comment by lyip1992** [comment]
Hi @ADukal, multiple instances of CEPHtmlEngine is expected behavior. Photoshop launches their own CEP extensions on startup, one of them being the hello extension for opening new files. Let me know if this answers your question.

**Comment by ADukal** [comment]
Many Thanks Leon.
Question answered!

**Comment by lyip1992** [comment]
Glad I was able to help =].

**Comment by Deoinbox** [comment]
Windows: Access 
**%USERPROFILE%\AppData\Local\Adobe\Creative Cloud Libraries\Logs**
from the search field in the Start Menu or from the Run command
Confirm that the folder exists and you have write permissions for it.  

If don't have or can't access "**Logs**" folder create it with same above path and set folder write permissions.
