### ISSUE TITLE
Incorrect Version?

### ISSUE THREAD

**Issue by chadsaun** [Adobe-CEP/CEP-Resources#523]
https://github.com/Adobe-CEP/CEP-Resources/blob/23ed55e453948b2ba36bb1eb7a948a92e7887d53/CEP_12.x/CSInterface.js#L14

Is this file version 10 or 12? The comment says 10, but this file is under `CEP_12.x/`.

**Comment by ErinFinnegan** [comment]
@inchakra What do you think?

**Comment by ErinFinnegan** [comment]
We fixed it!
