### ISSUE TITLE
applicationBeforeQuit is marked as supported for ILST in CEP 6.1 doc but not working

### ISSUE THREAD

**Issue by Jolg42** [Adobe-CEP/CEP-Resources#53]
Hi,

So the event applicationBeforeQuit is marked as supported for Illustrator in the latest doc:
![screenshot 2016-04-06 at 15 14 50](https://cloud.githubusercontent.com/assets/1328733/14317857/81895be2-fc0a-11e5-8d2c-f16fb499c24b.jpg)
See: https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_6.x/CEP_6.1_HTML_Extension_Cookbook.pdf

But I tried it and nothing happened in ILST 19.2.1, other events like applicationActivate are working fine.

![screenshot 2016-04-06 at 15 19 47](https://cloud.githubusercontent.com/assets/1328733/14317992/221368dc-fc0b-11e5-9ce8-f2b733537ea6.jpg)

By the way it is not marked as supported for ILST in older CEP docs -> See [CEP 5](https://github.com/Adobe-CEP/CEP-Resources/wiki/CEP-5-HTML-Extension-Cookbook-for-CC-2014#user-content-standard-events-in-point-products) [CEP 6](https://github.com/Adobe-CEP/CEP-Resources/wiki/CEP-6-HTML-Extension-Cookbook-for-CC-2015#standard-events-in-point-products)

Maybe I missed something or maybe it's not supported?

**Comment by zhangusc** [comment]
Same here. I got the problem today. applicationBeforeQuit Event doesn't get fired in Illustrator.

**Comment by zhangusc** [comment]
With "RegisterExtensionUnloadCallback" deprecated since CEP 6.0 and "applicationBeforeQuit" not working. What event can an CEP extension gets hold with when users close illustrator? Please advise!

**Comment by zhangusc** [comment]
Any progress on this issue? It has been around for a while (2+ years)

**Comment by ErinFinnegan** [comment]
I'll ask the Illustrator team.

**Comment by avartation** [comment]
And it seems nothing has changed since 2 years later :D I have the same problem and no solution, also posted [https://community.adobe.com/t5/premiere-pro/cep-util-registerextensionunloadcallback-returns-err-202/m-p/11081262?page=1#M266296](here)

**Comment by bbb999** [comment]
What does the lack of this functioning callback, keep your extension from doing?

**Comment by avartation** [comment]
My extension run a python local server as it's backend, all the logic is happening in there, when it is being closed it should shutdown the server as well, with http request.

**Comment by bbb999** [comment]
Makes sense.
