### ISSUE TITLE
ExtendScriptToolkit missing file

### ISSUE THREAD

**Issue by Nikomook** [Adobe-CEP/CEP-Resources#535]
Hello. 
I want to install ExtendScriptToolkit on a macbook pro 2010 with MacOs Sierra. But when I want to install it with the .dmg I have this message:
"The installer failed to initialize. A file may not be found. Download Adobe Support Advisor to identify the problem."
How to solve this problem?

**Comment by ErinFinnegan** [comment]
ExtendScript Toolkit stopped working on macOS starting with Mojave.

We recommend the ExtendScript Debugger for VS Code: https://hyperbrew.co/blog/setup-extendscript-dev-for-apple-silicon/  (which, at the time of this writing, will still need Rosetta mode to run)

Another alternative is to emulate Windows and run it that way, on a virtual machine.
