### ISSUE TITLE
Docked CEP extensions auto restart in Photoshop when activated

### ISSUE THREAD

**Issue by zhangusc** [Adobe-CEP/CEP-Resources#55]
This problem only occurs in Photoshop CC 2015, not in illustrator. To reproduce:
1. Start Photoshop
2. Start any of two extensions from extension menu.
3. Dock both extensions to Photoshop.
4. Switch between two extensions by clicking its window tab, you will see the extension get restarted everytime you click.

**Comment by arthurwei1975** [comment]
This is because Photoshop unloads an extension when it is closed, but Illustrator just hides that extension. CEP is a shared component in CC desktop apps. Each app might have different way to integrate it.

**Comment by zhangusc** [comment]
We got it resolved by dispatching "com.adobe.PhotoshopPersistent" in the code. We found The Adobe CEP APIs, as well as its JSX API, works differently in different host applications, which make it difficult to develop a CEP extension that runs across Adobe CC applications as it promised.
