### ISSUE TITLE
submenu missing from flyout menu

### ISSUE THREAD

**Issue by samgannaway** [Adobe-CEP/CEP-Resources#57]
On PS (2015.1.2) and AI I noticed that the flyout menu generated by the CEP HTML Test Panel 1 (6.0/6.1) was missing the submenu items.  Nested MenuItems simply do not appear.

The submenu items still appear for the context menu.

I first noticed while following the Cookbook to create a submenu in my own panel.

**Comment by arthurwei1975** [comment]
The sub menus in flyout menu depends on host application support. As I know, PS and AI do not support, but InDesign supports. Have you tried InDesign?

**Comment by samgannaway** [comment]
Thanks for the information.  The panel is for PS, so I'll just have to leave the menu items on the top level.  It does seem odd that context menus support it while flyout menus don't.
