### ISSUE TITLE
Is this repository actually maintained?

### ISSUE THREAD

**Issue by jmshal** [Adobe-CEP/CEP-Resources#58]
There are a growing number of GitHub issues to this repository, and only a small number have ever received updates/comments from official Adobe-CEP org members.

It seems a little odd to setup a repository & enable GitHub issues when nobody from Adobe seems to actually utilise it. There are numerous bugs which developers, of the Adobe CC extension community, face working around - with very little help from anybody official.

Just wondering whether it's something that you guys plan on focusing on in the future to help stabilise some of the (in my opinion) seriously inconsistent experiences from app to app. And again, in my opinion, listening to the people who actually use your tools may be a good way forward 😝

**Comment by irpye** [comment]
Same concern on my side. I wanted to start developments in CEP for InDesign in my business, but I've heard that Adobe does not want to develop this technology and the CEP team was disbanded.

However, there does not seem to be another technology that is announced to replace CEP.

So, I do not know what to do. This approach was fine for our projects. If anyone has any information, I'm interested.

**Comment by Klustre** [comment]
I'd also like to see a dedicated place for the CEP system, where we can submit feature requests and bugs.

@irpye I find it hard to believe that Adobe abandoned CEP. It's been a success so far and should still be in active development. By all means, start developing with CEP.

**Comment by arthurwei1975** [comment]
I promise that Adobe will continue to invest in CEP technology.

CEP team is pretty busy and cannot answer all questions in this forum. The major purpose of this CEP git site is to publish CEP API, documents, samples, and enable developers to help each other.

CEP is a shared component is almost all CC desktop apps. If you see a CEP issue in a app (such as Photoshop), it might actually be that app's issue. You can also report and seek for help in that app's user forum, or from that app's engineers.

**Comment by jacobmarshall** [comment]
I feel like it's not our responsibility to seek out one particular app's engineers within Adobe. There needs to be a single place in which developers can report CEP related issues - regardless of whether the issue stems from the CEP implementation within the app host itself.

**Comment by arthurwei1975** [comment]
This git site is the place to submit CEP feature requests and bugs. Besides, a lot of developers and partners already have connections with different Adobe product teams. They can also use those channels.

**Comment by jacobmarshall** [comment]
What about the majority of individual developers who have no direct connection to developers/product teams within Adobe? They have an even smaller impact on features/bug reports. And so far I've not seen many, if any, feature requests reviewed here on GitHub for CEP.

**Comment by bbb999** [comment]
Jacob: About "not our responsibility"...

Each Adobe application can integrate a different version of CEP. If you were to (example) go to Arthur, and say "I have a CEP problem!", the first thing he'd need to do is get the specifics of the CEP implementation in the app you're using. Much simpler to start with the product team.

Also, if you're developing integration for an Adobe app, you should probably already be working with the product team.

In that spirit, feel free to write me directly if you encounter any problems with panels in our video apps. ;)

**Comment by jacobmarshall** [comment]
@bbb999 Fair enough, I get all of that. I guess I'm voicing my concerns here as previous attempts to get in touch with somebody have failed miserably. And I know I'm not the only one with these kinds of experiences.

I know I cannot speak for all individual developers writing extensions with CEP, but I know that for those sorts of developers, they/we often times feel like there are few resources with answers to small but obstructive bugs/issues. I am grateful that this repo does cover some of those issues, however some common/frequently reported bugs have yet to be addressed.

**Comment by TomRuark** [comment]
I'm here for Photoshop issues. There are a lot of moving pieces here and as @arthurwei1975 points out. The CEF (Chrome) engine in use. The point product in use. The CEP version in use. We first start pointing figures at each other :-) (whom exactly owns this issue) then try to work towards a solution!

**Comment by jacobmarshall** [comment]
Great, thanks @TomRuark. Though I wonder whether having your org membership visibility set to visible would assist making interactions a bit clearer. And potentially teams separated into apps (`@Adobe-CEP/Photoshop`, or `@Adobe-CEP/InDesign`) would also make it easier to include the people who can assist with app related issues.

Though I'm just trying to remember whether team mentions are typeahead enabled for users outside of the org (maybe not?). Regardless, being able to see who is able to assist, rather than not being able to see whether an individual is actually from Adobe, could be extremely useful for us all.

**Comment by irpye** [comment]
@Klustre: Thank you for advice.
@ Arthurwei1975: thank you for your clear and committed response. Your answer contradicts the information I had received, particularly regarding the dissolution of the CEP team.

**Comment by bbb999** [comment]
@irpye From where, specifically, did you receive that false information?

**Comment by irpye** [comment]
@bbb999 From a commercial contact at Adobe. I was asking for documentation about CEP and i have received this answer.

**Comment by bbb999** [comment]
Who?

**Comment by arthurwei1975** [comment]
I'd like to know who gave the incorrect information either. I am engineering manager of CEP and I know Adobe will continue the investment in CEP technologies and its use in all CC desktop apps.

**Comment by irpye** [comment]
I have not heard that CEP would be removed from future versions of CC. I only heard that Adobe did not want to develop this technology anymore and that the team working on it had been dismantled.
@arthurwei1975: contact me by mail if you want more details on the source.

**Comment by anastasiuspernat** [comment]
@arthurwei1975 Thank you for the answers and clarification, that's good news!

If this repository's main purpose is to publish new updates and sources, where is the place to report bugs that we developers encounter in the CEP? I experience quite a lot of problems with the debugger (https://github.com/Adobe-CEP/CEP-Resources/issues/35), CSS handling, HTML Canvas, ExtendScript communication and other areas of CEP. Is there any chance they are gonna be fixed? Thank you!

**Comment by arthurwei1975** [comment]
Please report bugs here (https://github.com/Adobe-CEP/CEP-Resources/issues). If it is a real CEP bug, we will fix. If it is a bug in dependencies (Chromium, for example), we need to pick up new versions.

There are also some other wonderful CEP resources, such as http://www.davidebarranca.com/.

**Comment by anastasiuspernat** [comment]
Great! Thank you for clarification, @arthurwei1975 ! I'll do it!
