### ISSUE TITLE
Quick Start?

### ISSUE THREAD

**Issue by mhulse** [Adobe-CEP/CEP-Resources#59]
Hi,

I was hoping someone could help me out.

I'd like to start developing extensions, but I need some help with the OS X workflow.

I've disabled signing by doing:

```bash
defaults write com.adobe.CSXS.6 PlayerDebugMode 1
```

And copied the example plugins into:

```bash
~/Library/Application Support/Adobe/CEP/extensions
```

When I restart Illustrator, the plugin does not show under the Extensions menu.

Checking the log files here:

```bash
/Users/USERNAME/Library/Logs/CSXS
```

I don't see anything useful.

I really want to get a workflow figured out so I can start being productive.

Could someone share with me their quick start workflow for Mac OS X? 👍 :octocat: 

Honestly, I think the repos in Adobe-CEP could use a "quick start" section. Maybe this issue could be the start of some new quick start documentation?

Thanks!!!!

**Comment by arthurwei1975** [comment]
Which version of Illustrator are you using?

Can you post your manifest.xml here?

**Comment by mhulse** [comment]
Hi @arthurwei1975, thank you so much for your quick reply, I really appreciate it! 👍

I'm running Illustrator 19.2.1

I've just tried two of the samples from the CEP Samples repo:

RSS Reader
https://github.com/Adobe-CEP/Samples/blob/db6086245ee6b64466710056f60ca324fce12880/RSSReader/CSXS/manifest.xml

XMP Sample
https://github.com/Adobe-CEP/Samples/blob/db6086245ee6b64466710056f60ca324fce12880/XmpSamplePanel/CSXS/manifest.xml

I've tried the RSS Reader in both the system and user extension folders; each time, I've restarted Illustrator before checking the extensions menu.

I'm sure I'm overlooking something obvious. Thanks again for your help!

**Comment by avaneste** [comment]
hi @mhusle, you may have a look to Davide barranca HTML panels book & vidéo tutorial, it's PS oriented but could applied to Illustrator too  http://htmlpanelsbook.com/ Not Free but definitely worth it for me ! It helps me save days on CEP tricky path 
Arnaud.

**Comment by mhulse** [comment]
Thanks for tip @avaneste, I'm looking to buy the book now. 👍

I appreciate the help and reply!

**Comment by undavide** [comment]
Thanks for the plug, @avaneste :-) I did my best to collect everything-CEP in there, and (shouldn't say this myself, but...) feedbacks are great so far.
(if the extension doesn't show up, manifest.xml should be the one to blame)
Thanks,

– Davide

**Comment by Klustre** [comment]
@mhulse Make sure you change:
<Host Name="ILST" Version="[18.0,18.9]"/> in the RSS manifest,
<Host Name="ILST" Version="[17.0,17.9]" /> in the XMP manifest,

to

**Comment by mhulse** [comment]
> <Host Name="ILST" Version="17.0" />

That totally did it! Thanks @Klustre 

So it looks like the steps from my first post are good to go, and it looks like simply changing the `ILST` to `<Host Name="ILST" Version="17.0"/>` did the trick for me in Illustrator `19.x`.

I can't tell you how excited I am to be working with web technologies to create extensions. This is going to be great! Thanks to everyone for the help!

@undavide you book looks awesome! I plan on buying the full package as soon as I have the extra flow 💵 to do so. 👍
