### ISSUE TITLE
CEPEngine_extensions.js

### ISSUE THREAD

**Issue by undavide** [Adobe-CEP/CEP-Resources#6]
Hi,
could you please add (latest) CEPEngine_extensions.js to the list of available resources? Even if it's not required to add it to a project, the source code is helpful anyway as a reference.
Thanks!
Davide

**Comment by undavide** [comment]
Nobody listening? :-) Thanks!

**Comment by gmatthew-adobe** [comment]
Hi David,

We're looking into including this with our next update. 

Apologies for the delay,

Greg

**Comment by arthurwei1975** [comment]
Hi Davide,

I added a copy of CEP 5.2 (for CC 2014) at
https://github.com/arthurwei1975/CEP-Resources/blob/master/CEP_5.x/CEPEngine_extensions.js
I will push to Adobe-CEP repository later.

I also sent you an email with the file attached. Thanks

**Comment by undavide** [comment]
Thank you!!

**Comment by arthurwei1975** [comment]
It is on master branch now.
https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_5.x/CEPEngine_extensions.js
