### ISSUE TITLE
📃 CEP 7 documentation?

### ISSUE THREAD

**Issue by Jolg42** [Adobe-CEP/CEP-Resources#60]
Hi,

Do you know when the CEP 7 documentation will be available here? (As CEP 7 is now in production as of today with app updates like Illustrator 20 - CC2015.3 update)

As an extension developer it's a really important document 😉

**Comment by arthurwei1975** [comment]
We are working on it. Will publish in a couple of days. Thanks

**Comment by arthurwei1975** [comment]
By the way, Photoshop and Illustrator are using CEP 7.0, and other apps are still using CEP 6.1. To install extensions with new apps, please download latest version of ExManCmd from https://www.adobeexchange.com/resources/28.

**Comment by jakkor** [comment]
Hi,

It would be great if you could add some change log to the documentation, or at least new features added.

**Comment by MattMcNam** [comment]
@arthurwei1975 That page says last updated in July 2015, is that the right link?
That version of ExMan doesn't seem to detect Prelude 2015.4 nor Premiere 2015.3

**Comment by rishabhjain9191** [comment]
Hi
Does this release doesn't support the range in version in the manifest ?
For example
<Host Name="PHXS" Version="15.0" />
works with the latest version while
<Host Name="PHXS" Version="[14.0,16.9]" /> doesn't

Why is this happening ?

**Comment by arthurwei1975** [comment]
Can you show your manifest here?

**Comment by rishabhjain9191** [comment]
earlier hoslist information of my manifest was like this
`
<Host Name="PHXS" Version="[14.0,16.9]" />`
`<Host Name="PHSP" Version="[14.0,16.9]" />
`
When I updated my photoshop, it doesn't show the extension any more. As I changed the version like this 
`<Host Name="PHXS" Version="15.0" />`
`<Host Name="PHSP" Version="15.0" />`
It started showing up. Attached the 2 manifests.
[manifest.txt](https://github.com/Adobe-CEP/CEP-Resources/files/328661/manifest.txt)
[manifest_working.txt](https://github.com/Adobe-CEP/CEP-Resources/files/328663/manifest_working.txt)

Also, If I want a single extension for all the CC versions(CC, CC14, CC15) which version should I use as CSXS version and ExtensionManifest Version ?

Thanks

**Comment by undavide** [comment]
@rishabhjain9191 Photoshop CC2015.5 is in fact a major version (17.0): your original manifest.xml doesn't include it – and the Panel won't show up.
If you want to use ranges, it should be `"[14.0,17.9]"` (CC, CC2014, CC2015, CC2015.5), or use the non-array syntax `"14"` (or whatever version, which means: from that very version onwards, without upper limit).
I've posted a quite extensive blogpost covering troubleshooting Panels on CC 2015.5 [here](http://www.davidebarranca.com/2016/06/html-panel-tips-21-photoshop-cc2015-5-2016-survival-guide/).

Davide

**Comment by rishabhjain9191** [comment]
Thank you so much Davide, So silly of me.

**Comment by arthurwei1975** [comment]
We have posted CEP 7.0 documentation and samples.
- https://github.com/Adobe-CEP/CEP-Resources
- https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_7.x
- https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_7.x/Samples

CEP 6.1 documentation has been updated either.

For the CC 2015.x release in June 2016, Photoshop and Illustrator use CEP 7.0, and other apps still use an updated CEP 6.1.

**Comment by Jolg42** [comment]
@arthurwei1975 Thank you! 🙏

**Comment by Jolg42** [comment]
@arthurwei1975 It looks like you put some samples extensions here https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_7.x/Samples but as there is a special repository for that (https://github.com/Adobe-CEP/Samples) I think that can be a source of confusion!

Btw I like .pdf docs but in CEP5 and older the docs were in markdown and it was definitely easier to open on GitHub + easier to do a PR for modifications (if needed) 😉

**Comment by arthurwei1975** [comment]
The CEP sample extensions are updated for each CEP release. It would be better to put them together with that release' API and documentation.

We have CEP cookbook on Adobe internal wiki, which uses a different markup language than markdown. It is hard for us to synchronize all document changes to GitHub wiki.  By converting the wiki to PDF, it is easier for us to provide the cookbook quickly and thoroughly.

**Comment by Jolg42** [comment]
@arthurwei1975 I see what you mean but I think it will confuse people, because the "Samples" repo is here for that & there is no clue for developers that the samples are now here for CEP 7… + it's the first time that samples are added in CEP-Resources.
I think that a least a link in the CEP-Resources README will help people looking for it!

**Comment by arthurwei1975** [comment]
Does the change look good?
https://github.com/Adobe-CEP/Samples/blob/master/README.md

**Comment by Jolg42** [comment]
@arthurwei1975 Perfect 👌!

**Comment by fgregor** [comment]
@MattMcNam You're right that the zips have been updated - the Prelude/Premiere issues you mention are being investigated. I should have more to share in the next few days.

**Comment by Jolg42** [comment]
@rishabhjain9191 I just published a short tutorial with a CEP7 example if you're still interested [https://medium.com/@jolg42/how-to-create-an-html5-javascript-extension-for-adobe-illustrator-photoshop-cc-78921802e248](https://medium.com/@jolg42/how-to-create-an-html5-javascript-extension-for-adobe-illustrator-photoshop-cc-78921802e248#.vcoqlxsnn) 😉
