### ISSUE TITLE
CreativeCloud services within CEP extensions

### ISSUE THREAD

**Issue by franzh** [Adobe-CEP/CEP-Resources#61]
Is it possible to access CC user data via CEP? Just like the CC Libraries panel does in Photoshop.
Thanks!

**Comment by arthurwei1975** [comment]
Theoretically you can do it. However, you need to use some Adobe SDK to handle authentication, authorization, etc. I talked to program manager of Adobe Creative SDK and they are working on it. Basically we need to do some integration between Creative SDK and CEP.

**Comment by franzh** [comment]
Awesome, can't wait to start using this ;)

**Comment by undavide** [comment]
+1 !
