### ISSUE TITLE
Input type color

### ISSUE THREAD

**Issue by gleb-svechnikov** [Adobe-CEP/CEP-Resources#63]
Hello I want to ask about [HTML tag input with type **color** ](https://www.w3.org/TR/html-markup/input.color.html). Right now it is not supported, any chance that it might be working in near future? What is a main limitation for this? I thought Adobe extensions uses fully compatible chromium engine...

**Comment by birduni** [comment]
Hello, as you may know, CEP uses CEF library to render HTML contents. CEF has such limitation (https://bitbucket.org/chromiumembedded/cef/issues/899).
