### ISSUE TITLE
CEP showOpenDialog windows aren't resizable

### ISSUE THREAD

**Issue by derrickb** [Adobe-CEP/CEP-Resources#71]
This is in a Photoshop CC2015 panel running on Windows 10 x64.
When opening dialog windows via either option, eg:

`window.cep.fs.showOpenDialog`
or
`window.cep.fs.showOpenDialogEx`

The dialog windows are locked at a fairly small size and aren't resizable.  It's a big enough usability concern that I've switched to using HTML's file input element until these native dialogs are more flexible.

Ironically, ExtendScript's `Folder.openDlg` seems to offer the most usable window out of all options, but it's a bit cumbersome to have to call from the panel to JSX to get a file path to return back to the panel again.

**Comment by arthurwei1975** [comment]
This sounds like a bug. We will have a look and get back to you. Thanks

**Comment by VishakhaVaidya** [comment]
Thanks for reporting that, Derrick. Its a bug with open dialog function. Folder open and save dialogs are resizable. We will fix it in the next release.

**Comment by VishakhaVaidya** [comment]
This is fixed in CEP 7.0.0.59
