### ISSUE TITLE
Signing / Timestamping feat. request: please get rid of them.

### ISSUE THREAD

**Issue by undavide** [Adobe-CEP/CEP-Resources#74]
I might sound slightly subversive here, but is there still a point at all with signing / timestamping?

The shared feeling with many other developers is that building a ZXP, then uncompress it and deploy the resulting folder for manual installation (in other words: not relying upon ExManCmd, which as a CLI is **definitely not a viable answer** for the user of third party panels to the lack of installation software like Adobe Extension Manager) is such a delicate process that many things can go wrong – and they very likely do.

I'm flooded with complaints about "Extension not properly signed" popups – some of them very random, like a user with two machines, one is OK the other has signing problems.
We have of course the Debug Flag, but it's not a viable option for customers, because some of them might not want to mess with the Regedit app – they feel like it's "unsafe".

So, I'm asking: why do we sign & timestamp at all? 90% of developers I know now use self signed certificates; we have the debug flag; isn't this just a fake lock we can afford to get rid of?

Developing panels is already enough of a problematic matter, to struggle also when deploying our products looks like an extra burden we could happily live without.

Thank you very much for listening,

Davide Barranca

**Comment by arthurwei1975** [comment]
Where did you get the  "Extension not properly signed" popups? From ExManCmd, or CEP, or anything else?

**Comment by undavide** [comment]
In my case in Photoshop, at panel's load time – let's say: in the host application.

A well known InDesign developer told me that he uses to build and then uncompress the ZXP once on Mac, once on Windows (in order to have one panel folder for each platform).
They should be 100% identical, but when dealing with such a delicate process it might be beneficial – when you inspect a folder with Finder on Mac, hidden files might be written (which can compromise the signature).
Same thing with unzipping softwares – e.g. I've been reported that "Mac OS un-archiving utility almost always changes the byte length of .zxp files (thereby breaking the signing)". 
I wonder whether there are "legal" reasons to have signing, because practically speaking, from my (possibly biased) point of view, there are only downsides.

I apologize for being so openly frustrated, but this issue has severe repercussions on developer's businesses.

Thank you,

Davide

**Comment by arthurwei1975** [comment]
The extension signature and validation are for security and legal reasons. I do not think we can just remove it.

If you find any unzipping software changes any file or add any hidden file, and breaks signature validation, please provide the details to us. This sounds like a bug and should be fixed in our ZXPSign library/tool and CEP.

Thanks

**Comment by ErinFinnegan** [comment]
We've dropped the signing requirement from UXP, so I'm closing this.
