### ISSUE TITLE
ModalDialog: how to hide the close button or get unload event

### ISSUE THREAD

**Issue by WinkyW** [Adobe-CEP/CEP-Resources#77]
HI,

I have two extensiosns. Extension1 (Panel) fires an event to open Extension 2 (ModalDialog). When the Extension 2 is closed, the Extension 1 needs know that and has to do some actions. 

- Is it possible to disable or hide the close button/ box in the title bar? Than I can created a custom close button on the page, when the user clicks on the custom close button, a close event will be fired before I close this extension.
- or is it possible to have an unload event when the ModalDialog is closed? since CEP 6.0 the "RegisterExtensionUnloadCallback" is deprecated. Any workarounds for this situation?

**Comment by yugguo** [comment]
Hello, it is not supported to disable or hide the close button in the title bar. When an extension is unloaded, CEP event "com.adobe.csxs.events.ExtensionUnloaded" is sent out with the data "<ExtensionUnloadedEvent><Id>your_extension_id</Id><ClosingType>close_type</ClosingType></ExtensionUnloadedEvent>".

**Comment by WinkyW** [comment]
Thanks you yugguo, it seems to work.
May I ask you how did you know this solution/event? I read the HTML Extension Cookbook, Extension SDK and some other documentations/ forums, I cannot find anything about this event. Any other relevant documentation than the HTML Extension Cookbook?

**Comment by yugguo** [comment]
Hello, this is an internal event in CEP. I'll update the HTML Extension Cookbook in the next release.

**Comment by WinkyW** [comment]
Thanks for the information.
