### ISSUE TITLE
CEP is not refreshing node_modules on reload?

### ISSUE THREAD

**Issue by Jolg42** [Adobe-CEP/CEP-Resources#81]
Hi,

I found that node_modules packages in for a CEP extension are not refreshed on extension reload/execution in Photoshop & Illustrator, do you have a node_modules cache in place?

It would be really nice to force this refresh because right now the only solution to refresh the node_modules is to restart the application.

**Comment by venpa** [comment]
Hello,
      Are you not getting extensions refreshed when you close and re-open extension's window?

**Comment by Jolg42** [comment]
Hi @venpa,

No... 

In Illustrator closing and reopening is not reloading the extension (or the nodes_modules).
In Photoshop, I have the Persistent Mode ON, so it's the same behavior as Illustrator.

And doing a `window.location.reload()` is not reloading the node_modules.

Maybe I can try to put the Persistent Mode OFF in Photoshop to check. But this mode does not exists in Illustrator.

**Comment by venpa** [comment]
@Jolg42 : Yes, please try with persistent mode Off. The purpose of persistent is to force not reload HTML extension when it is closed or hidden.

**Comment by Jolg42** [comment]
@venpa Indeed! It's working for Photoshop with Persistent Mode OFF 👍 

Thanks for your help.

I guess we just need to tell the Illustrator team that this mode is useful (and maybe they will add it?). 😉

**Comment by leizongmin** [comment]
@venpa Hi, how to set the persistent mode off in After Effects?

**Comment by Jolg42** [comment]
@leizongmin If it's like Illustrator, you can't ... But maybe @venpa knows!

**Comment by Jolg42** [comment]
Here are some examples for Photoshop by the way https://github.com/search?q=PhotoshopPersistent&type=Code&utf8=%E2%9C%93
