### ISSUE TITLE
Zxp Package doesn't install correctly

### ISSUE THREAD

**Issue by zhangusc** [Adobe-CEP/CEP-Resources#82]
I have used both the Adobe Exchange Packager and command tool ZxpSignCmd.exe to create a zxp package based on MXI file which delivers some files to Illustrator folders. The zxp gets created, But when I install the package using ExManCmd.exe, nothing is installed to the destination. Below is the commands I have used and also my sample MXI file for creating the zxp. Does anyone know what causes the problem?

> ZXPSignCmd.exe -sign D:\Temp\MXI com.myCompany.test.zxp My_Cert.p12 123456 (succeed)
> ExManCmd.exe /install D:\Temp\com.myCompany.test.zxp (nothing installed, no error message)

![image](https://cloud.githubusercontent.com/assets/7468979/19318889/3f9e6a94-905f-11e6-98db-6dce2236ccd5.png)

**Comment by zhangusc** [comment]
@arthurwei1975 This becomes an impediment for us to publish our extension to Adobe Exchange. Any ideas/comments are highly appreciated.

**Comment by venpa** [comment]
@zhangusc: Looks like your steps are correct. Is it possible to share the extension with us? ZXPSign dev team would like to have a look at this issue.

**Comment by zhangusc** [comment]
@venpa The new version of ExManCmd (https://www.adobeexchange.com/resources/28) solves the problem.  I am able to package and install the extension using MXI file.
