### ISSUE TITLE
cep.fs API is missing copyFile, copyDir functions

### ISSUE THREAD

**Issue by zhangusc** [Adobe-CEP/CEP-Resources#83]
The current cep.fs API provides methods to read/write files, but is missing methods to copy files/directories between places.

**Comment by venpa** [comment]
Hello,
CEP provides access to the Node.js APIs.  So you can do something like:
var fs = require("fs");
fs.createReadStream('myfile.txt').pipe(fs.createWriteStream('mynewfile.txt'));

For dir copy, you can follow: http://stackoverflow.com/questions/13786160/copy-folder-recursively-in-node-js#answer-22185855

You can also use any nodejs modules for doing the same. node modules should be placed at the root dir of extension.

**Comment by zhangusc** [comment]
@venpa Thank you for the suggestion. I end up with using jsx copying files and folders. It is a little easier for me to get the Host applications (ILST/PS) and extension installation folders.
