### ISSUE TITLE
Documentation for CEP8 (2017 release)?

### ISSUE THREAD

**Issue by Jolg42** [Adobe-CEP/CEP-Resources#89]
Hi,

The 2017 release looks really good 😀 👍  but I haven't seen anything yet about some CEP changes/news/docs...!

Do you plan to publish something here, for us developers, soon? ping @arthurwei1975 😉

**Comment by bbb999** [comment]
Each application integrates different versions of CEP; any updates will be application-specific.

I'll be updating PProPanel later on today, but nothing in it has changed at the CEP level; we still integrate and expose CEP 6.1.

**Comment by Jolg42** [comment]
@bbb999 Ok so the latest version is still CEP 7(.0?) in Illustrator & Photoshop (was released in Illustrator 2015.3 & Photoshop 2015.5)?

**Comment by bbb999** [comment]
I have no visibility into the Photoshop or Illustrator teams' plans.

The latest CEP version I've heard of in the wild is 7.0.

All video apps (PPro, AE, Prelude, AME) use CEP 6.1; haven't checked Audition, which may have gone straight to CEP 7.

What features/fixes are you hoping for, in new CEP versions?

**Comment by Jolg42** [comment]
@bbb999 I was just excited to hear about a new CEP version because I was used to a new release of CEP at each major release of Photoshop & Illustrator 😃

So it's not a problem for me if it's still CEP7.0 now as we don't have any major bug in CEP to be fixed. But I'm always happy to see updates / changes / new features / deprecations / for developing extensions.
