### ISSUE TITLE
CEP 4

### ISSUE THREAD

**Issue by albmaso** [Adobe-CEP/CEP-Resources#9]
Readme.md in CEP-RESOURCES refers that "The Creative Suite 6 and the Creative Cloud 2013 releases of Adobe desktop applications support CEP 4".
This means that HTML5/JS developments can be possible in CS6?
CS6 not works with CSXS 3? It can be possible update to CEP 4?

Thanks

**Comment by arthurwei1975** [comment]
CS6 works with CSXS 3. It cannot be upgraded to CEP 4.  (CSXS is the old name of CEP).
CC 2013 works with CEP 4.
CC 2014 works with CEP 5.

Thanks

**Comment by albmaso** [comment]
So CS6  only supports Flex/AS3 extensions and not HTML5/JS extensions ?
HTML5/JS extensions with CC2013 onwards?
Thanks

**Comment by arthurwei1975** [comment]
Yes
