### ISSUE TITLE
Any news on CC 2017 Documentation

### ISSUE THREAD

**Issue by DouglasJMorris** [Adobe-CEP/CEP-Resources#90]
Is there any documentation yet for CC 2017. In particular I have several InDesign extensions which don't work in CC 2017. Perhaps InDesign has now been updated to run CEP 7.0 but I can't find any documentation.

**Comment by undavide** [comment]
Hi Douglas,
I have no idea whether ID now supports CEP7 or not, yet if you log `new CSInterface().getCurrentApiVersion()` in the Console, you should be able to find out that yourself.

As for CEP7 documentation, it should already be in place. We had CEP 7 in "our" previous Photoshop major version CC2015.5, and it didn't change in CC2017.

Hope this helps!

Davide Barranca

**Comment by DouglasJMorris** [comment]
Thanks for your help. I've discovered that a CEP manifest requires the following for InDesign CC 2017:
```
	<HostList>
		<Host Name="IDSN" Version="12.0"> 
	</HostList>
```
and that `CSInterface().getCurrentApiVersion()` returns 7.0.0 so it is indeed now using CEP 7.
