### ISSUE TITLE
Documentation on Premiere Pro ExtendScript API

### ISSUE THREAD

**Issue by bhstahl** [Adobe-CEP/CEP-Resources#92]
👋  Adobe folks,

With the Premiere Pro ExtendScript API, I can bind event handlers on the app object, such as:

```js
app.encoder.bind('onEncoderJobComplete', $._PPP_.onEncoderJobComplete);
```

Do you have any documentation on what events are supported that I may have overlooked? The only relevant documentation I can see is in the [sample repo](https://github.com/Adobe-CEP/Samples/blob/master/PProPanel/payloads/api_doc.html).

For example, I'm looking to do something in my app every time the active sequence changes.

Thanks!

**Comment by bhstahl** [comment]
Chatted with @bbb999 on email and the encoder events in the sample repo are a special case. Closing in favor of the feature request.

**Comment by lichuan80** [comment]
@bhstahl  Could you please share the details from bbb, if you still have them? 

What's the nature of the "onEncoderJobComplete" event?   Is it a translation of an event from some underlying messaging system, like BridgeTalk? 

What does app.encoder.bind() do under the hood? Is the method  implemented in ExtendScript or native code? 

Recently I am looking for this same API for AE that can does what app.encoder.bind  does. 

I am suspecting  app.encoder just to be a layer above BridgeTalk. If it’s true,  this might can be ported to AE and I might be able to do that. 

Thanks

**Comment by bhstahl** [comment]
Hi @lichuan80, unfortunately this was a bit too long ago so it evades both my memory and ability to search documentation/email/comments/etc. Best of luck figuring it out.

**Comment by lichuan80** [comment]
Thank you!
