### ISSUE TITLE
[Documentation] Misspelling of CEF Command Parameter in Cookbook (6.1)

### ISSUE THREAD

**Issue by ericdrobinson** [Adobe-CEP/CEP-Resources#94]
The _[CEP_6.1_HTML_Extension_Cookbook.pdf](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_6.x/CEP_6.1_HTML_Extension_Cookbook.pdf)_ contains a misspelling in the last parameter of the table in the **Commonly used CEF command parameters** section. Instead of`--mixed-context`, the content reads `--mixed-conext`. Note the missing 't' in "context".

**Comment by sujaisivanandan** [comment]
fixed in CEP 10
