### ISSUE TITLE
Show Extension Panel on Startup - But with "Do not show again" Option

### ISSUE THREAD

**Issue by Jens44** [Adobe-CEP/CEP-Resources#95]
Hey guys,
I have a HTML extension panel which is displayed on startup of Photoshop.
To to achieve this my manifest.xml looks like:
```
<Lifecycle>
            <AutoVisible>true</AutoVisible>
            <StartOn>
                <Event>com.adobe.csxs.events.AppOnline</Event>
            </StartOn>
</Lifecycle>
```
So far everything is easy and works fine.
 
But now the difficult part…
I want to implement a function that allows the user to disable the display of the panel on startup.
For example the panel should contain a checkbox "Do not show on startup".
 
Have you any idea how to do this?
 
so far I had two ideas:
1) Change the manifest.xml if checkbox is clicked. But this would require a new signing of the extension.
2) Maybe it is also possible to generate a custom AppOnline-Event which additionally checks the state whether the window should or shouldn’t be displayed.
The state „DoNotShowOnStartup=true/false“ could be stored in a textfile or in registry. Unfortunately therefore OS-depending code (Mac/Win) would be needed.

Photoshop has also a welcome screen which is displayed per default. But there is no checkbox in panel to disable the window. You have to disable this in Preferences. Maybe because it’s not possible? (Hopefully not)

I would be very pleased to receive your answers or ideas (:
regards Jens

**Comment by bbb999** [comment]
I think having the panel rely upon a text-based prefs file seems appropriate.

**Comment by jingtaotan** [comment]
Here are 2 ideas:

1. Let the panel autostart on Photoshop launch, read a text-based prefs file. If the prefs file says the panel should not autostart, close the panel immediately by using `CSInterface.closeExtension()`
The user may see a sudden flash of the panel though.

2. Have 2 extensions in your extension bundle: one is your panel extension, another is a hidden extension (see https://github.com/Adobe-CEP/Samples/tree/master/CEP_HTML_Invisible_Extension for an example)
The hidden extension will auto-start on Photoshop launch, read a text-based prefs file. If the prefs file says the panel should autostart, open the panel by using `CSInterface.requestOpenExtension(extensionId, "")`

We currently use #2 for our extension. Hope that helps!

**Comment by stompychump** [comment]
If you prefer to avoid a text prefs file, you can also store values in the Photoshop registry, which is OS-independent. See the app.eraseCustomOptions, .getCustomOptions, and .putCustomOptions methods in the Photoshop JavaScript Scripting Reference. A GUID/UUID works well as a unique key, and you can call these methods from an HTML panel using CSInterface.evalScript().

**Comment by Jens44** [comment]
Hey guys,
thank you very much for you replies!
@jingtaotan: Your second idea to use a second hidden extension is excellent! That's exactly what I need.
@stompychump: Of course I would prefer to avoid OS-depending code and text pref files. So I like your approach to use the PS registry very much! I had never heard of this before.

So I will try to combine both of your ideas: A second hidden extension, which reads the information whether the main extension should be started or not from the PS registry.
(I hope I can manage this.)

So far you were a great help! Thank you!
Jens
