### ISSUE TITLE
CSInterface.isWindowVisible() Returns String, Not Boolean

### ISSUE THREAD

**Issue by stompychump** [Adobe-CEP/CEP-Resources#97]
CSInterface.isWindowVisible() currently returns the string "true" or "false". Suggestion: it would be more usable (and a better match with the method name) if it returned a boolean.

**Comment by undavide** [comment]
@stompychump may I ask you what the use of `isWindowVisible` is – I never got it, I'm sure I miss something evident here.
Thank you

**Comment by stompychump** [comment]
@undavide: Sorry for the long delay!

In persistent panels, `isWindowVisible()` returns the string `"true"` if the panel is open and `"false"` if it is closed. In non-persistent panels it always returns `"true"`, perforce.

Also: thanks for your many helpful articles and posts about HTML panels.
